"""What CI runs, and the promise that you can run it yourself.

Two failures on one pull request on 2026-09-18 could not be reproduced locally:
the only copy of each command was inline shell inside a workflow yaml. The
remedy is that every gate lives in a script -- so these tests pin that the
workflows call the scripts, that the scripts exist and are executable, and that
`scripts/ci/local.sh` still runs the same list the runbook tells authors to run.

The other half is the path-aware lane. `pr-tests.yml` must keep reporting the
contexts branch protection requires (`guards-and-preflight`, `fast-suite (1)`
through `(6)`) on every event, while doing no work when the diff touches nothing
the shards can observe. That is a shape a later edit can break silently -- a
renamed job leaves a required context permanently unreported and no pull request
can merge again -- so the shape is pinned here rather than discovered on a
Friday.
"""

from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
WORKFLOW_DIR = REPO / ".github" / "workflows"
PR_TESTS = WORKFLOW_DIR / "pr-tests.yml"
LINT = WORKFLOW_DIR / "lint.yml"
LOCAL_SH = REPO / "scripts" / "ci" / "local.sh"
RUNBOOK = REPO / "docs" / "agent" / "agent-runbook.mdx"
CLASSIFY_SH = REPO / "scripts" / "ci" / "classify_changes.sh"

_SPEC = importlib.util.spec_from_file_location(
    "changed_paths", REPO / "scripts" / "ci" / "changed_paths.py"
)
assert _SPEC is not None and _SPEC.loader is not None
changed_paths = importlib.util.module_from_spec(_SPEC)
sys.modules[_SPEC.name] = changed_paths
_SPEC.loader.exec_module(changed_paths)

HEAVY_JOBS = ("guards-and-preflight", "fast-suite")


def workflow_files() -> list[Path]:
    return sorted(WORKFLOW_DIR.glob("*.yml"))


def load(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def run_blocks(node: object) -> list[str]:
    """Every `run:` script anywhere in a workflow document."""
    found: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "run" and isinstance(value, str):
                found.append(value)
            else:
                found += run_blocks(value)
    elif isinstance(node, list):
        for item in node:
            found += run_blocks(item)
    return found


# --------------------------------------------------------------------------
# Every workflow parses
# --------------------------------------------------------------------------


def test_the_workflow_directory_is_not_empty() -> None:
    """A glob that silently matches nothing would make every test below vacuous."""
    assert len(workflow_files()) >= 5, [p.name for p in workflow_files()]


@pytest.mark.parametrize(
    "path", workflow_files(), ids=lambda p: p.name
)
def test_every_workflow_parses(path: Path) -> None:
    data = load(path)
    assert isinstance(data, dict), f"{path.name} is not a mapping"
    assert data.get("jobs"), f"{path.name} declares no jobs"


# --------------------------------------------------------------------------
# No attacker-controlled expression reaches a shell
# --------------------------------------------------------------------------

#: Contexts that a `run:` block may interpolate. Each is generated by the
#: workflow itself -- the matrix entry, a previous step's output, a dependency's
#: output, the job's own env -- and none of them can carry text a pull-request
#: author wrote.
SAFE_RUN_CONTEXTS = ("matrix.", "needs.", "steps.", "env.", "runner.", "job.", "strategy.")

_EXPRESSION = re.compile(r"\$\{\{(.+?)\}\}", re.DOTALL)


def _unsafe_expressions(block: str) -> list[str]:
    bad = []
    for match in _EXPRESSION.finditer(block):
        body = match.group(1).strip()
        if not body.startswith(SAFE_RUN_CONTEXTS):
            bad.append(match.group(0))
    return bad


@pytest.mark.parametrize("path", workflow_files(), ids=lambda p: p.name)
def test_no_event_data_is_interpolated_into_a_run_block(path: Path) -> None:
    """A PR body, title or branch name is attacker-controlled text.

    ``${{ }}`` inside a ``run:`` block splices it into the shell before the
    shell ever sees a quote, which is a script injection. Event data reaches a
    script through ``env:`` instead, where it is only ever a variable.

    The rule is written as an allowlist of contexts the workflow generates for
    itself (``matrix.group``, a previous step's output) rather than a blocklist
    of ``github.event.*``: a context added to GitHub Actions next year is
    forbidden here until someone decides it is safe.
    """
    offenders = {
        expression
        for block in run_blocks(load(path))
        for expression in _unsafe_expressions(block)
    }
    assert not offenders, (
        f"{path.name}: pass these through `env:` instead of interpolating them "
        f"into `run:` — {sorted(offenders)}"
    )


# --------------------------------------------------------------------------
# pr-tests.yml: the required contexts, and the path-aware gate
# --------------------------------------------------------------------------


def test_the_required_job_names_still_exist() -> None:
    """Branch protection requires these contexts BY NAME.

    A rename leaves every required check permanently unreported and blocks every
    merge until someone edits branch protection, which is not visible from the
    repository.
    """
    jobs = load(PR_TESTS)["jobs"]
    for name in HEAVY_JOBS:
        assert name in jobs, f"pr-tests.yml no longer defines a `{name}` job"


def test_the_fast_suite_still_reports_six_groups_under_the_protected_names() -> None:
    fast = load(PR_TESTS)["jobs"]["fast-suite"]
    assert fast["strategy"]["matrix"]["group"] == [1, 2, 3, 4, 5, 6]
    # The 3.10 entry must render as `fast-suite (<group>)`; a plain matrix over
    # two python versions would render `fast-suite (3.10, 1)` and unreport every
    # required context.
    assert "format('fast-suite ({0})', matrix.group)" in fast["name"]


def test_the_changes_job_exists_and_publishes_the_verdict() -> None:
    jobs = load(PR_TESTS)["jobs"]
    assert "changes" in jobs, "pr-tests.yml has no `changes` job"
    outputs = jobs["changes"].get("outputs") or {}
    assert "code_changed" in outputs, outputs
    assert "steps.classify.outputs.code_changed" in outputs["code_changed"]


def test_the_changes_job_checks_out_full_history() -> None:
    """A shallow clone cannot find the merge base the diff is taken from."""
    steps = load(PR_TESTS)["jobs"]["changes"]["steps"]
    checkout = [s for s in steps if str(s.get("uses", "")).startswith("actions/checkout")]
    assert checkout, "the changes job does not check out the repository"
    assert checkout[0].get("with", {}).get("fetch-depth") == 0


def test_the_changes_job_delegates_to_the_tested_script() -> None:
    blocks = run_blocks(load(PR_TESTS)["jobs"]["changes"])
    assert any("scripts/ci/classify_changes.sh" in b for b in blocks), blocks


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_the_heavy_jobs_wait_for_the_verdict(job: str) -> None:
    needs = load(PR_TESTS)["jobs"][job].get("needs")
    needs = [needs] if isinstance(needs, str) else list(needs or [])
    assert "changes" in needs, f"`{job}` does not depend on `changes`"


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_every_step_after_checkout_is_gated_on_the_verdict(job: str) -> None:
    """The JOB always runs; only its steps are conditional.

    GitHub's "Troubleshooting required status checks" says a job skipped by a
    conditional reports Success, so a job-level `if:` would satisfy the required
    context too. Step level is still what this repo uses: a skipped job shows no
    steps and no reason, and an ungated step that installs the package or runs
    pytest would spend the 35 minutes the gate exists to save.
    """
    steps = load(PR_TESTS)["jobs"][job]["steps"]
    ungated = [
        step.get("name", step.get("uses", "?"))
        for step in steps[1:]
        if "needs.changes.outputs.code_changed" not in str(step.get("if", ""))
    ]
    assert not ungated, f"`{job}` steps run regardless of the verdict: {ungated}"


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_a_skipped_job_says_why_in_its_log(job: str) -> None:
    """A green job that did nothing has to explain itself, or it reads as a pass."""
    steps = load(PR_TESTS)["jobs"][job]["steps"]
    explainers = [
        step
        for step in steps
        if "code_changed == 'false'" in str(step.get("if", ""))
    ]
    assert len(explainers) == 1, f"`{job}` has {len(explainers)} explanation steps"
    assert "scripts/ci/changed_paths.py" in str(explainers[0].get("run", ""))


def test_pushes_to_main_still_trigger_the_lane() -> None:
    triggers = load(PR_TESTS).get("on", load(PR_TESTS).get(True))
    assert triggers["push"]["branches"] == ["main"]
    assert "pull_request" in triggers


# --------------------------------------------------------------------------
# The gates are scripts, and the workflows call them
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "script",
    ["lint.sh", "docs_hygiene.sh", "local.sh", "classify_changes.sh", "changed_paths.py"],
)
def test_the_ci_scripts_exist_and_are_executable(script: str) -> None:
    path = REPO / "scripts" / "ci" / script
    assert path.is_file(), f"missing {path}"
    assert os.access(path, os.X_OK), f"{path} is not executable (chmod +x)"


def test_the_lint_workflow_calls_the_scripts_rather_than_inlining_them() -> None:
    blocks = run_blocks(load(LINT))
    assert any("scripts/ci/lint.sh" in b for b in blocks), blocks
    assert any("scripts/ci/docs_hygiene.sh" in b for b in blocks), blocks
    joined = "\n".join(blocks)
    assert "ruff check" not in joined, "the ruff line is inline again"
    assert "grep -rn" not in joined, "the hygiene grep is inline again"


def test_the_lint_workflow_still_declares_both_jobs() -> None:
    jobs = load(LINT)["jobs"]
    assert "ruff" in jobs and "agent-docs-hygiene" in jobs, list(jobs)


# --------------------------------------------------------------------------
# local.sh and the runbook say the same thing
# --------------------------------------------------------------------------

_RUNBOOK_SENTENCE = "`scripts/ci/local.sh` runs, in order:"


def _local_sh_steps() -> list[str]:
    match = re.search(r"^STEP_NAMES=\(([^)]*)\)", LOCAL_SH.read_text(encoding="utf-8"), re.M)
    assert match, "scripts/ci/local.sh no longer declares STEP_NAMES=(...)"
    return match.group(1).split()


def _runbook_steps() -> list[str]:
    for line in RUNBOOK.read_text(encoding="utf-8").splitlines():
        if line.startswith(_RUNBOOK_SENTENCE):
            tail = line[len(_RUNBOOK_SENTENCE):].strip().rstrip(".")
            return [part.strip() for part in tail.split(",") if part.strip()]
    raise AssertionError(
        f"the runbook has no line starting {_RUNBOOK_SENTENCE!r} — authors are "
        "told to run a list that no longer exists"
    )


def test_local_sh_and_the_runbook_list_the_same_steps_in_the_same_order() -> None:
    assert _local_sh_steps() == _runbook_steps()


def test_local_sh_runs_the_real_entry_points() -> None:
    """Not a re-implementation: the same files CI calls."""
    text = LOCAL_SH.read_text(encoding="utf-8")
    for entry_point in (
        "scripts/ci/lint.sh",
        "scripts/ci/docs_hygiene.sh",
        "scripts/changelog/assemble.py --check",
        "scripts/ci/check_pr_body.py --file",
        "pytest tests/contracts",
    ):
        assert entry_point in text, f"scripts/ci/local.sh no longer runs {entry_point}"


def test_the_runbook_tells_authors_to_run_it_before_every_push() -> None:
    text = RUNBOOK.read_text(encoding="utf-8")
    assert "run `scripts/ci/local.sh` before every push" in text


# --------------------------------------------------------------------------
# The path classifier
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("paths", "expected"),
    [
        ([], False),
        (["docs/agent/agent-runbook.mdx", "docs/guides/support_matrix.md"], False),
        (["scripts/dev/prune_worktrees.py", "scripts/ci/check_pr_body.py"], False),
        ([".github/workflows/lint.yml", ".github/pull_request_template.md"], False),
        (["changelog.d/1112.ci.md", "README.md", "CHANGELOG.md"], False),
        (["rfx/core/yee.py"], True),
        (["docs/guides/known_limitations.md", "tests/contracts/test_x.py"], True),
        (["validation/crossval/manifest.json"], True),
        (["examples/waveguide/msl.py"], True),
        (["pyproject.toml"], True),
        (["setup.cfg"], True),
        ([".test_durations"], True),
        (["conftest.py"], True),
        ([".github/workflows/pr-tests.yml"], True),
        (["scripts/ci/changed_paths.py"], True),
        (["scripts/ci/classify_changes.sh"], True),
    ],
    ids=[
        "empty", "docs-only", "scripts-only", "other-workflows", "changelog-and-readme",
        "one-rfx-file", "docs-plus-one-test", "validation", "examples", "pyproject",
        "setup-cfg", "durations", "root-conftest", "the-lane-itself", "the-classifier",
        "the-classifier-shell",
    ],
)
def test_code_changed(paths: list[str], expected: bool) -> None:
    assert changed_paths.code_changed(paths) is expected


def test_a_directory_that_merely_starts_with_a_code_prefix_is_not_code() -> None:
    """`rfx/` is a prefix of `rfx-studio-notes/` only if you forget the slash."""
    assert changed_paths.code_changed(["rfx-notes/scratch.md"]) is False
    assert changed_paths.code_changed(["testsuite-design.md"]) is False
    assert changed_paths.code_changed(["docs/setup.md"]) is False


def test_paths_are_normalised_before_they_are_classified() -> None:
    assert changed_paths.code_changed(["./rfx/core/yee.py"]) is True
    assert changed_paths.code_changed(["  rfx/core/yee.py  "]) is True
    assert changed_paths.code_changed([""]) is False


def test_a_nested_conftest_or_durations_file_counts() -> None:
    assert changed_paths.code_changed(["studio/conftest.py"]) is True
    assert changed_paths.code_changed(["gallery-deploy/.test_durations"]) is True


def test_matching_paths_names_what_forced_the_verdict() -> None:
    paths = ["docs/a.md", "rfx/core/yee.py", "scripts/x.py"]
    assert changed_paths.matching_paths(paths) == ["rfx/core/yee.py"]


def test_the_classifier_cli_prints_true_or_false() -> None:
    def verdict(*args: str) -> str:
        result = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "ci" / "changed_paths.py"), *args],
            capture_output=True, text=True, timeout=60, check=True,
        )
        return result.stdout.strip()

    assert verdict("docs/agent/agent-runbook.mdx") == "false"
    assert verdict("rfx/core/yee.py") == "true"
    assert verdict() == "false"


# --------------------------------------------------------------------------
# The shell around the classifier fails open
# --------------------------------------------------------------------------


def _classify(env: dict[str, str], tmp_path: Path) -> tuple[str, str]:
    output = tmp_path / "github_output"
    output.touch()
    result = subprocess.run(
        ["bash", str(CLASSIFY_SH)],
        cwd=REPO,
        env={
            "PATH": os.environ.get("PATH", ""),
            "HOME": os.environ.get("HOME", "/tmp"),
            "GITHUB_OUTPUT": str(output),
            **env,
        },
        capture_output=True, text=True, timeout=120,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return output.read_text(encoding="utf-8").strip(), result.stdout


def test_a_push_to_main_is_never_skipped(tmp_path: Path) -> None:
    """main is what releases, the GPU lane and the weekly suite are cut from."""
    written, log = _classify({"EVENT_NAME": "push"}, tmp_path)
    assert written == "code_changed=true", log


def test_a_diff_that_cannot_be_computed_runs_everything(tmp_path: Path) -> None:
    written, log = _classify(
        {"EVENT_NAME": "pull_request", "BASE_SHA": "not-a-sha", "HEAD_SHA": "HEAD"},
        tmp_path,
    )
    assert written == "code_changed=true", log


def test_a_missing_base_sha_runs_everything(tmp_path: Path) -> None:
    written, log = _classify({"EVENT_NAME": "pull_request"}, tmp_path)
    assert written == "code_changed=true", log
