"""What CI runs, and the promise that you can run it yourself.

Two failures on one pull request on 2026-09-18 could not be reproduced locally:
the only copy of each command was inline shell inside a workflow yaml. The
remedy is that every gate lives in a script -- so these tests pin that the
workflows call the scripts, that the scripts exist and are executable, and that
`scripts/ci/local.sh` still runs the same list the runbook tells authors to run.

The other half is the path-aware lane. `pr-tests.yml` must keep reporting the
contexts branch protection requires (`guards-and-preflight`, `fast-suite (1)`
through `(6)`) on every event, while doing no work when the diff touches nothing
the shards can observe. That is a shape a later edit can break silently -- a
renamed job leaves a required context permanently unreported and no pull request
can merge again -- so the shape is pinned here rather than discovered on a
Friday.
"""

from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
WORKFLOW_DIR = REPO / ".github" / "workflows"
PR_TESTS = WORKFLOW_DIR / "pr-tests.yml"
LINT = WORKFLOW_DIR / "lint.yml"
LOCAL_SH = REPO / "scripts" / "ci" / "local.sh"
RUNBOOK = REPO / "docs" / "agent" / "agent-runbook.mdx"
CLASSIFY_SH = REPO / "scripts" / "ci" / "classify_changes.sh"

_SPEC = importlib.util.spec_from_file_location(
    "changed_paths", REPO / "scripts" / "ci" / "changed_paths.py"
)
assert _SPEC is not None and _SPEC.loader is not None
changed_paths = importlib.util.module_from_spec(_SPEC)
sys.modules[_SPEC.name] = changed_paths
_SPEC.loader.exec_module(changed_paths)

HEAVY_JOBS = ("guards-and-preflight", "fast-suite")


def workflow_files() -> list[Path]:
    return sorted(WORKFLOW_DIR.glob("*.yml"))


def load(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def run_blocks(node: object) -> list[str]:
    """Every `run:` script anywhere in a workflow document."""
    found: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "run" and isinstance(value, str):
                found.append(value)
            else:
                found += run_blocks(value)
    elif isinstance(node, list):
        for item in node:
            found += run_blocks(item)
    return found


# --------------------------------------------------------------------------
# Every workflow parses
# --------------------------------------------------------------------------


def test_the_workflow_directory_is_not_empty() -> None:
    """A glob that silently matches nothing would make every test below vacuous."""
    assert len(workflow_files()) >= 5, [p.name for p in workflow_files()]


@pytest.mark.parametrize(
    "path", workflow_files(), ids=lambda p: p.name
)
def test_every_workflow_parses(path: Path) -> None:
    data = load(path)
    assert isinstance(data, dict), f"{path.name} is not a mapping"
    assert data.get("jobs"), f"{path.name} declares no jobs"


# --------------------------------------------------------------------------
# No attacker-controlled expression reaches a shell
# --------------------------------------------------------------------------

#: Contexts that a `run:` block may interpolate. Each is generated by the
#: workflow itself -- the matrix entry, a previous step's output, a dependency's
#: output, the job's own env -- and none of them can carry text a pull-request
#: author wrote.
SAFE_RUN_CONTEXTS = ("matrix.", "needs.", "steps.", "env.", "runner.", "job.", "strategy.")

_EXPRESSION = re.compile(r"\$\{\{(.+?)\}\}", re.DOTALL)


def _unsafe_expressions(block: str) -> list[str]:
    bad = []
    for match in _EXPRESSION.finditer(block):
        body = match.group(1).strip()
        if not body.startswith(SAFE_RUN_CONTEXTS):
            bad.append(match.group(0))
    return bad


@pytest.mark.parametrize("path", workflow_files(), ids=lambda p: p.name)
def test_no_event_data_is_interpolated_into_a_run_block(path: Path) -> None:
    """A PR body, title or branch name is attacker-controlled text.

    ``${{ }}`` inside a ``run:`` block splices it into the shell before the
    shell ever sees a quote, which is a script injection. Event data reaches a
    script through ``env:`` instead, where it is only ever a variable.

    The rule is written as an allowlist of contexts the workflow generates for
    itself (``matrix.group``, a previous step's output) rather than a blocklist
    of ``github.event.*``: a context added to GitHub Actions next year is
    forbidden here until someone decides it is safe.
    """
    offenders = {
        expression
        for block in run_blocks(load(path))
        for expression in _unsafe_expressions(block)
    }
    assert not offenders, (
        f"{path.name}: pass these through `env:` instead of interpolating them "
        f"into `run:` — {sorted(offenders)}"
    )


# --------------------------------------------------------------------------
# pr-tests.yml: the required contexts, and the path-aware gate
# --------------------------------------------------------------------------


def test_the_required_job_names_still_exist() -> None:
    """Branch protection requires these contexts BY NAME.

    A rename leaves every required check permanently unreported and blocks every
    merge until someone edits branch protection, which is not visible from the
    repository.
    """
    jobs = load(PR_TESTS)["jobs"]
    for name in HEAVY_JOBS:
        assert name in jobs, f"pr-tests.yml no longer defines a `{name}` job"


def test_the_fast_suite_still_reports_six_groups_under_the_protected_names() -> None:
    fast = load(PR_TESTS)["jobs"]["fast-suite"]
    assert fast["strategy"]["matrix"]["group"] == [1, 2, 3, 4, 5, 6]
    # The 3.10 entry must render as `fast-suite (<group>)`; a plain matrix over
    # two python versions would render `fast-suite (3.10, 1)` and unreport every
    # required context.
    assert "format('fast-suite ({0})', matrix.group)" in fast["name"]


def test_the_changes_job_exists_and_publishes_the_verdict() -> None:
    jobs = load(PR_TESTS)["jobs"]
    assert "changes" in jobs, "pr-tests.yml has no `changes` job"
    outputs = jobs["changes"].get("outputs") or {}
    assert "code_changed" in outputs, outputs
    assert "steps.classify.outputs.code_changed" in outputs["code_changed"]


def test_the_changes_job_checks_out_full_history() -> None:
    """A shallow clone cannot find the merge base the diff is taken from."""
    steps = load(PR_TESTS)["jobs"]["changes"]["steps"]
    checkout = [s for s in steps if str(s.get("uses", "")).startswith("actions/checkout")]
    assert checkout, "the changes job does not check out the repository"
    assert checkout[0].get("with", {}).get("fetch-depth") == 0


def test_the_changes_job_delegates_to_the_tested_script() -> None:
    blocks = run_blocks(load(PR_TESTS)["jobs"]["changes"])
    assert any("scripts/ci/classify_changes.sh" in b for b in blocks), blocks


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_the_heavy_jobs_wait_for_the_verdict(job: str) -> None:
    needs = load(PR_TESTS)["jobs"][job].get("needs")
    needs = [needs] if isinstance(needs, str) else list(needs or [])
    assert "changes" in needs, f"`{job}` does not depend on `changes`"


#: The only two `if:` forms a step in a heavy job may carry.
WORK_IF = "needs.changes.outputs.code_changed != 'false'"
SKIP_IF = "needs.changes.outputs.code_changed == 'false'"

#: Steps that legitimately run on BOTH branches, because both need them: an
#: interpreter and the installed package. Matched against `uses:` or `run:`.
SHARED_SETUP = ("actions/setup-python", "pip install -e")


def _is_shared_setup(step: dict) -> bool:
    text = f"{step.get('uses', '')} {step.get('run', '')}"
    return any(marker in text for marker in SHARED_SETUP)


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_the_first_step_is_the_checkout(job: str) -> None:
    """Every test below reasons about "the steps after checkout"."""
    first = load(PR_TESTS)["jobs"][job]["steps"][0]
    assert str(first.get("uses", "")).startswith("actions/checkout"), first


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_every_step_after_checkout_is_gated_on_the_verdict(job: str) -> None:  # noqa: D401
    """The JOB always runs; only its steps are conditional.

    GitHub's "Troubleshooting required status checks" says a job skipped by a
    conditional reports Success, so a job-level `if:` would satisfy the required
    context too. Step level is still what this repo uses: a skipped job shows no
    steps and no reason, and an ungated step that runs the fast suite would spend
    the half hour the gate exists to save.

    The exception is the shared setup -- an interpreter and the package -- which
    both branches need, because the false branch still runs the contract tests.

    The `steps[1:]` slice is only meaningful if step 0 really is the checkout, so
    this asserts it here rather than trusting a sibling test to have run: a step
    inserted above the checkout would otherwise slip out of the scan.
    """
    steps = load(PR_TESTS)["jobs"][job]["steps"]
    assert str(steps[0].get("uses", "")).startswith("actions/checkout"), (
        f"`{job}` step 0 is not the checkout, so everything below scans the "
        f"wrong steps: {steps[0]}"
    )
    ungated = [
        step.get("name", step.get("uses", "?"))
        for step in steps[1:]
        if not str(step.get("if", "")).strip()
        and not _is_shared_setup(step)
    ]
    assert not ungated, f"`{job}` steps run regardless of the verdict: {ungated}"


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_work_steps_skip_only_on_the_one_known_value(job: str) -> None:
    """`!= 'false'`, never `== 'true'`.

    A third value -- an empty output because the classify step died after its
    checkout, or a refactor that renames the output -- makes `== 'true'` skip
    EVERY step including the one that explains itself, and the job goes green in
    silence having run nothing. `!= 'false'` degrades the other way: anything
    unexpected runs the full lane. Only the single value the classifier is known
    to emit for "nothing to see" skips anything.
    """
    steps = load(PR_TESTS)["jobs"][job]["steps"]
    wrong = [
        (step.get("name", "?"), step["if"])
        for step in steps
        if str(step.get("if", "")).strip()
        and str(step["if"]).strip() not in (WORK_IF, SKIP_IF)
    ]
    assert not wrong, (
        f"`{job}`: a step gates on something other than {WORK_IF!r} (do the work) "
        f"or {SKIP_IF!r} (the skip path): {wrong}"
    )


@pytest.mark.parametrize("job", HEAVY_JOBS)
def test_a_skipped_job_says_why_in_its_log(job: str) -> None:
    """A green job that did nothing has to explain itself, or it reads as a pass."""
    steps = load(PR_TESTS)["jobs"][job]["steps"]
    explainers = [step for step in steps if str(step.get("if", "")).strip() == SKIP_IF]
    assert len(explainers) == 1, f"`{job}` has {len(explainers)} explanation steps"
    assert "scripts/ci/changed_paths.py" in str(explainers[0].get("run", ""))


# --------------------------------------------------------------------------
# The contract tests run on BOTH branches of the verdict
# --------------------------------------------------------------------------


def test_the_contract_tests_run_when_the_diff_is_not_code() -> None:
    """The gates that watch `docs/` and `scripts/` must survive a docs diff.

    Much of `tests/contracts/` asserts on `docs/`, `scripts/`,
    `.github/workflows/`, `CHANGELOG.md` and `README.md` -- the paths the
    classifier calls not-code. Skipping them on a docs-only PR disarms exactly
    the gates that guard docs: a later PR could shrink the ruff scope pinned by
    `test_the_lint_scope_covers_this_gates_own_script`, and the test forbidding
    it would never run.
    """
    steps = load(PR_TESTS)["jobs"]["guards-and-preflight"]["steps"]
    on_the_skip_path = [
        str(step.get("run", ""))
        for step in steps
        if str(step.get("if", "")).strip() == SKIP_IF
    ]
    assert on_the_skip_path, "guards-and-preflight has no not-code branch at all"
    assert any(
        "pytest tests/contracts" in block for block in on_the_skip_path
    ), f"the not-code branch does not run the contract tests: {on_the_skip_path}"


def test_the_contract_tests_run_when_the_diff_is_code() -> None:
    """On the code branch the six shards collect the whole tree, contracts included."""
    fast = load(PR_TESTS)["jobs"]["fast-suite"]
    suite = "\n".join(
        str(step.get("run", ""))
        for step in fast["steps"]
        if "--splits" in str(step.get("run", ""))
    )
    assert suite, "the fast-suite job no longer runs a sharded pytest"
    assert "tests/contracts" not in suite, (
        "the sharded suite now names tests/contracts explicitly -- check it is "
        f"not being ignored: {suite}"
    )
    assert re.search(r"--ignore=tests/crossval", suite), (
        "the ignore list changed shape; re-read what the shards now exclude"
    )


def test_the_setup_steps_the_skip_path_needs_are_not_themselves_skipped() -> None:
    """Running the contracts on the false branch needs a Python and the package."""
    steps = load(PR_TESTS)["jobs"]["guards-and-preflight"]["steps"]
    shared = [step for step in steps if _is_shared_setup(step)]
    assert len(shared) == 2, [s.get("name") for s in shared]
    for step in shared:
        assert not str(step.get("if", "")).strip(), (
            f"{step.get('name')!r} is gated, so the not-code branch cannot run "
            "the contract tests"
        )


def test_the_workflow_asks_for_changes_to_be_a_required_check() -> None:
    """`needs: changes` is a hole until `changes` is required.

    A `changes` job that dies of a runner fault leaves both heavy jobs SKIPPED by
    dependency, and a skipped job does not fail a required context -- so a merge
    would go through having run no tests. Requiring `changes` closes it; the job
    is a checkout and a stdlib script.
    """
    text = PR_TESTS.read_text(encoding="utf-8")
    assert "`changes` MUST BE A REQUIRED CHECK" in text
    runbook = RUNBOOK.read_text(encoding="utf-8")
    assert "`changes` must be a required check too" in runbook


def test_pushes_to_main_still_trigger_the_lane() -> None:
    triggers = load(PR_TESTS).get("on", load(PR_TESTS).get(True))
    assert triggers["push"]["branches"] == ["main"]
    assert "pull_request" in triggers


# --------------------------------------------------------------------------
# The gates are scripts, and the workflows call them
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "script",
    ["lint.sh", "docs_hygiene.sh", "local.sh", "classify_changes.sh", "changed_paths.py"],
)
def test_the_ci_scripts_exist_and_are_executable(script: str) -> None:
    path = REPO / "scripts" / "ci" / script
    assert path.is_file(), f"missing {path}"
    assert os.access(path, os.X_OK), f"{path} is not executable (chmod +x)"


def test_the_lint_workflow_calls_the_scripts_rather_than_inlining_them() -> None:
    blocks = run_blocks(load(LINT))
    assert any("scripts/ci/lint.sh" in b for b in blocks), blocks
    assert any("scripts/ci/docs_hygiene.sh" in b for b in blocks), blocks
    joined = "\n".join(blocks)
    assert "ruff check" not in joined, "the ruff line is inline again"
    assert "grep -rn" not in joined, "the hygiene grep is inline again"


def test_the_lint_workflow_still_declares_both_jobs() -> None:
    jobs = load(LINT)["jobs"]
    assert "ruff" in jobs and "agent-docs-hygiene" in jobs, list(jobs)


# --------------------------------------------------------------------------
# local.sh and the runbook say the same thing
# --------------------------------------------------------------------------

_RUNBOOK_SENTENCE = "`scripts/ci/local.sh` runs, in order:"


def _local_sh_steps() -> list[str]:
    match = re.search(r"^STEP_NAMES=\(([^)]*)\)", LOCAL_SH.read_text(encoding="utf-8"), re.M)
    assert match, "scripts/ci/local.sh no longer declares STEP_NAMES=(...)"
    return match.group(1).split()


def _runbook_steps() -> list[str]:
    for line in RUNBOOK.read_text(encoding="utf-8").splitlines():
        if line.startswith(_RUNBOOK_SENTENCE):
            tail = line[len(_RUNBOOK_SENTENCE):].strip().rstrip(".")
            return [part.strip() for part in tail.split(",") if part.strip()]
    raise AssertionError(
        f"the runbook has no line starting {_RUNBOOK_SENTENCE!r} — authors are "
        "told to run a list that no longer exists"
    )


def test_local_sh_and_the_runbook_list_the_same_steps_in_the_same_order() -> None:
    assert _local_sh_steps() == _runbook_steps()


def test_local_sh_runs_the_real_entry_points() -> None:
    """Not a re-implementation: the same files CI calls."""
    text = LOCAL_SH.read_text(encoding="utf-8")
    for entry_point in (
        "scripts/ci/lint.sh",
        "scripts/ci/docs_hygiene.sh",
        "scripts/ci/check_changelog_fragment.py",
        "scripts/ci/check_pr_body.py --file",
        "pytest tests/contracts",
    ):
        assert entry_point in text, f"scripts/ci/local.sh no longer runs {entry_point}"


def test_local_sh_runs_the_changelog_gate_ci_runs_not_a_lookalike() -> None:
    """`assemble.py --check` answers a different question.

    It validates fragment names and headings. It never notices a MISSING fragment
    on a change under `rfx/`, nor a `CHANGELOG.md` edit without the `release`
    label -- and those two are the whole of what `changelog-fragment.yml`
    enforces. Running only the lookalike locally is how a red CI check surprises
    someone who ran the local gate first.
    """
    local = LOCAL_SH.read_text(encoding="utf-8")
    workflow_scripts = "\n".join(run_blocks(load(WORKFLOW_DIR / "changelog-fragment.yml")))
    assert "scripts/ci/check_changelog_fragment.py" in workflow_scripts
    assert "scripts/ci/check_changelog_fragment.py" in local, (
        "local.sh does not run the script the changelog-fragment workflow runs"
    )
    assert "--base" in local and "--head" in local


def test_every_local_step_can_pick_its_interpreter() -> None:
    """One `PYTHON=` covers the whole run, ruff included.

    `scripts/ci/lint.sh` called a bare `ruff`, which usually lives only in the
    project venv -- so `local.sh` failed at step 1 for anyone who had not
    activated it, which is exactly the "you cannot run what CI runs" problem
    these scripts exist to remove.
    """
    lint = (REPO / "scripts" / "ci" / "lint.sh").read_text(encoding="utf-8")
    ruff_lines = [
        line for line in lint.splitlines()
        if "ruff check" in line and not line.lstrip().startswith("#")
    ]
    assert len(ruff_lines) == 1, ruff_lines
    assert '"$PYTHON" -m ruff check' in ruff_lines[0], (
        f"lint.sh depends on a bare `ruff` on PATH: {ruff_lines[0].strip()!r}"
    )
    assert 'PYTHON="${PYTHON:-python3}"' in lint

    local = LOCAL_SH.read_text(encoding="utf-8")
    assert 'export PYTHON="${PYTHON:-python3}"' in local, (
        "local.sh does not export PYTHON, so the scripts it calls ignore it"
    )


def test_the_runbook_tells_authors_to_run_it_before_every_push() -> None:
    text = RUNBOOK.read_text(encoding="utf-8")
    assert "run `scripts/ci/local.sh` before every push" in text


# --------------------------------------------------------------------------
# The path classifier
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("paths", "expected"),
    [
        ([], False),
        (["docs/agent/agent-runbook.mdx", "docs/guides/support_matrix.md"], False),
        (["scripts/dev/prune_worktrees.py", "scripts/ci/check_pr_body.py"], False),
        ([".github/workflows/lint.yml", ".github/pull_request_template.md"], False),
        (["changelog.d/1112.ci.md", "README.md", "CHANGELOG.md"], False),
        (["rfx/core/yee.py"], True),
        (["docs/guides/known_limitations.md", "tests/contracts/test_x.py"], True),
        (["validation/crossval/manifest.json"], True),
        (["examples/waveguide/msl.py"], True),
        (["pyproject.toml"], True),
        (["setup.cfg"], True),
        ([".test_durations"], True),
        (["conftest.py"], True),
        ([".github/workflows/pr-tests.yml"], True),
        (["scripts/ci/changed_paths.py"], True),
        (["scripts/ci/classify_changes.sh"], True),
    ],
    ids=[
        "empty", "docs-only", "scripts-only", "other-workflows", "changelog-and-readme",
        "one-rfx-file", "docs-plus-one-test", "validation", "examples", "pyproject",
        "setup-cfg", "durations", "root-conftest", "the-lane-itself", "the-classifier",
        "the-classifier-shell",
    ],
)
def test_code_changed(paths: list[str], expected: bool) -> None:
    assert changed_paths.code_changed(paths) is expected


def test_a_directory_that_merely_starts_with_a_code_prefix_is_not_code() -> None:
    """`rfx/` is a prefix of `rfx-studio-notes/` only if you forget the slash."""
    assert changed_paths.code_changed(["rfx-notes/scratch.md"]) is False
    assert changed_paths.code_changed(["testsuite-design.md"]) is False
    assert changed_paths.code_changed(["docs/setup.md"]) is False


def test_paths_are_normalised_before_they_are_classified() -> None:
    assert changed_paths.code_changed(["./rfx/core/yee.py"]) is True
    assert changed_paths.code_changed(["  rfx/core/yee.py  "]) is True
    assert changed_paths.code_changed([""]) is False


def test_a_nested_conftest_or_durations_file_counts() -> None:
    assert changed_paths.code_changed(["studio/conftest.py"]) is True
    assert changed_paths.code_changed(["gallery-deploy/.test_durations"]) is True


def test_matching_paths_names_what_forced_the_verdict() -> None:
    paths = ["docs/a.md", "rfx/core/yee.py", "scripts/x.py"]
    assert changed_paths.matching_paths(paths) == ["rfx/core/yee.py"]


def test_the_classifier_cli_prints_true_or_false() -> None:
    def verdict(*args: str) -> str:
        result = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "ci" / "changed_paths.py"), *args],
            capture_output=True, text=True, timeout=60, check=True,
        )
        return result.stdout.strip()

    assert verdict("docs/agent/agent-runbook.mdx") == "false"
    assert verdict("rfx/core/yee.py") == "true"
    assert verdict() == "false"


# --------------------------------------------------------------------------
# The shell around the classifier fails open
# --------------------------------------------------------------------------


def _classify(env: dict[str, str], tmp_path: Path) -> tuple[str, str]:
    output = tmp_path / "github_output"
    output.touch()
    result = subprocess.run(
        ["bash", str(CLASSIFY_SH)],
        cwd=REPO,
        env={
            "PATH": os.environ.get("PATH", ""),
            "HOME": os.environ.get("HOME", "/tmp"),
            "GITHUB_OUTPUT": str(output),
            **env,
        },
        capture_output=True, text=True, timeout=120,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return output.read_text(encoding="utf-8").strip(), result.stdout


def test_a_push_to_main_is_never_skipped(tmp_path: Path) -> None:
    """main is what releases, the GPU lane and the weekly suite are cut from."""
    written, log = _classify({"EVENT_NAME": "push"}, tmp_path)
    assert written == "code_changed=true", log


def test_a_diff_that_cannot_be_computed_runs_everything(tmp_path: Path) -> None:
    written, log = _classify(
        {"EVENT_NAME": "pull_request", "BASE_SHA": "not-a-sha", "HEAD_SHA": "HEAD"},
        tmp_path,
    )
    assert written == "code_changed=true", log


def test_a_missing_base_sha_runs_everything(tmp_path: Path) -> None:
    written, log = _classify({"EVENT_NAME": "pull_request"}, tmp_path)
    assert written == "code_changed=true", log


# --------------------------------------------------------------------------
# A rename moves a file OUT of the code set, and must be seen
# --------------------------------------------------------------------------


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo,
        capture_output=True, text=True, timeout=60,
        env={
            "PATH": os.environ.get("PATH", ""),
            "HOME": str(repo),
            "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.invalid",
            "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.invalid",
            "GIT_CONFIG_GLOBAL": str(repo / "gitconfig"),
            "GIT_CONFIG_SYSTEM": "/dev/null",
        },
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return result.stdout.strip()


def _repo_with_a_rename(tmp_path: Path) -> tuple[Path, str, str]:
    """A repo where `rfx/mod.py` was renamed to `docs/mod.py`, nothing else."""
    repo = tmp_path / "repo"
    (repo / "rfx").mkdir(parents=True)
    (repo / "docs").mkdir()
    (repo / "rfx" / "mod.py").write_text("x = 1\n" * 40, encoding="utf-8")
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "base")
    base = _git(repo, "rev-parse", "HEAD")
    _git(repo, "mv", "rfx/mod.py", "docs/mod.py")
    _git(repo, "commit", "-qm", "move it out of the package")
    return repo, base, _git(repo, "rev-parse", "HEAD")


def test_a_rename_out_of_the_package_is_seen_as_a_code_change(tmp_path: Path) -> None:
    """`git mv rfx/mod.py docs/mod.py` deletes a module the suite imports.

    `git diff --name-only` reports a rename as its DESTINATION only, so without
    `--no-renames` this diff reads as `docs/mod.py` alone -- a docs-only change
    -- and the suite that just lost a module would not run. Git only calls it a
    rename when similarity detection fires, which is why the fixture moves a file
    big enough to be detected.
    """
    repo, base, head = _repo_with_a_rename(tmp_path)

    # The defect, reproduced: without --no-renames the destination is all you see.
    naive = _git(repo, "diff", "--name-only", f"{base}...{head}").split()
    assert naive == ["docs/mod.py"], naive
    assert changed_paths.code_changed(naive) is False

    # What the script actually asks for.
    both = _git(repo, "diff", "--name-only", "--no-renames", f"{base}...{head}").split()
    assert sorted(both) == ["docs/mod.py", "rfx/mod.py"], both
    assert changed_paths.code_changed(both) is True

    output = tmp_path / "github_output"
    output.touch()
    result = subprocess.run(
        ["bash", str(CLASSIFY_SH)],
        cwd=repo,
        env={
            "PATH": os.environ.get("PATH", ""),
            "HOME": str(repo),
            "GITHUB_OUTPUT": str(output),
            "EVENT_NAME": "pull_request",
            "BASE_SHA": base,
            "HEAD_SHA": head,
        },
        capture_output=True, text=True, timeout=120,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert output.read_text(encoding="utf-8").strip() == "code_changed=true", result.stdout


def test_the_classifier_shell_asks_git_for_both_rename_endpoints() -> None:
    """Pinned in the file too: each flag is one word and easy to drop."""
    text = CLASSIFY_SH.read_text(encoding="utf-8")
    # Lines that INVOKE git, not the one that echoes the command into the log.
    invocation = re.compile(r"(?:^\s*|!\s*)git diff\b")
    diffs = [
        line for line in text.splitlines()
        if invocation.search(line) and not line.lstrip().startswith("#")
    ]
    assert len(diffs) == 2, f"expected the push diff and the PR diff, got {diffs}"
    for line in diffs:
        assert "--no-renames" in line, f"rename endpoints would be lost: {line.strip()}"
        assert " -z " in line, f"a quoted path would be misread: {line.strip()}"
    assert "--stdin --null" in text, "the classifier is not told the paths are NUL-separated"


# --------------------------------------------------------------------------
# A path git would have to quote
# --------------------------------------------------------------------------


def test_a_path_containing_a_quote_survives_the_pipe(tmp_path: Path) -> None:
    """`git diff --name-only` C-quotes an awkward name; `-z` does not.

    A file at `rfx/od"d.py` comes back from a plain `--name-only` as the literal
    seven-plus characters `"rfx/od\\"d.py"`, quotes included. That does not start
    with `rfx/`, so the module that changed reads as not-code and the suite does
    not run. With `-z` the name arrives verbatim.
    """
    repo = tmp_path / "quoted"
    (repo / "rfx").mkdir(parents=True)
    _git(repo, "init", "-q", "-b", "main")
    (repo / "rfx" / "ok.py").write_text("x = 1\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "base")
    base = _git(repo, "rev-parse", "HEAD")

    awkward = 'rfx/od"d.py'
    (repo / awkward).write_text("y = 2\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "add an awkward name")
    head = _git(repo, "rev-parse", "HEAD")

    # The defect, reproduced: the quoted rendering is not a path under rfx/.
    quoted = _git(repo, "diff", "--name-only", f"{base}...{head}").split("\n")
    assert quoted == ['"rfx/od\\"d.py"'], quoted
    assert changed_paths.code_changed(quoted) is False

    # NUL-separated, the name arrives as itself.
    raw = subprocess.run(
        ["git", "diff", "-z", "--name-only", "--no-renames", f"{base}...{head}"],
        cwd=repo, capture_output=True, timeout=60, check=True,
        env={"PATH": os.environ.get("PATH", ""), "HOME": str(repo),
             "GIT_CONFIG_GLOBAL": str(repo / "gitconfig"),
             "GIT_CONFIG_SYSTEM": "/dev/null"},
    ).stdout.decode("utf-8")
    assert [f for f in raw.split("\0") if f] == [awkward]
    assert changed_paths.code_changed([f for f in raw.split("\0") if f]) is True

    output = tmp_path / "github_output"
    output.touch()
    result = subprocess.run(
        ["bash", str(CLASSIFY_SH)],
        cwd=repo,
        env={
            "PATH": os.environ.get("PATH", ""), "HOME": str(repo),
            "GITHUB_OUTPUT": str(output), "EVENT_NAME": "pull_request",
            "BASE_SHA": base, "HEAD_SHA": head,
        },
        capture_output=True, text=True, timeout=120,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert output.read_text(encoding="utf-8").strip() == "code_changed=true", result.stdout


def test_the_classifier_cli_reads_nul_separated_paths() -> None:
    script = REPO / "scripts" / "ci" / "changed_paths.py"

    def verdict(blob: str) -> str:
        return subprocess.run(
            [sys.executable, str(script), "--stdin", "--null"],
            input=blob, capture_output=True, text=True, timeout=60, check=True,
        ).stdout.strip()

    assert verdict("docs/a.md\0docs/b.md\0") == "false"
    assert verdict('rfx/od"d.py\0') == "true"
    # A name holding a newline is exactly what line splitting cannot survive.
    assert verdict("docs/two\nlines.md\0rfx/mod.py\0") == "true"
    assert verdict("docs/two\nlines.md\0") == "false"


# --------------------------------------------------------------------------
# Build configuration that does not exist yet
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "path",
    ["requirements.txt", "requirements-dev.txt", "MANIFEST.in", "pytest.ini", "tox.ini",
     "setup.py", "setup.cfg"],
)
def test_build_configuration_is_code_even_before_it_exists(path: str) -> None:
    """None of these are in the tree today; only `pyproject.toml` is.

    They are classified in advance because the failure is silent: someone adds a
    `requirements.txt`, the dependency set moves out from under the shards, and
    nothing says so. Listing them costs a line each.
    """
    assert changed_paths.code_changed([path]) is True


def test_a_requirements_file_that_is_not_the_build_is_not_code() -> None:
    """Root-scoped on purpose: the docs build has its own."""
    assert changed_paths.code_changed(["docs/requirements.txt"]) is False
