"""Excitation sources for FDTD simulation."""
# ruff: noqa: F401

from rfx.sources.sources import GaussianPulse, add_point_source, add_lumped_port
from rfx.sources.coaxial_port import (
    CoaxialPort,
    CoaxialPlaneSourceSpec,
    CoaxialTEMCartesianPlaneVI,
    setup_coaxial_port,
    add_coaxial_matched_termination,
    add_coaxial_open_termination,
    add_coaxial_pec_end_cap,
    make_coaxial_port_source,
    build_coaxial_tem_plane_source_specs,
    extract_coaxial_plane_vi_from_dft,
    CoaxialTEMReferencePlaneVI,
    coaxial_load_reflection,
    coaxial_tem_capacitance_per_m,
    coaxial_tem_characteristic_impedance,
    coaxial_tem_inductance_per_m,
    coaxial_tem_phase_constant,
    coaxial_tem_reference_plane_vi_from_cartesian_plane,
    coaxial_tem_reference_plane_s11,
    coaxial_tem_reference_plane_vi,
    CoaxialLineReflection,
    coaxial_line_plane_voltage,
    coaxial_line_reflection_from_plane_voltages,
    stamp_coaxial_line,
    stamp_coaxial_short_plane,
    stamp_coaxial_annular_resistor,
    SMA_PIN_RADIUS,
    SMA_OUTER_RADIUS,
    PTFE_EPS_R,
)
from rfx.sources.waveguide_port import (
    WaveguidePort,
    WaveguidePortConfig,
    init_waveguide_port,
    inject_waveguide_port,
    apply_waveguide_port_h,
    apply_waveguide_port_e,
    update_waveguide_port_probe,
    extract_waveguide_port_waves,
    extract_waveguide_s_matrix,
    extract_waveguide_sparams,
    extract_waveguide_s11,
    extract_waveguide_s21,
    waveguide_plane_positions,
    solve_rectangular_modes,
    init_multimode_waveguide_port,
    extract_multimode_s_matrix,
)
