"""WI-1 regression tests for JAX-native MSL S-matrix assembly (S1 base)."""

from __future__ import annotations

from pathlib import Path
from types import MethodType, SimpleNamespace

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from rfx.api import Simulation
from rfx.boundaries.spec import Boundary, BoundarySpec
from rfx.geometry.csg import Box
from rfx.probes.probes import DFTPlaneProbe
from tests._msl_ad_objective import msl_band_mean_s21_sq
from tests.test_msl_port_integration import (
    DX,
    EPS_R,
    F_MAX,
    H_SUB,
    L_LINE,
    LX,
    LY,
    LZ,
    PORT_MARGIN,
    W_TRACE,
)

# ---------------------------------------------------------------------------
# Fixture paths (S1-base, regenerated by scripts/capture_msl_replay_fixture.py)
# ---------------------------------------------------------------------------

REPLAY_ACCUMULATORS_PATH = (
    Path(__file__).resolve().parent
    / "fixtures"
    / "msl_replay_accumulators.npz"
)
REPLAY_GOLDEN_F64_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "msl_replay_golden_f64.npy"
)

# Slow end-to-end golden: pre-change S1 numpy output captured before assembly
# was converted.  Must NOT be regenerated from post-change code.
E2E_GOLDEN_PATH = (
    Path(__file__).resolve().parent
    / "fixtures"
    / "msl_s_matrix_golden.npy"
)


def _build_thru_line_sim() -> Simulation:
    sim = Simulation(
        freq_max=F_MAX,
        domain=(LX, LY, LZ),
        dx=DX,
        cpml_layers=8,
        boundary=BoundarySpec(
            x="cpml",
            y="cpml",
            z=Boundary(lo="pec", hi="cpml"),
        ),
    )
    sim.add_material("ro4350b", eps_r=EPS_R)
    sim.add(Box((0.0, 0.0, 0.0), (LX, LY, H_SUB)), material="ro4350b")

    y_centre = LY / 2.0
    trace_y_lo = y_centre - W_TRACE / 2.0
    trace_y_hi = y_centre + W_TRACE / 2.0
    sim.add(
        Box((0.0, trace_y_lo, H_SUB), (LX, trace_y_hi, H_SUB + DX)),
        material="pec",
    )
    sim.add_msl_port(
        position=(PORT_MARGIN, y_centre, 0.0),
        width=W_TRACE,
        height=H_SUB,
        direction="+x",
        impedance=50.0,
    )
    sim.add_msl_port(
        position=(PORT_MARGIN + L_LINE, y_centre, 0.0),
        width=W_TRACE,
        height=H_SUB,
        direction="-x",
        impedance=50.0,
    )
    return sim


# ---------------------------------------------------------------------------
# Replay helpers
# ---------------------------------------------------------------------------

def _make_replay_fake_run(acc_data: dict, run_idx: int):
    """Return a sim.run replacement that replays captured accumulators.

    The real FDTD scanner is NEVER called.  dft_planes is populated from
    pre-captured complex64 arrays.  Under enable_x64(True) the assembly
    calls jnp.asarray(..., dtype=complex_dtype) where complex_dtype evaluates
    to complex128, so the c64 replayed arrays are upcast to c128 — exactly
    what the float64 equivalence gate tests.
    """
    def fake_run(self, *, n_steps=None, num_periods=1.0, compute_s_params=False):
        del n_steps, num_periods, compute_s_params
        planes = {}
        for key, arr in acc_data.items():
            if not key.startswith(f"run{run_idx}__"):
                continue
            plane_name = key[len(f"run{run_idx}__"):]
            planes[plane_name] = SimpleNamespace(accumulator=arr)
        return SimpleNamespace(dft_planes=planes)
    return fake_run


def _load_replay_accumulators():
    """Load captured accumulator .npz and return (data_dict, freqs)."""
    npz = np.load(REPLAY_ACCUMULATORS_PATH)
    freqs = npz["freqs"]
    data = {k: npz[k] for k in npz.files if k != "freqs"}
    return data, freqs


def _run_assembly_with_replay(acc_data: dict, freqs_replay: np.ndarray, *,
                               use_x64: bool) -> np.ndarray:
    """Run compute_msl_s_matrix assembly with replayed accumulators.

    The real FDTD is never called.  Only the post-run assembly (V/I
    integration and de-embedding) runs under the requested x64 setting.
    """
    try:
        # Modern JAX promoted the scoped x64 context manager to top-level;
        # jax.experimental.enable_x64 was removed in v0.8.0.
        from jax import enable_x64
    except ImportError:  # older JAX (< ~0.4.31)
        from jax.experimental import enable_x64

    sim = _build_thru_line_sim()
    freqs_jnp = jnp.asarray(freqs_replay, dtype=jnp.float32)

    run_counter = [0]

    def counting_fake_run(self, *, n_steps=None, num_periods=1.0,
                           compute_s_params=False):
        r = run_counter[0]
        run_counter[0] += 1
        fake = _make_replay_fake_run(acc_data, r)
        return fake(self, n_steps=n_steps, num_periods=num_periods,
                    compute_s_params=compute_s_params)

    sim.run = MethodType(counting_fake_run, sim)

    with enable_x64(use_x64):
        result = sim.compute_msl_s_matrix(
            n_steps=1,
            freqs=freqs_jnp,
            num_periods=1.0,
            # The golden pins the RAW assembly (V/I integration +
            # de-embedding). Passivity projection is a separate, later stage
            # with its own tests (test_msl_passivity_enforcement.py); leaving
            # it on would make this compare projection against assembly.
            enforce_passivity=False,
        )

    return np.asarray(result.S, dtype=np.complex128)


# ---------------------------------------------------------------------------
# Test A: replay float64 equivalence (FAST — runs in default gate)
# ---------------------------------------------------------------------------

def test_replay_float64_equivalence():
    """Assembly under x64 on replayed c64 accumulators must match numpy-f64 golden.

    Gate: atol=1e-5.  Both jnp-x64 and numpy assemble from the SAME captured
    complex64 FDTD accumulators upcast to complex128 — structural equivalence
    must hold to near-machine-epsilon (observed ~1e-13).

    This test NEVER invokes the real FDTD scanner under x64.  sim.run is
    monkeypatched to return replayed plane data directly.  Only the post-run
    V/I integration and de-embedding assembly runs under x64.

    x64 is scoped via jax.experimental.enable_x64 context manager — does NOT
    leak to other test modules in the same pytest session.
    """
    acc_data, freqs_replay = _load_replay_accumulators()
    golden_f64 = np.load(REPLAY_GOLDEN_F64_PATH)  # (2, 2, n_freqs), complex128

    s_jnp_f64 = _run_assembly_with_replay(acc_data, freqs_replay, use_x64=True)

    print("\n[test_replay_float64_equivalence] per-frequency S overlay")
    print(f"{'freq_idx':>8}  {'max|S_jnp-S_numpy|':>20}")
    for fi in range(s_jnp_f64.shape[-1]):
        dev_fi = float(np.max(np.abs(s_jnp_f64[:, :, fi] - golden_f64[:, :, fi])))
        jv = s_jnp_f64[:, :, fi]
        nv = golden_f64[:, :, fi]
        print(f"  f[{fi:02d}]  dev={dev_fi:.3e}")
        print(f"         jnp  S00={jv[0,0].real:+.10e}{jv[0,0].imag:+.10e}j  "
              f"S10={jv[1,0].real:+.10e}{jv[1,0].imag:+.10e}j")
        print(f"         npy  S00={nv[0,0].real:+.10e}{nv[0,0].imag:+.10e}j  "
              f"S10={nv[1,0].real:+.10e}{nv[1,0].imag:+.10e}j")

    max_abs_dev = float(np.max(np.abs(s_jnp_f64 - golden_f64)))
    print(f"\n[test_replay_float64_equivalence] max_abs_dev = {max_abs_dev:.3e}")
    assert max_abs_dev < 1e-5, (
        f"jnp-x64 assembly differs from numpy-f64 golden by {max_abs_dev:.3e} "
        f"(threshold 1e-5). Structural divergence beyond float-point associativity."
    )
    np.testing.assert_allclose(s_jnp_f64, golden_f64, rtol=1e-5, atol=1e-5)
    print("[test_replay_float64_equivalence] PASS")


# ---------------------------------------------------------------------------
# Test B: float32 deployment delta documented and bounded (FAST)
# ---------------------------------------------------------------------------

def test_float32_deployment_delta_bounded():
    """Document and gate the production float32 vs float64 assembly delta.

    The production jnp assembly runs in float32 (no global x64).  The
    independent numpy golden runs in float64 (complex128).  The delta is
    physically negligible — MSL Z0 staircase error at DX=80µm is >5%.

    x64 is scoped via context manager; does not leak to other modules.
    """
    acc_data, freqs_replay = _load_replay_accumulators()

    s_f64 = _run_assembly_with_replay(acc_data, freqs_replay, use_x64=True)
    s_f32 = _run_assembly_with_replay(acc_data, freqs_replay, use_x64=False)

    delta = float(np.max(np.abs(s_f64 - s_f32)))
    print(f"\n[test_float32_deployment_delta_bounded] "
          f"f32-vs-f64 max_abs_dev = {delta:.3e}")
    print("  (Production float32 delta vs float64 structural result.)")
    print("  MSL Z0 staircase physics error at DX=80µm is >5% — delta is negligible.")

    assert delta < 1e-3, (
        f"f32-vs-f64 deployment delta {delta:.3e} exceeds 1e-3. "
        f"Unexpected precision regression."
    )
    print("[test_float32_deployment_delta_bounded] PASS")


# ---------------------------------------------------------------------------
# Test C: AD smoke test (FAST)
# ---------------------------------------------------------------------------

def _synthetic_v_n(alpha: jnp.ndarray, gamma: jnp.ndarray,
                    n_probes: int = 5) -> list:
    """Synthetic voltage probes: V_n = alpha * q^n + gamma * q^(-n)."""
    q = jnp.asarray(0.82 - 0.25j, dtype=jnp.complex64)
    return [alpha * q**n + gamma / q**n for n in range(n_probes)]


def _fake_run_for_theta(theta: jnp.ndarray, n_probes: int = 5):
    """Return a monkeypatched sim.run that injects synthetic phasors.

    Generates n_probes Ez planes (ez0..ez{n-1}) plus hy and hz planes per
    port per run.  The AD test differentiates through the V·I assembly.
    """
    import re
    plane_name_re = re.compile(
        r"_msl_run(?P<run>\d+)_p(?P<port>\d+)_(?P<kind>ez(?P<ez>\d+)|hy|hz)"
    )

    def fake_run(self, *, n_steps=None, num_periods=1.0, compute_s_params=False):
        del n_steps, num_periods, compute_s_params
        grid = self._build_grid()
        planes = {}
        ones = jnp.ones((1, grid.ny, grid.nz), dtype=jnp.complex64)
        # Linear z/y ramps for the Hy/Hz planes (issue #515 root cause).
        # msl_loop_current's closed Ampere loop is
        #   I = (Hy[bottom] - Hy[top])*dy_sum + (Hz[right] - Hz[left])*dz_sum
        # A spatially UNIFORM Hy/Hz plane (the old ``ones * amp``) makes the
        # opposing legs cancel EXACTLY, so I ~ 0 regardless of theta. With
        # I ~ 0, every a=(V+Z0*I)/2 and b=(V-Z0*I)/2 collapses to a~b~V/2,
        # so the multi-drive S=B*A^-1 solve returns ~Identity independent of
        # V (and therefore of theta) -- empirically confirmed: the old
        # fixture read S ~ [[1,~1e-9],[~1e-9,1]] at every theta in [0.5,0.9].
        # A non-uniform ramp gives Hy/Hz a genuine difference between the
        # loop's opposing legs, so I is non-zero and the V,I -> (a,b)
        # decomposition is no longer degenerate.
        z_ramp = (0.5 + jnp.arange(grid.nz, dtype=jnp.float32) / grid.nz)[None, None, :]
        y_ramp = (0.5 + jnp.arange(grid.ny, dtype=jnp.float32) / grid.ny)[None, :, None]
        for entry in self._dft_planes:
            match = plane_name_re.fullmatch(entry.name)
            assert match is not None, f"Unexpected probe name: {entry.name!r}"
            run_idx = int(match.group("run"))
            port_idx = int(match.group("port"))
            is_driven_port = port_idx == run_idx
            kind = match.group("kind")

            if is_driven_port:
                alpha = jnp.asarray(1.0 + 0.15j, dtype=jnp.complex64)
                gamma = jnp.asarray(0.08 - 0.03j, dtype=jnp.complex64)
            elif run_idx == 0 and port_idx == 1:
                alpha = theta * jnp.asarray(0.42 + 0.07j, dtype=jnp.complex64)
                gamma = jnp.asarray(0.02 + 0.01j, dtype=jnp.complex64)
            else:
                alpha = jnp.asarray(0.35 - 0.04j, dtype=jnp.complex64)
                gamma = jnp.asarray(0.01 - 0.02j, dtype=jnp.complex64)

            if kind.startswith("ez"):
                ez_idx = int(match.group("ez"))
                vs = _synthetic_v_n(alpha, gamma, n_probes=n_probes)
                field = ones * vs[ez_idx]
            elif kind == "hy":
                amp = jnp.asarray(0.018 + 0.004j, dtype=jnp.complex64)
                field = ones * amp * z_ramp
            else:  # hz
                amp = jnp.asarray(0.005 + 0.001j, dtype=jnp.complex64)
                field = ones * amp * y_ramp

            planes[entry.name] = DFTPlaneProbe(
                accumulator=field,
                freqs=entry.freqs,
                component=entry.component,
                axis=0,
                index=0,
                total_steps=1,
                window="rect",
                window_alpha=0.25,
            )
        return SimpleNamespace(dft_planes=planes)

    return fake_run


def test_compute_msl_s_matrix_ad_smoke_has_finite_gradient():
    """AD smoke: jax.grad through V·I assembly must produce finite non-NaN gradient.

    NOTE (M1, 2026-05-24): this test uses SYNTHETIC accumulators (``_fake_run``),
    so the honesty-guard fires a huge-Z0 warning (e.g. ~1e26 ohm) — that is
    EXPECTED for non-physical synthetic data and is NOT a regression. This test
    gates only that the assembly is differentiable; it deliberately does NOT
    assert physical S/Z0 (the data isn't physical). The real physics-sanity gate
    (forward S in [0, ~1.2] + finite-difference cross-check) belongs on the REAL
    end-to-end path and is a required acceptance criterion of G-AD-WIRE
    (docs/research_notes/2026-05-24_next_goals_and_miss_audit.md). Real-path
    passivity is already gated by test_msl_thru_line_passive_gate.

    REBUILT (issue #515, 2026-08-04). Two defects, found and fixed together:

    1. **The objective was structurally flat on current main.** The old
       objective was ``Re(S21)`` (``jnp.real(result.S[1, 0, 0])``). Measured
       on main post-PR #516 (the multi-drive ``S = B·A⁻¹`` solve): grad =
       0.000000e+00, and the forward value at theta = 0.6/0.7/0.8 was
       -2.85e-08 / 0.0 / -2.85e-08 — dead, not merely small. The test's
       ``isfinite``/``not isnan`` assertions cannot fail on a severed tape,
       so it passed on a dead value. Fixed by switching to the SAME shared
       objective the #530 tight gate uses (``msl_band_mean_s21_sq`` in
       ``tests/_msl_ad_objective.py``, band-mean ``|S21|**2``) instead of a
       second hand-written reduction.

    2. **Switching the objective alone was not enough — the FIXTURE was also
       degenerate**, and root-causing that is what this note records.
       ``_fake_run_for_theta`` used to synthesize Hy/Hz DFT-plane data as a
       spatially UNIFORM field (``ones * amp``). ``msl_loop_current``'s
       closed Ampère loop is
       ``I = (Hy[bottom] − Hy[top])·Σdy + (Hz[right] − Hz[left])·Σdz`` — a
       uniform Hy/Hz plane makes the opposing legs cancel EXACTLY, so the
       synthetic trace current I ≈ 0 at every port, every run, every theta.
       With I ≈ 0, every wave pair ``a = (V + Z0·I)/2``, ``b = (V − Z0·I)/2``
       collapses to ``a ≈ b ≈ V/2``, and the multi-drive ``S = B·A⁻¹`` solve
       then returns ``S ≈ Identity`` REGARDLESS of V — and therefore
       regardless of theta or which objective reads S21. Measured directly:
       the old fixture gave ``S ≈ [[1, ~1e-9], [~1e-9, 1]]`` at every
       theta ∈ [0.5, 0.9] — band-mean ``|S21|**2`` under that fixture reads
       ~1e-17 (float32 noise), not merely small. This was NOT a defect the
       #530 objective swap could fix by itself; it was a second, independent
       fixture defect that happened to be invisible under the old ``Re(S21)``
       objective too. Fixed by giving Hy a linear z-ramp and Hz a linear
       y-ramp (see the ramps built in ``_fake_run_for_theta``) so the loop's
       opposing legs no longer cancel and I is genuinely non-zero — a
       physically-motivated shape (a real trace current does not thread a
       spatially uniform H field either), not a numerology patch.

    Measured after both fixes (this test, CPU float32, theta0=0.7):
    ``grad = -4.681417e-03``, ``loss = 6.008485e-03``. A quick central-FD
    cross-check at h=0.01 on this SAME synthetic fixture (informal, not
    gated — this is a plumbing smoke, not an accuracy gate) reads
    ``g_fd = -2.842303e-03``, agreeing in sign and order of magnitude. The
    floor below (1e-4) sits ~47x under the measured magnitude — comfortable
    headroom for CPU/GPU or JAX-version float32 noise while still rejecting
    a severed tape (which reads exactly 0.0, not a small nonzero number).

    FALSIFIER (PR body records the run): reproducing the OLD uniform-field
    fixture with the NEW shared objective still gives grad ≈ 0
    (|grad| < 1e-4), confirming this floor rejects the exact severed
    construction issue #515 was filed against.
    """
    freqs = jnp.asarray([1.0e9], dtype=jnp.float32)

    # A strictly-positive floor, not merely isfinite/not-NaN (the #515
    # defect: those assertions cannot fail on a severed tape, so the old
    # test passed on a dead grad = 0.0). Derived from the measured
    # -4.681417e-03 with ~47x headroom below its magnitude.
    _GRAD_FLOOR = 1.0e-4

    def objective(theta):
        sim = _build_thru_line_sim()
        sim.run = MethodType(_fake_run_for_theta(theta), sim)
        result = sim.compute_msl_s_matrix(
            n_steps=1,
            freqs=freqs,
            num_periods=1.0,
        )
        return msl_band_mean_s21_sq(result.S)

    grad = jax.grad(objective)(jnp.asarray(0.7, dtype=jnp.float32))
    print(f"\n[AD smoke] grad = {float(grad):.6e}")
    assert bool(jnp.isfinite(grad)), f"Gradient is not finite: {grad}"
    assert not bool(jnp.isnan(grad)), f"Gradient is NaN: {grad}"
    assert abs(float(grad)) > _GRAD_FLOOR, (
        f"[AD smoke] gradient is effectively zero ({float(grad):.3e}, floor "
        f"{_GRAD_FLOOR:.0e}): the tape may be severed again. isfinite/not-NaN "
        "alone cannot catch this — see issue #515."
    )
    print("[test_compute_msl_s_matrix_ad_smoke_has_finite_gradient] PASS")


# ---------------------------------------------------------------------------
# Test D: slow end-to-end vs genuine pre-change S1 golden
# ---------------------------------------------------------------------------

@pytest.mark.slow
def test_compute_msl_s_matrix_end_to_end_matches_historical_base():
    """End-to-end drift lock: full FDTD + assembly vs the committed golden.

    RE-BASELINED 2026-07-30 (PR #516; decision required by that PR's review,
    finding F4, and recorded here + in issue #509). The original golden was a
    pre-jnp-conversion S1 capture whose contract said it "must NOT be
    regenerated from post-change code" — that contract existed to prove a pure
    REFACTOR was precision-only. Two deliberate algorithm changes then made
    the premise unsatisfiable:

      * #468 made ``enforce_passivity=True`` the default (projection moves S
        by up to 5.2e-2 on this fixture — the first red, 2026-07-27, #509);
      * #511/#507 (PR #516) corrected the modal-voltage span and replaced the
        single-ratio assembly with the multi-drive solve (measured deviation
        vs the old golden: 1.07e-1 as shipped (an intermediate PR state
        measured 2.93e-1 before review finding F2 re-anchored the V span) —
        not f32 rounding, and not
        meant to be).

    A frozen old-algorithm capture cannot survive deliberate algorithm
    changes, and keeping it red hides real regressions behind an expected
    one. The golden is therefore now a capture of the CURRENT pipeline
    (fixture, freqs, ``num_periods=12``, default ``enforce_passivity`` —
    exactly this test's invocation; capture script recorded in PR #516), and
    this test's job is narrower and honest: catch UNINTENDED cross-version
    drift. Any future red here is a real change to the MSL S-matrix and must
    be either root-caused or re-baselined with its reason written in this
    docstring — never silently.

    Structural correctness (jnp == numpy on the SAME algorithm) is proven
    separately by test_replay_float64_equivalence against the replay golden.
    Tolerance stays rtol=5e-3/atol=2e-3: it must absorb cross-machine float
    noise on a CI runner (the PR #119 lesson: tolerances, not bit-equality),
    and every deliberate algorithm change to date has exceeded it by >10x, so
    the lock still discriminates.
    """
    golden = np.load(E2E_GOLDEN_PATH)
    sim = _build_thru_line_sim()
    freqs = jnp.linspace(F_MAX / 10, F_MAX, golden.shape[-1], dtype=jnp.float32)

    result = sim.compute_msl_s_matrix(freqs=freqs, num_periods=12)
    s_actual = np.asarray(result.S).astype(np.complex128)

    print("\n[WI-1 MSL end-to-end full S trace]")
    for idx, freq in enumerate(np.asarray(result.freqs)):
        vals = s_actual[:, :, idx]
        print(
            f"f[{idx:02d}]={freq:.9e} "
            f"S00={vals[0, 0].real:+.12e}{vals[0, 0].imag:+.12e}j "
            f"S01={vals[0, 1].real:+.12e}{vals[0, 1].imag:+.12e}j "
            f"S10={vals[1, 0].real:+.12e}{vals[1, 0].imag:+.12e}j "
            f"S11={vals[1, 1].real:+.12e}{vals[1, 1].imag:+.12e}j"
        )

    max_dev = float(np.max(np.abs(s_actual - golden)))
    print(f"[WI-1 MSL] max_abs_dev(new-f32-jnp vs pre-change S1 golden) = {max_dev:.3e}")
    # f32 production delta for the S1 V·I de-embedding; precision-only (see
    # test_replay_float64_equivalence for the exact f64 structural proof).
    np.testing.assert_allclose(s_actual, golden, rtol=5e-3, atol=2e-3)
