"""P-polarized xy Bloch launch: Yee matching, leakage and refusals (#1422)."""
import hashlib

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from tests._x64_compat import enable_x64

from rfx import Simulation
from rfx.core.yee import EPS_0, MU_0, init_materials, init_state, update_e, update_h
from rfx.sources import tfsf_2d as aux
from rfx.sources.tfsf import init_tfsf, tfsf_boundary_flags
from tests._absorber_witness import tfsf_oblique_auxiliary_reflection


def propagate(polarization, angle=30, direction="+x", module=aux, steps=400):
    """Small empty Bloch domain; retain all six main and all auxiliary fields."""
    shape, dx, dt = (64, 3, 3), 1e-3, 1.5e-12
    cfg, state = module.init_tfsf_2d(
        shape[0], shape[1], dx, dt, nz=shape[2], cpml_layers=8,
        f0=10e9, bandwidth=.2, theta_deg=angle,
        polarization=polarization, direction=direction)
    fields = init_state(shape, field_dtype=jnp.complex64)
    materials = init_materials(shape)
    periodic, _ = tfsf_boundary_flags(cfg)
    bloch = module.bloch_phase_tuple(cfg, dx)

    def step(carry, t):
        fields, state = carry
        fields = update_h(fields, materials, dt, dx, periodic=periodic, bloch=bloch)
        fields = module.apply_tfsf_2d_h(fields, cfg, state, dx, dt)
        state = module.update_tfsf_2d_h(cfg, state, dx, dt)
        fields = update_e(fields, materials, dt, dx, periodic=periodic, bloch=bloch)
        fields = module.apply_tfsf_2d_e(fields, cfg, state, dx, dt)
        state = module.update_tfsf_2d_e(cfg, state, dx, dt, t)
        return (fields, state), None

    fields, state = jax.lax.scan(step, (fields, state), jnp.arange(steps) * dt)[0]
    return cfg, fields, state


@pytest.mark.parametrize("polarization", ["ez", "ey"])
def test_te_main_byte_identity(polarization):
    # CPU float32, main 59a37c8b62f5b0698d1262776ab1381968d20c60.
    # Generated by executing that revision's unmodified tfsf_2d.py through
    # propagate(), including both main-grid corrections and all aux carries.
    expected = {"ez": "f2af733244444819b3f988913ad4d3b302838f2c58d176c498373a83deb8bb41",
                "ey": "36be8cbc010ccc9ed8ae2b39eba9b619e14bc6512d27317074e00fde39dfd50b"}
    with jax.default_device(jax.devices("cpu")[0]), enable_x64(False):
        _, fields, state = propagate(polarization)
    digest = hashlib.sha256(b"".join(np.asarray(v).tobytes() for v in (*fields, *state))).hexdigest()
    assert digest == expected[polarization]


@pytest.mark.parametrize("angle", [30, -30, 75])
@pytest.mark.parametrize("direction", ["+x", "-x"])
def test_p_empty_domain_leakage(angle, direction):
    cfg, fields, state = propagate("p", angle, direction)
    energy = sum(np.abs(np.asarray(v))**2 for v in fields[:3]) * EPS_0
    energy += sum(np.abs(np.asarray(v))**2 for v in fields[3:6]) * MU_0
    total = energy[cfg.x_lo:cfg.x_hi + 1].sum()
    scattered = energy[:cfg.x_lo - 2].sum() + energy[cfg.x_hi + 3:].sum()
    print(f"P {angle=} {direction=}: SF/TF={scattered / total:.9g}")
    assert total > 1e-14
    assert scattered / total < .01  # same 1% bar as existing oblique tests
    for component in (fields.ex, fields.ey, fields.hz):
        assert np.max(np.abs(component)) > 1e-6
    for component in (fields.ez, fields.hx, fields.hy):
        assert np.count_nonzero(component) == 0
    # Check field ownership and staggering against the independent 3D curls.
    ix = slice(cfg.x_lo + 2, cfg.x_hi - 1)
    ia = slice(cfg.i0_x + 2, cfg.i0_x + cfg.x_hi - cfg.x_lo - 1)
    for main, incident in ((fields.ey, state.ez_2d), (fields.ex, state.hx_2d),
                           (fields.hz, state.hy_2d)):
        np.testing.assert_allclose(np.asarray(main[ix, :, 0]), np.asarray(incident[ia]),
                                   atol=2e-6, rtol=2e-4)


@pytest.mark.parametrize("direction", ["+x", "-x"])
@pytest.mark.parametrize("depth,target", [(30, 1e-15), (200, 1e-28)])
def test_p_auxiliary_absorber(direction, depth, target):
    reflected_db, residual = tfsf_oblique_auxiliary_reflection(
        depth, polarization="p", direction=direction, r_asymptotic=target)
    print(f"P {direction}: max return={np.max(10**(reflected_db / 20)):.9g}, residual={residual:.9g}")
    assert residual < 1e-2
    # Same fixed witness rig/bar as test_tfsf_half_cell_reflection.py (30 deg).
    from tests._gate_policy import gate_from_envelope
    # The shipped 200-layer / 1e-28 profile reads <=1.74e-6 on both faces.
    # Pin that envelope separately; no absorber coefficient is adjusted.
    measured, quantum = (7.48e-5, 1e6) if depth == 30 else (1.74e-6, 1e7)
    assert np.all(10**(reflected_db / 20) < gate_from_envelope(measured, quantum=quantum))


def build_sim(**kwargs):
    return Simulation(freq_max=30e9, domain=(.06, .006, .006), dx=.001,
                      cpml_layers=4, **kwargs)


@pytest.mark.parametrize("options,match", [
    ({"method": "methodB"}, "bloch"),
    ({"closed_box": True}, "closed_box"),
    ({"angle_deg": 0}, "oblique"),
    ({"angle_deg": .001}, "oblique"),
    ({"waveform": "continuous_wave"}, "normal incidence"),
])
@pytest.mark.parametrize("entry", ["api", "initializer"])
def test_p_source_refusals(options, match, entry):
    kw = dict(polarization="p", angle_deg=30)
    kw.update(options)
    with pytest.raises((ValueError, NotImplementedError), match=match):
        if entry == "api":
            build_sim().add_tfsf_source(**kw)
        else:
            init_tfsf(64, .001, 1.5e-12, ny=3, nz=3, **kw)


@pytest.mark.parametrize("entry", ["run", "forward"])
@pytest.mark.parametrize("lane", ["nonuniform", "distributed", "subgrid"])
def test_p_lane_refusals(entry, lane):
    sim = build_sim(**({"dz_profile": np.full(6, .001)} if lane == "nonuniform" else {}))
    sim.add_tfsf_source(polarization="p", angle_deg=30)
    if lane == "subgrid":
        sim.add_refinement((.002, .004), ratio=2)
    kw = {"distributed": True} if entry == "forward" else {"devices": [0, 1]}
    with pytest.raises(NotImplementedError, match="polarization='p'.*uniform"):
        getattr(sim, entry)(n_steps=2, skip_preflight=True,
                            **(kw if lane == "distributed" else {}))


@pytest.mark.parametrize("entry", ["run", "forward"])
@pytest.mark.parametrize("axis,side", [(a, s) for a in "yz" for s in ("lo", "hi")])
def test_p_magnetic_transverse_refusal(entry, axis, side):
    from rfx.boundaries.spec import Boundary
    faces = {"x": "cpml", "y": "cpml", "z": "cpml"}
    faces[axis] = Boundary(**{side: "pmc", "hi" if side == "lo" else "lo": "cpml"})
    sim = build_sim(boundary=faces)
    sim.add_tfsf_source(polarization="p", angle_deg=30)
    with pytest.raises(NotImplementedError, match="magnetic transverse"):
        getattr(sim, entry)(n_steps=2, skip_preflight=True)


@pytest.mark.parametrize("entry", ["run", "forward"])
def test_p_api_launch(entry):
    sim = build_sim()
    sim.add_tfsf_source(polarization="p", angle_deg=30, f0=10e9, bandwidth=.2)
    for component in ("ex", "ey", "hz"):
        sim.add_probe((.03, .003, .003), component=component)
    result = getattr(sim, entry)(n_steps=300, skip_preflight=True)
    assert np.all(np.max(np.abs(result.time_series), axis=0) > 1e-6)
    # run reconstructs physical fields; forward retains the Bloch envelope.
    assert result.time_series.dtype == (jnp.float32 if entry == "run" else jnp.complex64)


@pytest.mark.parametrize("feature", ["flux", "decay"])
def test_p_existing_bloch_refusals(feature):
    sim = build_sim()
    sim.add_tfsf_source(polarization="p", angle_deg=30)
    if feature == "flux":
        sim.add_flux_monitor(axis="x", coordinate=.03, freqs=[15e9], name="flux")
        with pytest.raises(NotImplementedError, match="transform-aware"):
            sim.run(n_steps=2, skip_preflight=True)
    else:
        with pytest.raises(NotImplementedError, match="until_decay"):
            sim.run(until_decay=1e-4, decay_monitor_component="ey",
                    decay_monitor_position=(.03, .003, .003), skip_preflight=True)


@pytest.mark.parametrize("mode", ["2d_tmz", "2d_tez"])
def test_p_reduced_mode_refusal(mode):
    with pytest.raises(NotImplementedError, match="mode='3d'"):
        build_sim(mode=mode).add_tfsf_source(polarization="p", angle_deg=30)


@pytest.mark.parametrize("runner", ["nonuniform", "distributed", "subgridded"])
def test_p_direct_runner_refusals(runner):
    sim = build_sim()
    sim.add_tfsf_source(polarization="p", angle_deg=30)
    with pytest.raises(NotImplementedError, match="polarization='p'.*not supported"):
        if runner == "nonuniform":
            from rfx.runners.nonuniform import run_nonuniform_path
            run_nonuniform_path(sim, n_steps=2)
        elif runner == "distributed":
            from rfx.runners.distributed_v2 import run_distributed
            run_distributed(sim, n_steps=2)
        else:
            from rfx.runners.subgridded import run_subgridded_path
            run_subgridded_path(sim, None, None, None, 2)
