#!/usr/bin/env python3
"""External openEMS referee for rfx issue #490 lane 2 (MSL de-embedded phase).

SCOPE FENCE (matches ``validation/research/coax_two_port/
openems_coax_two_port_referee.py`` and ``scripts/diagnostics/
openems_thru_referee/thru_openems.py`` precedent): this is a
COMPARATOR-LEG referee. It builds and runs an INDEPENDENT openEMS model
and reports its own S-parameters; it does NOT run any rfx simulation
and does NOT import rfx. Stage B reads ONE committed, rfx-produced JSON
data file (``tests/fixtures/msl_phase_referee/msl_thru_rfx_dx50.json``,
regenerated by ``scripts/diagnostics/build_msl_thru_phase_dx50um_
reference.py`` -- a plain data dependency, not a Python import of rfx)
so the two solvers' numbers can be compared inside one artifact. This
script brackets; it does not judge rfx's own numbers.

DECLARED QUESTION (issue #490 lane 2): is rfx's MSL de-embedded phase
(``compute_msl_s_matrix``'s ``angle(S21)``) "not gated" because of an
unresolved e^{+-j*omega*t} TIME-CONVENTION mismatch against an external
solver, or because of an unresolved REFERENCE-PLANE mismatch? The
CONVENTION NOTE section below answers this from BOTH tools' own source
(not by running FDTD): the two DFT kernels are IDENTICAL, so it is a
reference-plane question, resolved here by placing openEMS's own
``MeasPlaneShift`` measurement stencil directly at rfx's own probe-0
plane. ``CalcPort(ref_plane_shift=...)`` referral (the SAME mechanism
the #489 coax referee validated end-to-end) is ALSO called on every
run, but on THIS fixture it is a MEASURED no-op (effective shift 0.0 --
see CONVENTION NOTE part (c)'s "NEW-1 FINDING" and the artifact's own
``port_info`` block) because the placement above already lands exactly
on-grid; the referral machinery is exercised, not skipped, and remains
the mechanism a future off-grid fixture would need it to actually do
work.

============================================================================
DO-NOT-REPEAT (R1/R2 class -- read before choosing a mesh size)
============================================================================
This fixture's substrate is RO4350B (eps_r=3.66, h_sub=254um) -- the
SAME substrate ``scripts/diagnostics/build_msl_notch_openems_
comparison.py`` already used for a matched-geometry rfx-vs-openEMS
comparison, and that script's own docstring records a directly
applicable finding: "at dx=80 um the substrate is only 3.175 cells
(the 'mixed-cell danger zone' rfx preflight warns about), where the
openEMS MSL-port extraction is NON-PHYSICAL (|S11|^2+|S21|^2 up to
8.9, passivity grossly violated). dx=50 um gives 5.08 substrate cells
where BOTH solvers are passive, so it is the only valid matched-mesh
comparison." ``tests/test_msl_port_integration.py``'s own committed
thru-line gate happens to use dx=80um (3.175 substrate cells) for rfx
alone -- reusing THAT dx here for a cross-solver comparison would
repeat the exact recorded openEMS failure. This script's Stage B
therefore uses dx=50um (254/50 = 5.08 substrate cells, identical
fraction to the already-validated notch comparison) on the SAME
substrate, and rfx's own side (``build_msl_thru_phase_dx50um_
reference.py``) was run at dx=50um for the SAME reason -- neither side
reuses the committed dx=80um fixture.

============================================================================
PRECEDENT TICK-LIST (2026-08-03 addendum to ``external_solver_
comparator.md``: quote precedent headers IN FULL, tick every recorded
failure against this design BEFORE writing code)
============================================================================
``scripts/diagnostics/openems_thru_referee/thru_openems.py`` (the MSL
wire-port precedent, 0.7% |S| agreement, #321 era) -- its ENTIRE header
was read (not summarized) before this script was written. Ticks:
  1. "Do NOT pass ref_impedance as a scalar float -- that triggers a
     bug in the base Port.CalcPort when Z_ref is array-valued." This
     script never passes ``ref_impedance`` to ``CalcPort`` on EITHER
     stage -- ``MSLPort``/``CoaxialPort``-family ports self-measure
     ``Z_ref`` in ``ReadUIData``, so the parameter is simply omitted
     throughout, structurally avoiding the bug rather than tiptoeing
     around it.
  2. "each port's prop_dir = sign(stop[axis]-start[axis]) points INTO
     the line" -- replicated exactly for both Stage B ports (mirror-
     symmetric: port0 points +x into the line from the left, port1
     points -x into the line from the right).
  3. "s21 = port1.uf_ref / port0.uf_inc" (port1's uf_ref channel
     carries the +x-going transmitted wave under this mirror-symmetric
     port layout) -- reused verbatim; Stage B never needs the coax
     lane's reverse-drive S12/S22 bookkeeping because it is
     single-drive only (matching thru_openems.py's own single-drive
     scope, and issue #490 lane 2's own stated scope: "extracting
     angle(S21)(f) (and angle(S11) if cheap)").
  4. Port-model caveat: thru_openems.py compared rfx's 1-cell wire
     port against openEMS's span ``MSLPort`` (different port classes
     by construction). THIS script compares rfx's OWN ``add_msl_port``
     (also a distributed span port, ``rfx/sources/msl_port.py``)
     against openEMS's ``MSLPort`` -- a TIGHTER match than the
     precedent's own comparison, not a looser one.

``matlab/examples/waveguide/Coax.m`` via ``validation/research/
coax_two_port/openems_coax_two_port_referee.py`` (#489 stage 3, 5
review rounds, PRs #540/#546/#547/#548) -- relevant lessons ticked:
  5. "MUR-on-dielectric is unstable (exponential energy blow-up)." This
     script never uses MUR anywhere -- Stage A uses the MSL tutorial's
     own PML_8/MUR mix VERBATIM (MUR only on the Y faces, which carry
     no dielectric interface in that geometry -- the tutorial's own
     substrate spans the full Y extent, so Y-face MUR sees a *uniform*
     dielectric cross-section, not the mixed air/substrate transition
     that broke the coax lane), and Stage B uses PML_8 on every
     absorbing face (matching rfx's own ``BoundarySpec(x='cpml',
     y='cpml', z=Boundary(hi='cpml'))`` exactly) -- MUR is not used in
     Stage B at all.
  6. Reference-plane/measurement-plane ORDERING bug (M1 of the COAX
     lane, run-1's |S11|=280.7 root cause -- do not confuse with THIS
     file's own M1, the phase-gate-budget fix): the coax lane's ports
     spanned the WHOLE domain edge-to-edge, through the PML, so
     FeedShift/MeasPlaneShift had to be carefully placed relative to the
     PML edge. THIS script's Stage B ports are SHORT (6 cells / 300um,
     matching thru_openems.py's own ``PORT_W`` pattern for the
     excitation+Feed_R footprint -- m5 fix, module docstring DELTA LIST
     item 5) and sit deep inside the clear region, far from any PML --
     the entire ordering-bug CLASS is structurally avoided by the
     port-topology choice, not merely unencountered. ``FeedShift`` is
     left at ``MSLPort``'s own class default (0, at ``start`` -- matching
     thru_openems.py); ``MeasPlaneShift`` is now set EXPLICITLY (m5 fix,
     2026-08-04 review -- NOT left at the class default, which at this
     Stage's finer dx put the measurement stencil only 150um/3 cells
     from the excitation, near-field contaminated) to a target that is
     STILL far from any PML (2.5mm from ``start``, vs a 400um-deep PML) --
     the ordering-bug class remains structurally avoided; only the
     SOURCE of the value changed (explicit target, not a class default).
  7. Direction-signed current probe / forward-vs-reverse-drive S-matrix
     bookkeeping (``_extract_two_port_s``, 3 review rounds to get
     right): N/A here by design -- Stage B is single-drive, so there is
     no reverse-drive case to get wrong.
  8. Scale-free excitation guard (no absolute floor -- issue #465/PR
     #473, reaffirmed PR #547 after two floor-tuning false starts):
     replicated verbatim in ``_check_excitation_and_trace`` below.
  9. complex128-in-JSON serialization crash (B2, PR #546): avoided from
     the start -- every complex array below is converted to ``[re,
     im]`` pairs before ``json.dump``, never passed raw.
  10. TRACKED log-path contract for a FILLED reproduce-gate record
      (PR #548, correcting PR #548's own first fill): applied directly
      in ``REPRODUCE_GATE_RECORD`` and its header test.
  11. Exit-code split 0/1/2/3 (0=self-checks passed, 1=physics/self-
      check gate failed, 2=openEMS missing, 3=internal config/layout
      bug) and forensics-on-failure (partial per-bin data attached to
      a raised ``RuntimeError`` so a failing run still leaves numbers
      to inspect): both applied directly, matching the coax lane's own
      convention (``docs/agent-memory/task_recipes/vessl_external_
      referee_lane.md``).

============================================================================
CONVENTION NOTE (the actual deliverable -- read this before the code)
============================================================================
Issue #490's premise is that "MSL/wire phase is not gated because the
reference conventions differ" (``docs/guides/sparameter_support_
matrix.md``, Wire port section) is a CONVENTION problem, not a physics
one, and asks for it to be RESOLVED, not masked. Resolving it requires
knowing, independently, on EACH side: (a) the time-domain phasor
convention (e^{+j*omega*t} vs e^{-j*omega*t}), (b) where the reported
phase is referenced in space, and (c) the transform between them.

(a) TIME CONVENTION -- VERIFIED IDENTICAL, not assumed.
    rfx's DFT accumulator (``rfx/probes/probes.py``,
    ``update_dft_plane_probe``):
        phase = jnp.exp(-1j * 2.0 * jnp.pi * probe.freqs * t)
    openEMS's DFT (``python/openEMS/utilities.py``, ``DFT_time2freq``,
    fetched 2026-08-04 via ``gh api repos/thliebig/openEMS/contents/
    python/openEMS/utilities.py``):
        f_val[n_f] = np.sum(val * np.exp(-1j*2*np.pi*freq[n_f]*t))
    Both tools integrate a REAL time-domain signal against the SAME
    kernel, exp(-j*omega*t) -- the standard forward-Fourier convention,
    consistent with reconstructing the time-domain field as
    Re[X(omega)*exp(+j*omega*t)], i.e. BOTH tools are e^{+j*omega*t}
    (IEEE/engineering) phasors. This is the OPPOSITE of what the cv11
    WR-90 slab-phase precedent might suggest by analogy (Meep/OpenEMS/
    Palace genuinely disagreed by 100+ degrees among THEMSELVES on that
    case, docs/agent-memory/rfx-known-issues.md "cv11 slab-phase
    convention mismatch") -- for THIS solver pair, the two kernels are
    IDENTICAL IN EXPONENT AND SIGN (n7 wording fix: not "byte-identical"
    -- the NORMALIZING factors applied afterward differ: rfx's
    accumulator multiplies by ``dt`` and a window weight per timestep
    inside the loop, while openEMS's ``DFT_time2freq`` multiplies by
    ``t[1]-t[0]`` (dt, 'pulse' signals) THEN returns ``2*f_val`` (an
    extra factor of 2, its own single-sided-spectrum convention) --
    both are REAL POSITIVE scalars, and multiplying a complex phasor by
    a real positive scalar cannot change its ARGUMENT (phase); S11/S21
    are RATIOS (b/a) besides, so any residual overall scalar cancels a
    second time regardless), so e^{+-j*omega*t} is NOT the mismatch
    mechanism here. This finding is new: no prior rfx doc records
    having compared the two tools' DFT kernels directly.

    A second, independent check: rfx's N-probe extractor fits
    ``V_n = alpha*exp(-j*beta*x_n) + gamma*exp(+j*beta*x_n)`` and
    documents ``alpha`` as "the +x-travelling wave" (``rfx/api/
    _sparams.py``, N-probe placement comment) -- exp(-j*beta*x) for a
    forward (+x) wave is exactly what e^{+j*omega*t} predicts
    (E(x,t) = Re[exp(j*(omega*t - beta*x))]). openEMS's own a/b
    (incident/reflected) split, ``Port.CalcPort`` (``python/openEMS/
    ports.py``):
        uf_inc = 0.5*(uf_tot + if_tot*Z_ref)
        uf_ref = uf_tot - uf_inc
    is the SAME textbook telegrapher-equation split rfx's
    ``a_fwd = 0.5*(V + Z0*I)``, ``b_ref = 0.5*(V - Z0*I)``
    (``rfx/api/_sparams.py``, ``compute_msl_s_matrix``) uses --
    identical formula, not merely analogous.

(b) REFERENCE PLANE -- this IS where the two tools differ, and it is
    a pure geometry question, not a sign-convention one.
      rfx: ``compute_msl_s_matrix``'s reported S11/S21 are referenced
      at PROBE 0 of each port -- NOT the feed plane. The code uses
      ``v_per_port[driven][0]`` (probe 0's voltage) directly in
      ``a_fwd_d``/``b_ref_d`` (``rfx/api/_sparams.py``). Probe 0 sits
      ``n_probe_offset`` cells downstream of the port's ``feed_x``
      (``rfx/sources/msl_port.py::msl_probe_x_coords_n``), where
      ``n_probe_offset`` is auto-resolved per issue #478/#469
      (``_resolve_msl_auto_offsets``) from the line geometry -- NOT a
      fixed constant, and NOT the feed plane.
      openEMS: ``MSLPort``'s own default measurement plane
      (``measplane_pos = start + measplane_shift*direction``,
      ``measplane_shift`` defaulting to half the port's own physical
      span) is neither rfx's feed plane nor rfx's probe-0 plane.
      ``CalcPort(ref_plane_shift=...)`` re-references the reported
      wave split to an arbitrary target, expressed as a signed
      distance from the port's own ``start`` along its own
      ``direction`` (``python/openEMS/ports.py``, base
      ``Port.CalcPort``: ``shift = ref_plane_shift - self.
      measplane_shift``, both in that one convention, applied via a
      plain TL phase-rotation BEFORE the a/b split).

(c) THE TRANSFORM applied here: for each Stage B port,
        ref_plane_shift = (target_x - start_x) * direction
    where ``target_x`` is rfx's OWN probe-0 physical x-coordinate (read
    from the committed fixture's ``reference_plane_geometry`` block,
    not re-derived independently -- avoiding a second, possibly-
    drifting copy of ``_resolve_msl_auto_offsets``'s arithmetic) and
    ``start_x`` is this script's own port ``start`` coordinate. Because
    rfx's own domain convention places the user-domain origin (x=0) at
    the START of its non-CPML interior (CPML is padded ADDITIVELY,
    outside [0, LX_clear] -- verified via ``grid.pad_x_lo``/``dx``,
    see ``_reference_plane_geometry`` in ``build_msl_thru_phase_
    dx50um_reference.py``) and this script's own openEMS mesh is built
    with PML consuming bands OUTSIDE [0, LX_clear] rather than from
    within it (see Stage B geometry below), rfx's own physical
    coordinates (feed_x, probe0_x) transfer to this script's openEMS
    geometry with ZERO coordinate shift -- verified by construction
    (``_assert_matches_rfx_fixture``), not assumed. This sidesteps the
    coax lane's pad-relative-vs-nominal-domain arithmetic entirely (the
    coax fixture's CPML consumes the domain differently on each side --
    see that script's DELTA LIST item 5 -- which is what forced its own
    careful ``ref_plane_shift_port{1,2}_mm`` derivation).

    UNWRAPPING: ``np.unwrap(np.angle(S21))`` on the COMMON frequency
    grid (Stage B reads ``freqs_hz`` directly from the committed rfx
    fixture and evaluates openEMS's own ``CalcPort`` at those exact
    frequencies -- no interpolation, so no interpolation-induced phase
    artefact).

    NEW-1 FINDING (review 2026-08-04, the one that matters -- read this
    before citing "resolved via ref_plane_shift referral" as this
    fixture's own evidence): on THIS COMMITTED fixture, the referral is
    an EXACT NO-OP by construction. ``MeasPlaneShift`` (m5 fix) is set to
    the SAME target as ``ref_plane_shift`` (both 2.5mm per port), and
    that target lands EXACTLY on an existing x-mesh line (dx=50um
    divides 2.5mm into 50 whole cells, and Stage B's own x-mesh is
    uniform with no thirds-rule refinement -- see
    ``_predict_measplane_snap``). So openEMS's own mesh-line snap
    (``python/openEMS/ports.py``) leaves ``measplane_shift`` UNCHANGED at
    2.5mm, and ``CalcPort``'s own ``shift = ref_plane_shift -
    measplane_shift`` evaluates to 0.0 -- the TL-phase-rotation this
    referee cites as "the transform" therefore rotates by ZERO on this
    specific run (measured, not merely predicted: ``_build_stage_b``
    cross-checks the REAL openEMS-measured ``measplane_shift`` against
    the pure-arithmetic prediction and records BOTH, plus the resulting
    ``effective_shift_real_port{0,1}_m``, in ``port_info`` -- see
    ``_stage_b_port_placement`` and the artifact's own ``stage_b.
    port_info`` block). What THIS fixture actually validates, then, is
    that placing the MEASUREMENT STENCIL directly at rfx's own probe-0
    plane (via ``MeasPlaneShift``) reproduces the right reference plane
    -- STENCIL PLACEMENT, not CalcPort's own rotation ARITHMETIC. The
    ``ref_plane_shift`` argument is still passed to ``CalcPort`` on every
    run (the code path is exercised, computing and applying a shift of
    0.0 -- not skipped or dead code), and remains the mechanism a
    DIFFERENT fixture would need if its own target plane fell BETWEEN
    two mesh lines (an off-grid target, where ``MeasPlaneShift`` alone
    cannot land exactly on it and the TL rotation would have real work to
    do) -- this fixture's own placement was deliberately chosen (m5) to
    land exactly on-grid, which is what makes its own shift trivial. A
    reviewer should read this referee's result as "reference-plane
    PLACEMENT resolved to rfx's own probe-0, referral machinery
    exercised-as-a-no-op and held in reserve for an off-grid target," not
    as "the CalcPort referral transform independently validated."

WHAT IS GATED vs REPORTED (per issue #490 lane 2's own design brief):
this fixture's substrate is Yee-staircased differently by each
solver's own discretization (rfx: Cartesian voxel raster at dx=50um;
openEMS: its own Cartesian raster, generally NOT cell-for-cell
identical even at the "same" dx because mesh-line placement/smoothing
differs) -- quasi-TEM eps_eff, and therefore beta(f), is expected to
differ SLIGHTLY between the two solvers for a REAL, mesh-dependent
physics reason unrelated to any convention bug (the coax lane's run-3
finding, ~12% beta mismatch traced to PTFE-annulus staircasing, is the
precedent for this being physically real and solver-specific, not a
defect). Gating the RAW cross-solver phase difference would conflate
that physical dispersion difference with the convention-resolution
claim. So:
  GATED (the convention claim, QUALIFIED -- M2/#534 provenance-mismatch
  fix, see below): each solver's OWN de-embedded angle(S21)(f), AFTER
  its OWN reference-plane referral to the shared L12 span, is
  self-consistent with THAT SAME solver's OWN measured beta(f) via the
  textbook angle(S21) ~= -beta(f)*L12 relation.

  QUALIFIER (read before citing this witness as "proof of convention
  correctness" -- the #534 provenance-mismatch discipline: the sentence
  must say what the check ACTUALLY measures, not what it would be nice
  for it to measure): on ANY uniform (non-dispersive within the gate
  band) line, angle(S21) = -beta*(x1-x0) HOLDS IDENTICALLY for ANY
  correctly-identified pair of planes separated by the reported
  distance -- and the two referred planes here are L12 apart BY
  CONSTRUCTION of how ref_plane_shift is derived (module docstring part
  (c)), not an independent fact this witness discovers. So passing this
  check does NOT prove "the reference-plane transform is convention-
  correct" in general -- it proves the referral/shift ARITHMETIC is
  right to WITHIN the gate's own RESOLVING POWER (see "GATE-BUDGET
  DERIVATION" below): an error SMALLER than that budget would not be
  caught, by construction. It is therefore a NECESSARY check with a
  STATED, MEASURED resolving power (the planted-error test in the
  header suite), not a sufficient, general convention-correctness
  proof. What it DOES positively rule out, at the stated resolving
  power: a referral bug of realistic size (this file's own
  ref_plane_shift is 2.5mm per port -- see the resolving-power test's
  own measured ~16-22 deg deviation for that exact size of error).

  REPORTED, not gated: beta_rfx(f), beta_openems(f), and their ratio
  (the physical-dispersion comparison), plus the raw cross-solver
  angle(S21) difference before and after subtracting the
  dispersion-predicted term -- for the reviewer's own judgement, not a
  pass/fail.

GATE-BUDGET DERIVATION (M1 fix -- ``B_PHASE_TOL_DEG``): the 30 deg
value this script originally shipped with admits a plane-position
error of 3.372mm (67% of L12=5mm) at this fixture's own measured beta
-- a single-port referral drop (see the resolving-power test) measured
~16-22 deg PASSED under it. Re-derived from an explicit physical
budget instead of a round number:
  - Base unit: dx=50um (Stage B's own mesh). A +-2-cell (100um)
    reference-plane positional uncertainty per port is the target
    budget (few-cell mesh round-off/snap class, not a referral bug).
  - At this fixture's OWN measured beta over the 3.0-4.5GHz gate band
    (``tests/fixtures/msl_phase_referee/msl_thru_rfx_dx50.json``,
    ``beta_first_port``: 111.65-155.92 rad/m), a FIXED 100um (2-cell)
    plane error maps to 0.640 deg at the gate band's beta_min
    (3.14GHz) up to 0.893 deg at its beta_max (4.38GHz) -- i.e. the
    RANGE here is across the band's own beta variation at ONE fixed
    cell count, not across different cell counts (NEW-2 fix, review
    2026-08-04: the pre-fix wording conflated a 1-cell/2-cell SPAN
    evaluated at fixed beta_max with a beta-range at fixed cell count --
    they read the same on the page but are different quantities).
  - BOTH ports contribute independent plane uncertainty (S21's phase
    depends on both referred planes) -- worst-case linear combination,
    a FIXED 200um (4-cell) total plane error maps to 1.279 deg
    (beta_min) up to 1.787 deg (beta_max) at this fixture's own
    measured beta.
  - Headroom for what this in-band budget does NOT model (the
    ``MeasPlaneShift``-to-mesh-line snap is exact for THIS geometry's
    own integer-cell target -- see m5 below -- but the openEMS side's
    own beta and finite-difference measurement-stencil residual are
    UNMEASURED before a real run) rounds this up to
    ``B_PHASE_TOL_DEG = 3.0`` -- deliberately still ~7-10x tighter than
    the measured single-port-referral-drop error (the resolving-power
    test), so a genuine referral defect reds with wide margin while a
    +-2-to-4-cell mesh-round-off class does not false-fire.
  - RESOLVING-POWER TEST (the #529 pattern -- a gate must be PROVEN to
    discriminate a real defect, not just pass a real run): ``tests/
    test_msl_phase_referee_header.py::
    test_self_consistency_witness_resolving_power_single_port_referral_drop``
    plants a synthetic single-port referral drop (S21 rotated by
    ``exp(+j*beta*ref_shift)`` for ONE port's own 2.5mm ref_plane_shift,
    on the REAL committed rfx fixture's own S21/beta) and asserts the
    3 deg gate REDS it, while the unperturbed fixture (measured
    max_phase_dev_deg=0.121, see "RFX-SIDE SELF-CONSISTENCY" below)
    still passes with ~25x margin. Measured threshold: the planted
    defect reads 15.88-22.21 deg across the gate band (max 22.21 deg at
    4.38GHz) -- comfortably red at gate=3 deg (~7.4x over).
  - GROUP-DELAY GATE HONESTY (part of the M1 fix): ``B_GD_TOL_PS=200``
    is INERT for this specific failure class -- a CONSTANT plane-
    position error contributes an ALMOST-CONSTANT group-delay offset
    (d/domega[-beta(f)*dl] = -dl*dbeta/domega, and dbeta/domega is
    nearly flat for this near-non-dispersive quasi-TEM line), not a
    slope change, so it does not show up strongly in a group-delay
    (derivative) diagnostic. Measured on the real fixture: the SAME
    single-port (2.5mm) referral-drop that produces 16-22 deg of phase
    deviation produces only ~14.13-14.20 ps of group-delay deviation
    (matches the analytic dl*sqrt(eps_eff)/c0 ~= 14.13ps prediction to
    3 sig figs -- ``eps_eff~=2.87`` from this substrate's own
    Hammerstad-Jensen value); a BOTH-ports-dropped scenario (dl=L12=
    5mm) reaches ~28.4 ps -- still far under the 200ps gate. The
    group-delay witness is KEPT because it is NOT inert for a different
    failure class it is well-suited to -- a gross ``np.unwrap`` failure
    (a missed 2*pi branch) or a genuine dispersion-model break (wrong
    eps_r, wrong beta sign, a non-monotonic beta fit) -- but a reviewer
    must not read "group-delay gate passed" as evidence bearing on
    reference-plane/referral correctness; that is the phase gate's job.

============================================================================
STAGE A -- REPRODUCE-GATE: a faithful port of openEMS's own MSL_
NotchFilter.py tutorial
============================================================================
``python/Tutorials/MSL_NotchFilter.py`` (fetched verbatim 2026-08-04 via
``gh api repos/thliebig/openEMS/contents/python/Tutorials/MSL_
NotchFilter.py``; "(c) 2016-2023 Thorsten Liebig", "Tested with python
3.10, openEMS v0.0.35+") builds an open-circuit-stub microstrip notch
filter on RO4350B (eps_r=3.66, h_sub=254um), MSL_width=600um,
MSL_length=50mm (each side), stub_length=12mm, f_max=7GHz, boundary
``['PML_8','PML_8','MUR','MUR','PEC','MUR']``, ``SetGaussExcite(f_max/2,
f_max/2)`` (both center AND corner set to the SAME 3.5GHz -- an
unusual-looking but literal reading, reproduced verbatim rather than
"corrected", the same discipline the coax lane applied to Coax.m's own
f0=fc choice). ``AddMSLPort`` (thirds-rule mesh already built into the
tutorial's own ``third_mesh`` refinement at the trace's Y-edges) with
port[0] ``excite=-1`` (verbatim, not "corrected" to +1) and
``FeedShift=10*resolution``, ``MeasPlaneShift=MSL_length/3`` on BOTH
ports. openEMS(NrTS, EndCriteria) are left at the library's own
defaults (NrTS~=1e9, EndCriteria=1e-5 -- ``python/openEMS/openEMS.pyx``
docstring, fetched 2026-08-04) because the tutorial itself never
overrides them.

DOCUMENTED CHECK (per ``external_solver_comparator.md`` step 2 -- the
tutorial's own documented result, not a number invented for this
script): the tutorial's stub is a quarter-wave open-circuit notch. Its
analytic notch frequency, using the closed form THIS REPO ALREADY
VALIDATES for the identical substrate/trace/stub combination
(``validation/crossval/06b_msl_notch_filter_uniform.py``:
``F_NOTCH_AN = C0 / (4*STUB_LEN*sqrt(EPS_EFF))``, Hammerstad-Jensen
``EPS_EFF``), is independently recomputed here as
``F_NOTCH_AN_HZ`` (a regression-locked constant, see the header test)
and cross-checks to 5 significant figures against this repo's own
recorded "fringing-free analytic 3.69 GHz" (``docs/agent-memory/
rfx-known-issues.md``, cv06b/msl_notch_e4 entries) for the SAME
substrate/stub. That entry ALSO records the direction and rough size of
the expected openEMS-vs-analytic gap on a DIFFERENT (not identical)
line-length/domain geometry: "rfx 3.6273 GHz vs openEMS 3.4286 GHz vs
Palace ~3.631 GHz vs fringing-free analytic 3.69 GHz" (openEMS reads
~7% LOW, more open-end fringing captured). ``STAGE_A_GATE`` below uses
a generous, ONE-SIDED-LOW-BIASED band informed by that precedent
(status PREDICTED until a real run fills the record -- report-first,
gate-second, per the honest-UNRUN pattern this repo uses throughout its
external referees).

============================================================================
STAGE B -- rfx's OWN ``compute_msl_s_matrix`` thru-line fixture, at
DX=50um (matched-mesh; see DO-NOT-REPEAT above)
============================================================================
Geometry: the SAME substrate/trace/line ``tests/test_msl_port_
integration.py`` validates (RO4350B, W_TRACE=600um, L_LINE=10mm,
PORT_MARGIN=2mm), rebuilt at dx=50um by ``scripts/diagnostics/
build_msl_thru_phase_dx50um_reference.py`` and committed as ``tests/
fixtures/msl_phase_referee/msl_thru_rfx_dx50.json``. This script's own
Stage B geometry constants below are declared independently (for
readability) and CROSS-CHECKED against that committed fixture at
runtime (``_assert_matches_rfx_fixture``) -- a drift between the two
raises loud (exit 3, a config bug), rather than silently comparing
against stale numbers.

Port topology (M3 fix, 2026-08-04 review -- read before touching this
again): mirrors thru_openems.py's validated pattern FULLY, not
partially. The FIRST version of this script fused two precedents
incompatibly: it kept ``Feed_R=50`` (a genuine lumped termination
resistor, sitting at each port's own ``start``) AND ALSO extended the
PEC trace THROUGH both x-PMLs (the coax lane's H2 pattern). Those two
choices conflict: with the trace continuing past the resistor into a
PML-matched continuation of the SAME line (impedance close to this
line's own Z0, ~48-53 ohm per the rfx fixture's own measured Z0), each
port's resistor sits ELECTRICALLY IN PARALLEL with that continuation
-- roughly 50||50 ~= 25 ohm seen by the line, Gamma = (25-50)/(25+50)
~= -1/3, predicted |S11|~=0.33. That is enough to trip the passivity
witness (predicted max(|S11|^2+|S21|^2) ~= 1.11 against the 1.05
ceiling) on the FIRST real run -- a SELF-INFLICTED failure, not a
finding about openEMS or rfx. Fix: terminate the trace AT each port
with ``Feed_R=50`` as the ACTUAL load, matching thru_openems.py's own
topology exactly -- its single ``trace_metal.AddBox`` spans exactly
X1..X2 (each port's own ``start``), with NOTHING beyond that (no
PML-side continuation of the CONDUCTOR at all). Boundary: PML_8 on
every absorbing face (x lo/hi, y lo/hi, z hi), PEC on z lo -- matches
rfx's own ``BoundarySpec(x='cpml', y='cpml', z=Boundary(lo='pec',
hi='cpml'))`` exactly (no MUR anywhere in Stage B).

DELTA LIST (every remaining way this openEMS model differs from the
rfx fixture):
  1. SUBSTRATE EXTENSION THROUGH PML, TRACE DOES NOT (M3 fix -- retitled
     and narrowed from the pre-review version, which extended BOTH):
     the coax lane's H2 justification ("the full coax cross-section
     extends uniformly through both PML regions so PML is
     reflectionless") is the COAX lane's own record for a topology with
     NO mid-line shunt element -- it does not transfer here, where
     ``Feed_R=50`` IS a mid-line (at the port's own end) shunt, and
     continuing the CONDUCTOR past it created exactly the parallel-
     impedance defect M3 fixed. The TRACE (PEC) now spans EXACTLY
     feed_x0..feed_x1 (thru_openems.py's own single-AddBox span) --
     NOT through either PML. The SUBSTRATE (dielectric only, no
     conductor, so no analogous shunt-parallel discontinuity) still
     extends through the x/y-PML on all sides -- a plain dielectric
     background continuing into an absorber is not the pattern the coax
     lane's own record warns about, and avoids inventing a NEW,
     untested discontinuity (an abrupt dielectric-to-vacuum step right
     at the PML boundary) instead.
  2. FEED MODEL: rfx's Laplace-Ez static-mode source distributed over
     the port cross-section (``rfx/sources/msl_port.py``,
     ``make_msl_port_sources``) vs openEMS's own ``MSLPort`` excitation
     (a soft Ez source at the excitation mesh line, per-cell weighted
     by the ``upside_down``/``excite`` sign) -- both are distributed
     Ez launches over the trace-to-ground gap, not a point feed, but
     the exact per-cell weighting differs; no CSXCAD primitive
     reproduces rfx's own Laplace solve.
  3. MESH: rfx uses a UNIFORM dx=50um on all three axes (no thirds-
     rule refinement -- ``compute_msl_s_matrix`` does not do trace-edge
     mesh grading). This script adds a thirds-rule Y refinement at the
     trace edges (matching the openEMS MSL_NotchFilter.py tutorial's
     OWN convention, not thru_openems.py's plain-uniform mesh) since
     Stage B's phase/Z0 precision goal benefits more from trace-edge
     resolution than Stage A's simpler magnitude-only precedent did;
     the underlying background mesh is otherwise dx=50um uniform,
     matching rfx, EXCEPT the substrate's own top surface (m6 fix
     below: an explicit mesh line at z=254um, the tutorial's own
     ``linspace`` pattern, with the substrate's own rasterized cell
     count asserted rather than left to an uniform arange's arbitrary
     rounding -- the #325 rasterization class).
  4. WAVEFORM: rfx's Gaussian pulse (``freq_max/2`` centre,
     ``bandwidth=0.8`` fractional -- the ``add_msl_port`` default) vs
     openEMS's ``SetGaussExcite`` with matching f0/fc chosen from the
     SAME freq_max=5GHz band (f0=2.5GHz, fc=0.85*5=4.25GHz, the
     ``thru_openems.py`` f0-midband/fc-0.85x pattern) -- different
     waveform family by construction; only the illuminated band needs
     to cover the comparison window.
  5. MEASUREMENT-PLANE CLEARANCE (m5 fix): ``B_PORT_W_CELLS=6`` (300um
     at this Stage's dx=50um) sets the port's OWN physical footprint
     (excitation + Feed_R location) -- a direct COPY of thru_openems.py's
     cell count, but thru_openems.py's own dx was 500um, so ITS 6 cells
     were 3mm; blindly copying "6 cells" at a 10x finer mesh shrinks the
     PHYSICAL clearance 10x (engineering principle 1: physical absolute
     coordinates, not copied cell counts). ``MeasPlaneShift`` is now set
     EXPLICITLY (not left at the class default of half the port's own
     300um span, which would put the measurement stencil only 150um /
     3 cells from the excitation+resistor -- near-field contaminated)
     to EXACTLY this fixture's own ``ref_plane_shift`` target, 2.5mm --
     the SAME physical distance rfx's own #478 ``n_probe_offset``
     resolution places its probe 0 at, on the SAME fixture. The port's
     own physical span (``B_PORT_W_CELLS``) is UNCHANGED at 300um --
     ``MeasPlaneShift`` is not bounded by the port's own [start,stop]
     box (``MSLPort.__init__`` searches the GLOBAL mesh-line array for
     the nearest line to ``measplane_pos``, verified by reading the
     source directly), so a compact port footprint plus a remote,
     explicit measurement plane on the now-single-span shared trace
     (delta item 1) is a valid, and arguably MORE rfx-like, combination
     (a compact feed + a REMOTE measurement location, mirroring rfx's
     own N-probe philosophy) rather than requiring the port's own box
     to be physically 3mm long.

Hand-ported sanity checks (external scripts get no rfx preflight --
``external_solver_comparator.md`` step 3): (a) nonzero excitation
energy + nonzero port time trace (``_check_excitation_and_trace``,
scale-free per PR #547); (b) settling/truncation witness (timestep
count vs NrTS cap); (c) non-physical field guard (|S|>2.0 raises);
(d) PRE-solve fail-fast stdout scan (mesh/port-parse warning classes,
before the full NrTS budget is spent); (e) per-bin passivity ceiling
(M4 fix -- NAMED explicitly, not left implicit: M3's topology fix made
this ceiling SATISFIABLE by construction, not the underlying physics
CORRECT -- the device now sits between two genuinely Feed_R=50-matched
loads instead of each port's own resistor sitting in parallel with a
PML-matched line continuation, so a real run is no longer DOOMED to
trip this witness on the self-inflicted parallel-impedance defect
alone (pre-M3, predicted max ~1.11 against a 1.05 ceiling). Whether
the actual VESSL run passes it is still an open, unmeasured question --
NEW-4 fix, review 2026-08-04: "physically meaningful again" overclaimed
that M3 restored correctness; it only removed a KNOWN reason the gate
would have failed regardless of correctness).
``|S11|^2+|S21|^2 <= 1.05`` (``tol=0.05``) is the gate; given
this near-lossless matched thru's OWN measured |S21| ~= 1 (rfx-side:
mean|S21|=0.9985), the SAME inequality implies a NAMED ceiling
``|S11| <~ sqrt(1.05 - |S21|^2) ~= sqrt(1.05-0.997) ~= 0.23`` at bins
where |S21| stays near 1 -- a reported |S11| well above that ceiling
AT SUCH a bin specifically signals a port-mismatch/topology defect
(e.g. the exact M3 class this review caught), not genuine dielectric
loss, since this fixture's substrate is lossless by construction); (f)
self-consistency witness (mag band + phase vs THIS solver's OWN
measured beta, see CONVENTION NOTE "WHAT IS GATED" -- QUALIFIED, gate-
budget-derived, resolving-power-tested per the M1/M2 fixes above).

RFX-SIDE SELF-CONSISTENCY -- MEASURED, LOCALLY, BEFORE ANY VESSL RUN
(2026-08-04, RE-VERIFIED after the M1/M3/m5/m6 review-fix edits --
neither the rfx fixture nor its own geometry changed, since Stage B's
geometry edits are entirely openEMS-side): ``build_msl_thru_phase_
dx50um_reference.py`` was run locally (rfx IS importable outside
VESSL; only openEMS is VESSL-only) and its own committed output was
fed through THIS script's ``_self_consistency_witness`` directly (no
openEMS involved -- a pure Python check on real FDTD data):
mean|S11|=0.0482, mean|S21|=0.9985 (dx=50um, far cleaner than the
committed dx=80um fixture's 0.118/0.972 -- consistent with the finer
mesh), and the self-consistency check itself PASSED with
max_phase_dev_deg=0.121 (NOW gate=3 deg, ~25x margin -- was 30 deg
pre-M1) and group_delay_dev_ps=0.063 (gate 200 ps) against rfx's OWN
measured beta
over L12=5.0mm. This is real evidence the reference-plane-referral
MECHANISM (the ``(target-start)*direction`` transform, applied to
rfx's own probe-0 plane) and the sign convention in
``_self_consistency_witness`` are sound on genuine FDTD data -- not
merely self-consistent by construction -- though it says nothing yet
about openEMS's own side, which is the actual VESSL-pending unknown.
The gate bands (``B_S21_MAG_BAND``, ``B_PHASE_TOL_DEG``,
``B_GD_TOL_PS``) are NOT tightened from this rfx-only measurement
(report-first, gate-second: tightening now would bias the gate toward
whatever rfx alone achieves, not the openEMS-side unknown this referee
exists to test).

Exit codes (lane convention, ``docs/agent-memory/task_recipes/
vessl_external_referee_lane.md``): 0 = both stages' self-checks passed
(NOT a claim that rfx and openEMS numerically agree -- this referee
brackets); 1 = a PHYSICS/self-check gate failed (``RuntimeError``);
2 = openEMS Python bindings not importable (declared skip); 3 = an
INTERNAL CONFIGURATION error in this script's own geometry/layout math
or a drift against the committed rfx fixture (``AssertionError``).

MUST-MOVE-WHEN-VALIDATED (mirrors the coax/floquet referee governance
note): this script lives at ``validation/research/msl_phase_referee/``,
outside ``validation/crossval/`` and its ``manifest.json`` -- exempt
from crossval governance by construction (``.claude/rules/
rfx-feature-discovery.md`` + ``feedback_crossval_governance_glob_
bypass.md``). Move into ``validation/crossval/`` only after a real
VESSL run has filled ``REPRODUCE_GATE_RECORD`` AND issue #490's own
reviewer has judged the resulting convention-resolution evidence.

Usage (VESSL-only; openEMS is not importable outside
``scripts/vessl_msl_phase_referee.yaml``, which runs the PRIMARY
checkout -- this script must be merged to main before submitting)::

    python validation/research/msl_phase_referee/openems_msl_phase_referee.py \\
        --output .omx/msl-phase-referee/openems_msl_phase_referee.json
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Reproduce-gate record -- audit artifact (external_solver_comparator.md
# step 2). Committed UNRUN; a VESSL run fills these fields AND must supply a
# log path under a git-TRACKED prefix (PR #548 lesson -- .omx/ and
# docs/research_notes/vessl_logs/ are both gitignored and therefore
# unreadable by any reviewer outside the machine that ran the job).
# ---------------------------------------------------------------------------
_C0 = 2.998e8  # m/s -- matches the coax/notch precedent's own constant

# Stage A tutorial geometry (RO4350B) -- same substrate/trace/stub the
# repo's own cv06b/msl_notch_e4 comparison already validates a closed form
# against; recomputed independently here (not copy-pasted) as a regression
# lock on the reproduce-gate's own oracle.
_A_STUB_LEN_M = 12.0e-3
_A_W_TRACE_M = 600e-6
_A_H_SUB_M = 254e-6
_A_EPS_R = 3.66
_A_U = _A_W_TRACE_M / _A_H_SUB_M
_A_EPS_EFF = (_A_EPS_R + 1.0) / 2.0 + (_A_EPS_R - 1.0) / 2.0 * (1.0 + 12.0 / _A_U) ** -0.5
F_NOTCH_AN_HZ = _C0 / (4.0 * _A_STUB_LEN_M * np.sqrt(_A_EPS_EFF))

REPRODUCE_GATE_RECORD: dict = {
    "stage": "A",
    "tutorial": {
        "repo": "thliebig/openEMS",
        "path": "python/Tutorials/MSL_NotchFilter.py",
        "verified_present_on": "2026-08-04",
        "verified_via": "gh api repos/thliebig/openEMS/contents/python/Tutorials/MSL_NotchFilter.py",
        "submodule_pin_note": (
            "AddMSLPort is a long-standing openEMS primitive (predates the "
            "CoaxialPort 2026-05-13 addition the coax lane needed); no "
            "submodule-pin caveat applies."
        ),
    },
    "do_not_repeat": (
        "scripts/diagnostics/build_msl_notch_openems_comparison.py header: "
        "'at dx=80 um the substrate is only 3.175 cells ... the openEMS "
        "MSL-port extraction is NON-PHYSICAL (|S11|^2+|S21|^2 up to 8.9)'; "
        "'dx=50 um gives 5.08 substrate cells where BOTH solvers are "
        "passive' -- this script's Stage B uses dx=50um on the SAME "
        "RO4350B substrate for exactly that reason (Stage A's own mesh is "
        "the tutorial's own dx, ~lambda/50, unrelated to this trap)."
    ),
    "geometry": (
        "open-stub microstrip notch filter, RO4350B eps_r=3.66, "
        "h_sub=254um, MSL_width=600um, MSL_length=50mm (each side of "
        "centre), stub_length=12mm, f_max=7GHz, boundary "
        "['PML_8','PML_8','MUR','MUR','PEC','MUR'], thirds-rule Y-edge "
        "mesh refinement (tutorial's own 'third_mesh')"
    ),
    "documented_check": (
        "Quarter-wave open-stub notch: F_NOTCH_AN = c0/(4*stub_len*"
        "sqrt(eps_eff_HJ)) -- the SAME closed form validation/crossval/"
        "06b_msl_notch_filter_uniform.py already uses for this identical "
        "substrate/trace/stub combination (that script's own docstring: "
        "'fringing-free analytic 3.69 GHz'), independently recomputed "
        "here as F_NOTCH_AN_HZ, not copy-pasted, and cross-checked to 5 "
        "significant figures by the header test."
    ),
    "expected_f_notch_an_hz": float(F_NOTCH_AN_HZ),
    "gate": {
        # One-sided-low-biased band: docs/agent-memory/rfx-known-issues.md
        # records openEMS reading ~7% LOW vs the fringing-free analytic on
        # a DIFFERENT (not identical) line-length/domain combination of
        # this SAME substrate/trace/stub -- PREDICTED, not yet measured
        # for THIS exact tutorial geometry, hence the generosity.
        "f_notch_lo_hz": 0.80 * float(F_NOTCH_AN_HZ),
        "f_notch_hi_hz": 1.05 * float(F_NOTCH_AN_HZ),
    },
    "status": "UNRUN",
    "reproduced_f_notch_hz": None,
    "reproduced_f_notch_dev_pct": None,
    "log_path": None,
    "vessl_run_id": None,
    "verified_on": None,
}

DECLARED_QUESTION = (
    "Is rfx's MSL de-embedded phase (compute_msl_s_matrix's angle(S21)) "
    "'not gated' (docs/guides/sparameter_support_matrix.md, Wire port "
    "section: 'Phase is not gated because the reference conventions "
    "differ') because of an unresolved e^{+-j*omega*t} time-convention "
    "mismatch, or an unresolved reference-plane mismatch? Verified "
    "directly against both tools' own DFT-kernel source (module docstring "
    "CONVENTION NOTE): the kernels are identical, so it is a reference-"
    "plane question, resolved here by placing openEMS's own MeasPlaneShift "
    "measurement stencil directly at rfx's own probe-0 plane (issue "
    "#478/#469). NEW-1 CAVEAT (review 2026-08-04): on this fixture the "
    "effective CalcPort(ref_plane_shift=...) shift is 0.0 by construction "
    "(MeasPlaneShift's own target already lands exactly on an existing "
    "mesh line, measured in port_info -- see CONVENTION NOTE part (c)'s "
    "own 'NEW-1 FINDING'), so the referral ROTATION itself is exercised "
    "but not independently validated by this run; it is held in reserve "
    "for a future fixture whose target plane falls off-grid."
)

MUST_MOVE_WHEN_VALIDATED = (
    "Move into validation/crossval/ (+ manifest.json) only after a real "
    "VESSL run has filled REPRODUCE_GATE_RECORD with a number + log path, "
    "AND issue #490's own reviewer has judged the resulting convention-"
    "resolution evidence. Not before -- this file's presence under "
    "validation/research/ must not be read as a registered crossval pass "
    "(validation/research/floquet/rcwa_referee.py precedent)."
)

RFX_FIXTURE_PATH = "tests/fixtures/msl_phase_referee/msl_thru_rfx_dx50.json"

# ---------------------------------------------------------------------------
# Stage A geometry constants -- MSL_NotchFilter.py, verbatim (um units).
# ---------------------------------------------------------------------------
A_UNIT = 1.0e-6  # CSXCAD length unit: um (tutorial's own choice)
A_MSL_LENGTH_UM = 50000.0
A_MSL_WIDTH_UM = 600.0
A_SUBSTRATE_THICKNESS_UM = 254.0
A_SUBSTRATE_EPR = 3.66
A_STUB_LENGTH_UM = 12.0e3
A_F_MAX_HZ = 7.0e9
A_N_FREQS = 1601  # tutorial's own np.linspace(1e6, f_max, 1601)


# ---------------------------------------------------------------------------
# Stage B geometry constants -- declared here for readability, CROSS-
# CHECKED against the committed rfx fixture at runtime (see
# _assert_matches_rfx_fixture). All lengths in metres.
# ---------------------------------------------------------------------------
B_EPS_R = 3.66
B_H_SUB_M = 254e-6
B_W_TRACE_M = 600e-6
B_L_LINE_M = 10e-3
B_PORT_MARGIN_M = 2e-3
B_DX_M = 50e-6
B_CPML_CELLS = 8
B_F_MAX_HZ = 5.0e9
B_PORT_W_CELLS = 6  # thru_openems.py's own PORT_W pattern -- sets the
                    # port's OWN excitation+Feed_R footprint only (m5
                    # fix); the measurement plane is placed EXPLICITLY
                    # via MeasPlaneShift below, not derived from this.

B_F0_HZ = 0.5 * B_F_MAX_HZ            # 2.5 GHz -- thru_openems.py midband pattern
B_FC_HZ = 0.85 * B_F_MAX_HZ           # 4.25 GHz -- thru_openems.py 0.85x pattern

# Self-consistency witness gate band -- matches tests/test_msl_port_
# integration.py's own "quasi-TEM well-established" window (conservative;
# not re-derived for dx=50um, which should if anything establish earlier).
B_GATE_F_LO_HZ = 3.0e9
B_GATE_F_HI_HZ = 4.5e9

# Predicted (not yet measured) one-sided matched-through magnitude band --
# report-first, gate-second, per the coax/floquet precedent.
B_S21_MAG_BAND = (0.80, 1.10)
# Phase gate -- DERIVED from an explicit +-2-to-4-cell (100-200um)
# reference-plane positional-uncertainty budget at this fixture's own
# measured beta, with headroom; see module docstring "GATE-BUDGET
# DERIVATION" (M1 fix) for the full derivation and the resolving-power
# test that measures this gate actually discriminates a realistic
# referral defect (~16-22 deg for a single-port 2.5mm drop) with ~7-10x
# margin. NOT a round number -- was 30 deg pre-review (admitted a
# 3.372mm/67%-of-L12 plane error; a real referral-drop defect PASSED).
B_PHASE_TOL_DEG = 3.0
# Group-delay gate -- INERT for the reference-plane-referral failure
# class this file's own gate above targets (a constant plane-position
# error is nearly frequency-independent for this near-non-dispersive
# quasi-TEM line, so it barely perturbs a DERIVATIVE diagnostic -- see
# "GATE-BUDGET DERIVATION"/"GROUP-DELAY GATE HONESTY"). Kept for a
# DIFFERENT failure class: a gross np.unwrap failure or a genuine
# dispersion-model break (wrong eps_r, wrong beta sign, non-monotonic
# beta fit) -- 200ps is generous for THAT class, not for referral
# errors, and this gate passing must not be read as evidence about
# reference-plane correctness.
B_GD_TOL_PS = 200.0


# ---------------------------------------------------------------------------
# openEMS import plumbing (deferred, matches the coax/thru precedent so
# this module stays importable -- and testable -- without openEMS).
# ---------------------------------------------------------------------------
def _ensure_openems_numpy_compat() -> None:
    for name, value in {"float": float, "int": int, "complex": complex, "mat": np.matrix}.items():
        if not hasattr(np, name):
            setattr(np, name, value)


def _import_openems():
    _ensure_openems_numpy_compat()
    from CSXCAD.CSXCAD import ContinuousStructure
    from openEMS.openEMS import openEMS
    from openEMS.ports import MSLPort
    return ContinuousStructure, openEMS, MSLPort


# ---------------------------------------------------------------------------
# Shared sanity-check helpers (ticked against the coax/thru precedent above)
# ---------------------------------------------------------------------------
_BAD_STDOUT_PATTERNS = ("Unused primitive", "not on the mesh", "unused excitation")


def _scan_stdout_for_bad_patterns(log_text: str, label: str) -> None:
    hits = [p for p in _BAD_STDOUT_PATTERNS if p.lower() in log_text.lower()]
    if hits:
        raise RuntimeError(
            f"[{label}] pre-solve mesh/port fail-fast gate tripped: openEMS "
            f"stdout contains {hits!r}. Aborting BEFORE the full NrTS "
            f"budget is spent."
        )


def _run_openems_capturing_stdout(fdtd, sim_path: str, *, threads: int) -> str:
    """Run openEMS while capturing its OS-level stdout to a file we can grep.

    ``fdtd.Run()`` invokes the openEMS C++ binary; its stdout goes to the
    process's OS-level fd 1, not Python's ``sys.stdout`` -- redirect fd 1
    itself, restoring it afterward even on error (thru_openems.py/coax
    referee pattern).
    """
    os.makedirs(sim_path, exist_ok=True)
    log_path = os.path.join(sim_path, "_openems_stdout.log")
    stdout_fd = sys.stdout.fileno()
    saved_fd = os.dup(stdout_fd)
    with open(log_path, "w") as logf:
        sys.stdout.flush()
        os.dup2(logf.fileno(), stdout_fd)
        try:
            fdtd.Run(sim_path, cleanup=True, verbose=1, numThreads=threads)
        finally:
            sys.stdout.flush()
            os.dup2(saved_fd, stdout_fd)
            os.close(saved_fd)
    with open(log_path) as logf:
        return logf.read()


def _check_excitation_and_trace(port, sim_path: str, label: str, *,
                                channel: str = "uf_inc") -> tuple[float, int]:
    """Scale-free excitation/trace guard (issue #465/PR #473, reaffirmed
    PR #547 -- see the module docstring PRECEDENT TICK-LIST item 8). No
    absolute floor on the launched-channel peak: only exact-zero/non-finite
    is a defect signature, because the healthy and broken populations
    overlap in openEMS's raw units (verified-good runs as small as
    ~3e-14 are recorded in ``rfx/interop/emitters/openems.py``'s own [D5]
    guard).
    """
    launched = np.asarray(getattr(port, channel), dtype=np.complex128)
    peak = float(np.max(np.abs(launched))) if launched.size else 0.0
    if not np.isfinite(peak) or peak == 0.0:
        raise RuntimeError(
            f"[{label}] openEMS port injected/received NO wave energy on "
            f"its own launched channel ({channel}={peak!r}): excitation "
            f"did not couple or the port never saw the wave."
        )
    n_samples = 0
    for name in list(getattr(port, "U_filenames", []) or []):
        trace_path = os.path.join(sim_path, name)
        if not os.path.exists(trace_path):
            continue
        raw = np.loadtxt(trace_path, comments="%")
        if not raw.size:
            continue
        raw2 = np.atleast_2d(raw)
        n_samples = max(n_samples, raw2.shape[0])
        peak_here = float(np.max(np.abs(raw2[:, 1])))
        if peak_here == 0.0:
            raise RuntimeError(
                f"[{label}] openEMS port voltage time trace is identically "
                f"zero: the excitation never entered the grid."
            )
    return peak, n_samples


def _non_physical_guard(s_mag: np.ndarray, label: str) -> None:
    peak = float(np.max(s_mag)) if s_mag.size else float("nan")
    if not np.all(np.isfinite(s_mag)) or peak > 2.0:
        raise RuntimeError(
            f"[{label}] non-physical/unstable |S| max={peak!r}: field blew "
            f"up or diverged."
        )


def _passivity_witness(s11: np.ndarray, s21: np.ndarray, label: str, *,
                       tol: float = 0.05, idx=None) -> dict:
    balance_full = np.abs(s11) ** 2 + np.abs(s21) ** 2
    balance = balance_full[idx] if idx is not None else balance_full
    max_balance = float(np.max(balance))
    passed = bool(max_balance <= 1.0 + tol)
    if not passed:
        raise RuntimeError(
            f"[{label}] passivity witness failed: max(|S11|^2+|S21|^2)="
            f"{max_balance:.4f} > {1.0 + tol} -- non-physical energy gain."
        )
    return {"balance": balance.tolist(), "max_balance": max_balance,
            "tol": tol, "passed": passed}


def _self_consistency_witness(freqs_hz: np.ndarray, s21: np.ndarray, beta: np.ndarray,
                              *, l12_m: float, mag_band: tuple[float, float],
                              phase_tol_deg: float, gd_tol_ps: float, label: str) -> dict:
    """The CONVENTION-resolution gate (module docstring "WHAT IS GATED"):
    THIS solver's own de-embedded angle(S21) vs THIS solver's own measured
    beta, over the shared L12 span -- not a cross-solver comparison. See
    the coax lane's ``_matched_through_witness`` for the precedent this
    mirrors (mag band + phase-vs-own-beta + group delay, one-sided).
    """
    mask = (freqs_hz >= B_GATE_F_LO_HZ) & (freqs_hz <= B_GATE_F_HI_HZ)
    if not np.any(mask):
        mask = np.ones_like(freqs_hz, dtype=bool)

    s21_mag = np.abs(s21)
    mag_lo, mag_hi = mag_band
    mag_ok = bool(np.all((s21_mag[mask] >= mag_lo) & (s21_mag[mask] <= mag_hi)))

    beta_re = np.real(np.asarray(beta, dtype=np.complex128))
    expected_phase = -beta_re * l12_m
    measured_phase = np.unwrap(np.angle(s21))
    phase_dev_rad = np.angle(np.exp(1j * (measured_phase - expected_phase)))
    max_phase_dev_deg = float(np.degrees(np.max(np.abs(phase_dev_rad[mask]))))
    phase_ok = bool(max_phase_dev_deg < phase_tol_deg)

    omega = 2.0 * np.pi * freqs_hz
    gd_measured_s = -np.gradient(measured_phase, omega)
    gd_expected_s = -np.gradient(expected_phase, omega)
    gd_dev_ps = float(np.max(np.abs(gd_measured_s[mask] - gd_expected_s[mask])) * 1e12)
    gd_ok = bool(gd_dev_ps < gd_tol_ps)

    passed = bool(mag_ok and phase_ok and gd_ok)
    result = {
        "band_s21_mag": s21_mag[mask].tolist(), "mag_band_expected": [mag_lo, mag_hi],
        "mag_ok": mag_ok, "max_phase_dev_deg": max_phase_dev_deg,
        "phase_tol_deg": phase_tol_deg, "phase_ok": phase_ok,
        "group_delay_dev_ps": gd_dev_ps, "gd_tol_ps": gd_tol_ps, "gd_ok": gd_ok,
        "passed": passed,
    }
    if not passed:
        raise RuntimeError(f"[{label}] self-consistency witness failed: {result}")
    return result


# ---------------------------------------------------------------------------
# rfx fixture loading (plain JSON -- no rfx import; see module docstring
# SCOPE FENCE).
# ---------------------------------------------------------------------------
def _load_rfx_fixture(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"rfx-side committed fixture not found: {p}. Regenerate with "
            f"'python scripts/diagnostics/build_msl_thru_phase_dx50um_"
            f"reference.py --output {path}' (requires a local rfx install; "
            f"this openEMS script itself never imports rfx)."
        )
    return json.loads(p.read_text())


def _assert_matches_rfx_fixture(fixture: dict) -> None:
    """Drift guard: this script's OWN Stage B constants must match the
    committed fixture's ``meta`` block. A mismatch is a CONFIG bug (exit
    3), not a physics finding -- it means the two sides silently stopped
    describing the same geometry.
    """
    meta = fixture["meta"]
    checks = [
        ("eps_r", meta["eps_r"], B_EPS_R),
        ("h_sub_m", meta["h_sub_m"], B_H_SUB_M),
        ("w_trace_m", meta["w_trace_m"], B_W_TRACE_M),
        ("l_line_m", meta["l_line_m"], B_L_LINE_M),
        ("port_margin_m", meta["port_margin_m"], B_PORT_MARGIN_M),
        ("dx_m", meta["dx_m"], B_DX_M),
        ("f_max_hz", meta["f_max_hz"], B_F_MAX_HZ),
    ]
    for name, fixture_val, local_val in checks:
        assert abs(float(fixture_val) - float(local_val)) < 1e-12 * max(1.0, abs(local_val)), (
            f"Stage B constant {name!r} drifted from the committed rfx "
            f"fixture: script={local_val!r} fixture={fixture_val!r}. "
            f"Regenerate the fixture or update the script constants."
        )


def _stage_b_layout(fixture: dict) -> dict:
    """Pure arithmetic (openEMS-free, testable without the solver): every
    Stage B position/ref_plane_shift, in metres. An AssertionError here is
    a config bug (exit 3), matching the coax lane's ``_stage_b_layout``
    convention.
    """
    _assert_matches_rfx_fixture(fixture)
    geom = fixture["reference_plane_geometry"]
    grid = geom["_grid"]

    lx_clear_m = grid["rasterized_clear_m"]["x"]
    ly_clear_m = grid["rasterized_clear_m"]["y"]
    lz_clear_m = grid["rasterized_clear_m"]["z"]
    pml_x_m = grid["pad_x_lo"] * grid["dx"]
    pml_y_m = grid["pad_y_lo"] * grid["dx"]
    pml_z_hi_m = grid["pad_z_hi"] * grid["dx"]

    p0 = geom["msl_0"]
    p1 = geom["msl_1"]
    assert p0["direction"] == "+x" and p1["direction"] == "-x", (
        "unexpected port direction in the committed rfx fixture"
    )

    def _ref_plane_shift(port_geom: dict) -> float:
        direction = 1.0 if port_geom["direction"] == "+x" else -1.0
        return (port_geom["probe0_x_m"] - port_geom["feed_x_m"]) * direction

    ref_plane_shift_port0_m = _ref_plane_shift(p0)
    ref_plane_shift_port1_m = _ref_plane_shift(p1)
    l12_m = abs(p1["probe0_x_m"] - p0["probe0_x_m"])

    layout = {
        "lx_clear_m": lx_clear_m, "ly_clear_m": ly_clear_m, "lz_clear_m": lz_clear_m,
        "pml_x_m": pml_x_m, "pml_y_m": pml_y_m, "pml_z_hi_m": pml_z_hi_m,
        "feed_x_port0_m": p0["feed_x_m"], "feed_x_port1_m": p1["feed_x_m"],
        "probe0_x_port0_m": p0["probe0_x_m"], "probe0_x_port1_m": p1["probe0_x_m"],
        "ref_plane_shift_port0_m": ref_plane_shift_port0_m,
        "ref_plane_shift_port1_m": ref_plane_shift_port1_m,
        "l12_m": l12_m,
    }

    # Config assertions (a regression here is a script bug, exit 3).
    assert lx_clear_m > 0 and ly_clear_m > 0 and lz_clear_m > 0
    assert 0.0 < p0["feed_x_m"] < p1["feed_x_m"] < lx_clear_m, (
        "Stage B port ordering broken (port0 must sit left of port1)"
    )
    assert p0["probe0_x_m"] < p1["probe0_x_m"], (
        "Stage B probe-0 ordering broken"
    )
    port_w_m = B_PORT_W_CELLS * B_DX_M
    assert port_w_m < abs(p1["feed_x_m"] - p0["feed_x_m"]) / 2.0, (
        "Stage B port span too long relative to the feed-to-feed gap "
        "(ports would overlap at line centre)"
    )
    return layout


# ---------------------------------------------------------------------------
# STAGE A: faithful port of MSL_NotchFilter.py.
# ---------------------------------------------------------------------------
def _build_stage_a_notch_tutorial(ContinuousStructure, openEMS, MSLPort, *,
                                  nrts: int | None, end_criteria: float | None):
    """Build MSL_NotchFilter.py's geometry fresh (smoke + real run, matching
    the coax/thru precedent's "separate openEMS instances" pattern)."""
    kw = {}
    if nrts is not None:
        kw["NrTS"] = nrts
    if end_criteria is not None:
        kw["EndCriteria"] = end_criteria
    fdtd = openEMS(**kw)
    fdtd.SetGaussExcite(A_F_MAX_HZ / 2.0, A_F_MAX_HZ / 2.0)
    fdtd.SetBoundaryCond(["PML_8", "PML_8", "MUR", "MUR", "PEC", "MUR"])

    csx = ContinuousStructure()
    fdtd.SetCSX(csx)
    mesh = csx.GetGrid()
    mesh.SetDeltaUnit(A_UNIT)

    resolution = _C0 / (A_F_MAX_HZ * np.sqrt(A_SUBSTRATE_EPR)) / A_UNIT / 50.0
    third_mesh = np.array([2.0 * resolution / 3.0, -resolution / 3.0]) / 4.0

    mesh.AddLine("x", [0.0])
    mesh.AddLine("x", A_MSL_WIDTH_UM / 2.0 + third_mesh)
    mesh.AddLine("x", -A_MSL_WIDTH_UM / 2.0 - third_mesh)
    mesh.SmoothMeshLines("x", resolution / 4.0)
    mesh.AddLine("x", [-A_MSL_LENGTH_UM, A_MSL_LENGTH_UM])
    mesh.SmoothMeshLines("x", resolution)

    mesh.AddLine("y", [0.0])
    mesh.AddLine("y", A_MSL_WIDTH_UM / 2.0 + third_mesh)
    mesh.AddLine("y", -A_MSL_WIDTH_UM / 2.0 - third_mesh)
    mesh.SmoothMeshLines("y", resolution / 4.0)
    mesh.AddLine("y", [-15.0 * A_MSL_WIDTH_UM, 15.0 * A_MSL_WIDTH_UM + A_STUB_LENGTH_UM])
    mesh.AddLine("y", (A_MSL_WIDTH_UM / 2.0 + A_STUB_LENGTH_UM) + third_mesh)
    mesh.SmoothMeshLines("y", resolution)

    mesh.AddLine("z", np.linspace(0.0, A_SUBSTRATE_THICKNESS_UM, 5))
    mesh.AddLine("z", [3000.0])
    mesh.SmoothMeshLines("z", resolution)

    substrate = csx.AddMaterial("RO4350B", epsilon=A_SUBSTRATE_EPR)
    substrate.AddBox(
        [-A_MSL_LENGTH_UM, -15.0 * A_MSL_WIDTH_UM, 0.0],
        [A_MSL_LENGTH_UM, 15.0 * A_MSL_WIDTH_UM + A_STUB_LENGTH_UM, A_SUBSTRATE_THICKNESS_UM],
    )

    pec = csx.AddMetal("PEC")
    port0 = MSLPort(
        csx, port_nr=1, metal_prop=pec,
        start=[-A_MSL_LENGTH_UM, -A_MSL_WIDTH_UM / 2.0, A_SUBSTRATE_THICKNESS_UM],
        stop=[0.0, A_MSL_WIDTH_UM / 2.0, 0.0],
        prop_dir="x", exc_dir="z", excite=-1.0,
        FeedShift=10.0 * resolution, MeasPlaneShift=A_MSL_LENGTH_UM / 3.0,
        priority=10,
    )
    port1 = MSLPort(
        csx, port_nr=2, metal_prop=pec,
        start=[A_MSL_LENGTH_UM, -A_MSL_WIDTH_UM / 2.0, A_SUBSTRATE_THICKNESS_UM],
        stop=[0.0, A_MSL_WIDTH_UM / 2.0, 0.0],
        prop_dir="x", exc_dir="z",
        MeasPlaneShift=A_MSL_LENGTH_UM / 3.0,
        priority=10,
    )

    pec.AddBox(
        [-A_MSL_WIDTH_UM / 2.0, A_MSL_WIDTH_UM / 2.0, A_SUBSTRATE_THICKNESS_UM],
        [A_MSL_WIDTH_UM / 2.0, A_MSL_WIDTH_UM / 2.0 + A_STUB_LENGTH_UM, A_SUBSTRATE_THICKNESS_UM],
        priority=10,
    )
    return fdtd, port0, port1


def _run_stage_a_reproduce_gate(*, sim_root: str, threads: int) -> dict:
    ContinuousStructure, openEMS, MSLPort = _import_openems()

    sim_dir = os.path.join(sim_root, "stage_a_notch_tutorial")
    smoke_dir = os.path.join(sim_root, "stage_a_notch_tutorial_smoke")

    smoke_fdtd, _p0, _p1 = _build_stage_a_notch_tutorial(
        ContinuousStructure, openEMS, MSLPort, nrts=200, end_criteria=0.0)
    smoke_log = _run_openems_capturing_stdout(smoke_fdtd, smoke_dir, threads=threads)
    _scan_stdout_for_bad_patterns(smoke_log, "stage_a_smoke")

    # Tutorial's own defaults (NrTS~=1e9, EndCriteria=1e-5) -- verbatim,
    # not overridden (module docstring STAGE A).
    fdtd, port0, port1 = _build_stage_a_notch_tutorial(
        ContinuousStructure, openEMS, MSLPort, nrts=None, end_criteria=None)

    t0 = time.time()
    real_log = _run_openems_capturing_stdout(fdtd, sim_dir, threads=threads)
    _scan_stdout_for_bad_patterns(real_log, "stage_a")
    elapsed = time.time() - t0

    freqs = np.linspace(1.0e6, A_F_MAX_HZ, A_N_FREQS)
    port0.CalcPort(sim_dir, freqs)
    port1.CalcPort(sim_dir, freqs)

    inc_peak, n_samples = _check_excitation_and_trace(port0, sim_dir, "stage_a")
    truncated = False  # NrTS defaults to ~1e9; EndCriteria decay is the stop condition here

    s11 = np.asarray(port0.uf_ref, dtype=np.complex128) / np.asarray(port0.uf_inc, dtype=np.complex128)
    s21 = np.asarray(port1.uf_ref, dtype=np.complex128) / np.asarray(port0.uf_inc, dtype=np.complex128)
    _non_physical_guard(np.abs(s11), "stage_a_s11")
    _non_physical_guard(np.abs(s21), "stage_a_s21")

    s21_db = 20.0 * np.log10(np.abs(s21) + 1e-30)
    # Search only the physically-plausible window around the analytic
    # estimate (avoids a spurious minimum elsewhere in the 1601-point,
    # 7 GHz sweep).
    search_lo, search_hi = 0.5 * F_NOTCH_AN_HZ, 1.5 * F_NOTCH_AN_HZ
    search_mask = (freqs >= search_lo) & (freqs <= search_hi)
    if not np.any(search_mask):
        search_mask = np.ones_like(freqs, dtype=bool)
    i_local = int(np.argmin(s21_db[search_mask]))
    f_notch = float(freqs[search_mask][i_local])
    notch_depth_db = float(s21_db[search_mask][i_local])

    gate = REPRODUCE_GATE_RECORD["gate"]
    f_notch_ok = bool(gate["f_notch_lo_hz"] <= f_notch <= gate["f_notch_hi_hz"])

    passed = bool(f_notch_ok)
    return {
        "freqs_hz": freqs.tolist(),
        "s11_mag": np.abs(s11).tolist(), "s21_mag": np.abs(s21).tolist(),
        "f_notch_hz": f_notch, "notch_depth_db": notch_depth_db,
        "f_notch_expected_hz": float(F_NOTCH_AN_HZ),
        "f_notch_dev_pct": abs(f_notch - F_NOTCH_AN_HZ) / F_NOTCH_AN_HZ * 100.0,
        "f_notch_ok": f_notch_ok,
        "max_uf_inc": inc_peak, "n_trace_samples": n_samples,
        "truncated_suspected": truncated, "elapsed_s": round(elapsed, 1),
        "passed": passed,
    }


# ---------------------------------------------------------------------------
# STAGE B: rfx-matched thru-line, at dx=50um, with ref_plane_shift referral.
# ---------------------------------------------------------------------------
def _stage_b_substrate_z_mesh(h_sub: float, dx: float) -> tuple[np.ndarray, int]:
    """m6 fix: an explicit mesh line AT the substrate top (the openEMS
    MSL_NotchFilter.py tutorial's own ``linspace(0, substrate_thickness,
    5)`` pattern), instead of leaving the substrate top wherever a plain
    uniform ``np.arange`` from z=0 happens to land -- the #325
    rasterization class (intended vs ACTUAL cell count silently
    disagreeing; rfx's own do-not-repeat here covered dx choice, not
    z-line PLACEMENT). Builds a uniform sub-mesh spanning EXACTLY
    [0, h_sub] with ``round(h_sub/dx)`` cells (5 at this fixture's own
    h_sub=254um/dx=50um -- NOT an even divisor, so each substrate cell is
    ~50.8um, not exactly dx -- redistributing the mismatch across the
    substrate instead of leaving one arbitrary sliver cell wherever an
    unguided arange happened to cross z=h_sub).

    Pure arithmetic, openEMS-free -- testable directly (see the header
    test's own rasterized-substrate-cell-count pin).
    """
    n_sub = max(1, round(h_sub / dx))
    z_lines_sub = np.linspace(0.0, h_sub, n_sub + 1)
    return z_lines_sub, n_sub


def _predict_measplane_snap(target_shift_m: float, dx_m: float) -> float:
    """Predict what ``MSLPort.__init__``'s own mesh-line snap will compute
    for ``measplane_shift``, given a UNIFORM x-mesh at step ``dx_m`` (Stage
    B's own x-mesh has no thirds-rule refinement, unlike y -- see
    ``_build_stage_b``). openEMS's own snap (``python/openEMS/ports.py``,
    fetched 2026-08-04): ``meas_pos_idx = argmin(abs(prop_lines -
    measplane_pos))`` then ``measplane_shift = abs(start - prop_lines[
    meas_pos_idx])`` -- on a uniform grid whose own ``start`` already sits
    exactly on a mesh line (true for this fixture's own feed_x0/feed_x1,
    both integer multiples of dx_m from the mesh origin), this is exactly
    rounding ``target_shift_m`` to the nearest integer multiple of
    ``dx_m``. Pure arithmetic, openEMS-free -- ``_build_stage_b`` (VESSL-
    only, openEMS required) cross-checks the REAL, measured ``port.
    measplane_shift`` against this prediction at build time, so a future
    mesh change that breaks the "uniform, start-aligned grid" assumption
    this function relies on fails loud (an AssertionError), not silently.
    """
    n_cells = round(target_shift_m / dx_m)
    return n_cells * dx_m


def _stage_b_port_placement(layout: dict) -> dict:
    """Pure arithmetic (openEMS-free): the trace span, each port's target
    MeasPlaneShift/ref_plane_shift, and a PREDICTION of the resulting
    EFFECTIVE CalcPort shift (``ref_plane_shift - measplane_shift``).
    ``_build_stage_b`` calls this directly for its own AddBox/
    MeasPlaneShift values (wired, not a second hand-copy) and returns both
    this prediction AND the REAL, openEMS-measured values for the caller
    to record.

    NEW-1 finding (review 2026-08-04, the one that matters): on the
    COMMITTED fixture, ``ref_plane_shift`` and the predicted
    ``measplane_shift`` are IDENTICAL (both land on an EXISTING mesh line
    -- dx=50um divides the 2.5mm target exactly, 50 cells), so the
    predicted ``effective_shift`` is 0.0. ``CalcPort``'s own TL-phase-
    rotation (``python/openEMS/ports.py``, base ``Port.CalcPort``:
    ``phase = real(beta)*shift; uf_tot' = uf_tot*cos(-phase) + ...``) is
    therefore a NO-OP on THIS specific fixture -- the phase-plane
    correctness this referee measures comes from ``MeasPlaneShift``'s own
    STENCIL PLACEMENT landing exactly at rfx's own probe-0 plane, not from
    the referral ROTATION actually correcting a nonzero offset. The
    ``ref_plane_shift`` argument is still passed to ``CalcPort`` (the code
    path exists and is exercised, computing and applying a shift of
    0.0 -- not skipped), and remains the correct, necessary mechanism for
    a geometry where the target plane does NOT happen to fall exactly on
    a pre-existing mesh line; this fixture's own placement was chosen
    (m5 fix) specifically so it WOULD land exactly on-grid, which is what
    makes the shift trivial here. See DECLARED_QUESTION / module
    docstring CONVENTION NOTE for the full, non-overclaiming statement.
    """
    trace_x_start_m = layout["feed_x_port0_m"]
    trace_x_stop_m = layout["feed_x_port1_m"]
    ref_shift0_m = layout["ref_plane_shift_port0_m"]
    ref_shift1_m = layout["ref_plane_shift_port1_m"]
    measplane_predicted0_m = _predict_measplane_snap(ref_shift0_m, B_DX_M)
    measplane_predicted1_m = _predict_measplane_snap(ref_shift1_m, B_DX_M)
    return {
        "trace_x_start_m": trace_x_start_m,
        "trace_x_stop_m": trace_x_stop_m,
        "ref_plane_shift_port0_m": ref_shift0_m,
        "ref_plane_shift_port1_m": ref_shift1_m,
        # The value passed as the MeasPlaneShift= kwarg (m5 fix): the
        # SAME target ref_plane_shift is aimed for directly.
        "measplane_shift_target_port0_m": ref_shift0_m,
        "measplane_shift_target_port1_m": ref_shift1_m,
        "measplane_shift_predicted_port0_m": measplane_predicted0_m,
        "measplane_shift_predicted_port1_m": measplane_predicted1_m,
        "effective_shift_predicted_port0_m": ref_shift0_m - measplane_predicted0_m,
        "effective_shift_predicted_port1_m": ref_shift1_m - measplane_predicted1_m,
    }


def _build_stage_b(ContinuousStructure, openEMS, MSLPort, layout: dict, *,
                   nrts: int, end_criteria: float):
    unit = 1.0e-6  # um, independent CSXCAD unit choice for Stage B
    dx = B_DX_M / unit

    lx_clear = layout["lx_clear_m"] / unit
    ly_clear = layout["ly_clear_m"] / unit
    lz_clear = layout["lz_clear_m"] / unit
    pml_x = layout["pml_x_m"] / unit
    pml_y = layout["pml_y_m"] / unit
    pml_z_hi = layout["pml_z_hi_m"] / unit

    # z_lo is PEC, no padding below (matches rfx pad_z_lo=0).
    x0, x1 = -pml_x, lx_clear + pml_x
    y0, y1 = -pml_y, ly_clear + pml_y
    z1 = lz_clear + pml_z_hi  # z=0 is the PEC ground plane (z_lo, no padding)

    y_centre = ly_clear / 2.0
    w_trace = B_W_TRACE_M / unit
    h_sub = B_H_SUB_M / unit
    trace_y_lo = y_centre - w_trace / 2.0
    trace_y_hi = y_centre + w_trace / 2.0

    fdtd = openEMS(NrTS=nrts, EndCriteria=end_criteria)
    fdtd.SetGaussExcite(B_F0_HZ, B_FC_HZ)
    # x lo/hi, y lo/hi, z lo/hi -- PEC on z lo (ground), PML_8 everywhere
    # else (matches rfx's own BoundarySpec exactly; no MUR in Stage B).
    fdtd.SetBoundaryCond(["PML_8", "PML_8", "PML_8", "PML_8", "PEC", "PML_8"])

    csx = ContinuousStructure()
    fdtd.SetCSX(csx)
    mesh = csx.GetGrid()
    mesh.SetDeltaUnit(unit)

    resolution = dx
    # Thirds-rule Y refinement at the trace edges (module docstring DELTA
    # LIST item 3 -- the MSL_NotchFilter.py tutorial's own convention,
    # applied here for Stage B's phase-precision goal).
    third_mesh = np.array([2.0 * resolution / 3.0, -resolution / 3.0]) / 4.0

    x_lines = np.arange(x0, x1 + 0.5 * dx, dx)
    mesh.AddLine("x", x_lines)

    mesh.AddLine("y", [y0, y1])
    mesh.AddLine("y", trace_y_lo + third_mesh)
    mesh.AddLine("y", trace_y_hi + third_mesh)
    y_lines_bulk = np.arange(y0, y1 + 0.5 * dx, dx)
    mesh.AddLine("y", y_lines_bulk)
    mesh.SmoothMeshLines("y", resolution / 4.0, 1.4)

    # m6 fix: explicit substrate-top line (z=h_sub), not left to an
    # unguided uniform arange (see _stage_b_substrate_z_mesh docstring).
    z_lines_sub, n_sub = _stage_b_substrate_z_mesh(h_sub, dx)
    assert n_sub == round(B_H_SUB_M / B_DX_M), (
        f"Stage B substrate rasterized cell count drifted: got {n_sub}, "
        f"expected round(h_sub/dx)={round(B_H_SUB_M / B_DX_M)} (#325 class)"
    )
    z_lines_air = np.arange(h_sub, z1 + 0.5 * dx, dx)
    mesh.AddLine("z", z_lines_sub)
    mesh.AddLine("z", z_lines_air)

    # Substrate (dielectric only) extended through the x/y-PML; the TRACE
    # (conductor) is NOT (M3 fix -- see module docstring "Port topology").
    substrate = csx.AddMaterial("ro4350b", epsilon=B_EPS_R)
    substrate.AddBox([x0, y0, 0.0], [x1, y1, h_sub])

    pec = csx.AddMetal("copper")
    # NEW-3 fix (review 2026-08-04): the trace span and MeasPlaneShift
    # targets are now sourced from the PURE, openEMS-free
    # _stage_b_port_placement (wired, not a second hand-copy) so the
    # header test can assert on the SAME numbers this function actually
    # uses, instead of grepping the source text.
    placement = _stage_b_port_placement(layout)
    feed_x0 = placement["trace_x_start_m"] / unit
    feed_x1 = placement["trace_x_stop_m"] / unit
    port_w = B_PORT_W_CELLS * dx

    # M3 fix: the trace spans EXACTLY feed_x0..feed_x1 -- thru_openems.py's
    # own single-AddBox span (X1..X2, each port's own `start`) -- with
    # NOTHING beyond either port toward the PML (no through-PML
    # continuation of the conductor; see module docstring "Port topology"
    # for the parallel-impedance defect this fixes).
    pec.AddBox([feed_x0, trace_y_lo, h_sub], [feed_x1, trace_y_hi, h_sub + dx], priority=10)

    # m5 fix: MeasPlaneShift set EXPLICITLY to this fixture's own
    # ref_plane_shift target (2.5mm here, same "unit" as ref_plane_shift
    # in _run_stage_b's own CalcPort call) -- NOT the class default (half
    # the port's own 300um span, 150um/3 cells from the excitation+
    # Feed_R -- near-field contaminated). See module docstring DELTA LIST
    # item 5.
    measplane_target0_units = placement["measplane_shift_target_port0_m"] / unit
    measplane_target1_units = placement["measplane_shift_target_port1_m"] / unit

    port0_metal = csx.AddMetal("port0_metal")
    port0 = MSLPort(
        csx, port_nr=1, metal_prop=port0_metal,
        start=[feed_x0, trace_y_lo, h_sub], stop=[feed_x0 + port_w, trace_y_hi, 0.0],
        prop_dir="x", exc_dir="z", excite=1.0, Feed_R=50.0,
        MeasPlaneShift=measplane_target0_units, priority=10,
    )
    port1_metal = csx.AddMetal("port1_metal")
    port1 = MSLPort(
        csx, port_nr=2, metal_prop=port1_metal,
        start=[feed_x1, trace_y_lo, h_sub], stop=[feed_x1 - port_w, trace_y_hi, 0.0],
        prop_dir="x", exc_dir="z", excite=0.0, Feed_R=50.0,
        MeasPlaneShift=measplane_target1_units, priority=10,
    )

    # n8 fix: assert the ports' own `start` (what ref_plane_shift/
    # MeasPlaneShift are BOTH computed relative to, module docstring
    # CONVENTION NOTE part (c)) still equals feed_x0/feed_x1 -- a silent
    # coupling: _stage_b_layout computes ref_plane_shift assuming
    # `start[prop] == feed_x`, but nothing enforced that invariant at the
    # point the ports are actually built, ~250 lines away.
    assert abs(float(port0.start[0]) - feed_x0) < 1e-6, (
        "Stage B port0 start drifted from the ref_plane_shift/"
        "MeasPlaneShift target (250-line silent coupling, n8 regression)"
    )
    assert abs(float(port1.start[0]) - feed_x1) < 1e-6, (
        "Stage B port1 start drifted from the ref_plane_shift/"
        "MeasPlaneShift target (250-line silent coupling, n8 regression)"
    )

    # NEW-1/NEW-3 fix (review 2026-08-04): read openEMS's OWN, REAL,
    # mesh-line-snapped measplane_shift (available immediately after
    # MSLPort.__init__ -- see _predict_measplane_snap's own docstring)
    # and cross-check it against the PURE prediction above (an
    # AssertionError here means Stage B's own "uniform, start-aligned
    # x-mesh" assumption broke -- e.g. a future edit adds x-refinement --
    # not a physics finding). Compute the REAL effective CalcPort shift
    # (ref_plane_shift - measured measplane_shift) so the artifact records
    # what ref_plane_shift ACTUALLY did on this run, not just what this
    # script predicted it would do.
    measplane_real0_m = float(port0.measplane_shift) * unit
    measplane_real1_m = float(port1.measplane_shift) * unit
    assert abs(measplane_real0_m - placement["measplane_shift_predicted_port0_m"]) < 1e-9, (
        f"Stage B port0's REAL measplane_shift ({measplane_real0_m} m) does "
        f"not match the pure-arithmetic prediction "
        f"({placement['measplane_shift_predicted_port0_m']} m) -- the "
        f"uniform-grid assumption _predict_measplane_snap relies on broke"
    )
    assert abs(measplane_real1_m - placement["measplane_shift_predicted_port1_m"]) < 1e-9, (
        f"Stage B port1's REAL measplane_shift ({measplane_real1_m} m) does "
        f"not match the pure-arithmetic prediction "
        f"({placement['measplane_shift_predicted_port1_m']} m) -- the "
        f"uniform-grid assumption _predict_measplane_snap relies on broke"
    )

    port_info = dict(placement)
    port_info["measplane_shift_real_port0_m"] = measplane_real0_m
    port_info["measplane_shift_real_port1_m"] = measplane_real1_m
    port_info["effective_shift_real_port0_m"] = (
        placement["ref_plane_shift_port0_m"] - measplane_real0_m
    )
    port_info["effective_shift_real_port1_m"] = (
        placement["ref_plane_shift_port1_m"] - measplane_real1_m
    )

    return fdtd, port0, port1, port_info


def _run_stage_b(*, sim_root: str, threads: int, nrts: int, end_criteria: float,
                 rfx_fixture: dict) -> dict:
    ContinuousStructure, openEMS, MSLPort = _import_openems()
    layout = _stage_b_layout(rfx_fixture)

    sim_dir = os.path.join(sim_root, "stage_b_thru")
    smoke_dir = os.path.join(sim_root, "stage_b_thru_smoke")

    smoke_fdtd, _p0, _p1, _pinfo = _build_stage_b(
        ContinuousStructure, openEMS, MSLPort, layout, nrts=200, end_criteria=0.0)
    smoke_log = _run_openems_capturing_stdout(smoke_fdtd, smoke_dir, threads=threads)
    _scan_stdout_for_bad_patterns(smoke_log, "stage_b_smoke")

    fdtd, port0, port1, port_info = _build_stage_b(
        ContinuousStructure, openEMS, MSLPort, layout, nrts=nrts, end_criteria=end_criteria)

    t0 = time.time()
    real_log = _run_openems_capturing_stdout(fdtd, sim_dir, threads=threads)
    _scan_stdout_for_bad_patterns(real_log, "stage_b")
    elapsed = time.time() - t0
    end_criteria_not_reached = "reached before the end-criteria of" in real_log

    freqs_hz = np.asarray(rfx_fixture["freqs_hz"], dtype=float)
    unit = 1.0e-6
    # NEW-1 fix: ref_plane_shift is the SAME target port_info already
    # recorded as measplane_shift_target -- on this fixture the two are
    # identical by construction (see _stage_b_port_placement's own
    # docstring), so this call's own rotation is a measured no-op
    # (port_info["effective_shift_real_port{0,1}_m"] ~= 0.0). The
    # argument is still passed -- the code path is exercised, not
    # skipped -- for a geometry where the target would NOT land exactly
    # on-grid.
    ref_shift0_units = port_info["ref_plane_shift_port0_m"] / unit
    ref_shift1_units = port_info["ref_plane_shift_port1_m"] / unit

    port0.CalcPort(sim_dir, freqs_hz, ref_plane_shift=ref_shift0_units)
    port1.CalcPort(sim_dir, freqs_hz, ref_plane_shift=ref_shift1_units)

    inc_peak, n_samples = _check_excitation_and_trace(port0, sim_dir, "stage_b", channel="uf_inc")
    truncated = bool(nrts > 0 and n_samples >= nrts)

    s11 = np.asarray(port0.uf_ref, dtype=np.complex128) / np.asarray(port0.uf_inc, dtype=np.complex128)
    s21 = np.asarray(port1.uf_ref, dtype=np.complex128) / np.asarray(port0.uf_inc, dtype=np.complex128)
    beta_port0 = np.asarray(getattr(port0, "beta", np.full_like(freqs_hz, np.nan, dtype=complex)), dtype=np.complex128)
    beta_port1 = np.asarray(getattr(port1, "beta", np.full_like(freqs_hz, np.nan, dtype=complex)), dtype=np.complex128)

    partial_data = {
        "freqs_hz": freqs_hz.tolist(),
        "s11": [[float(c.real), float(c.imag)] for c in s11],
        "s21": [[float(c.real), float(c.imag)] for c in s21],
        "s11_mag": np.abs(s11).tolist(), "s21_mag": np.abs(s21).tolist(),
        "beta_port0": [[float(c.real), float(c.imag)] for c in beta_port0],
        "beta_port1": [[float(c.real), float(c.imag)] for c in beta_port1],
        "port_info": port_info,
        "max_uf_inc": inc_peak, "n_trace_samples": n_samples, "nrts_cap": nrts,
        "truncated_suspected": truncated, "elapsed_s": round(elapsed, 1),
        "end_criteria_not_reached": end_criteria_not_reached,
    }

    try:
        _non_physical_guard(np.abs(s11), "stage_b_s11")
        _non_physical_guard(np.abs(s21), "stage_b_s21")
        passivity = _passivity_witness(s11, s21, "stage_b")

        beta_openems = 0.5 * (beta_port0 + beta_port1)
        self_consistency_openems = _self_consistency_witness(
            freqs_hz, s21, beta_openems, l12_m=layout["l12_m"],
            mag_band=B_S21_MAG_BAND, phase_tol_deg=B_PHASE_TOL_DEG,
            gd_tol_ps=B_GD_TOL_PS, label="stage_b_openems_self_consistency",
        )
    except RuntimeError as exc:
        exc.partial_stage_b_data = partial_data
        raise

    # --- Cross-solver comparison (REPORTED, not gated -- module docstring
    # "WHAT IS GATED vs REPORTED"). ---
    s21_rfx = np.asarray([complex(re, im) for re, im in rfx_fixture["s21"]], dtype=np.complex128)
    beta_rfx = np.asarray([complex(re, im) for re, im in rfx_fixture["beta_first_port"]], dtype=np.complex128)
    assert s21_rfx.shape == freqs_hz.shape, "rfx fixture S21 length mismatch vs freqs_hz"

    phase_rfx = np.unwrap(np.angle(s21_rfx))
    phase_openems = np.unwrap(np.angle(s21))
    raw_phase_diff_deg = np.degrees(np.angle(np.exp(1j * (phase_rfx - phase_openems))))

    beta_ratio = np.real(beta_rfx) / np.where(np.real(beta_openems) != 0, np.real(beta_openems), np.nan)
    dispersion_predicted_diff_rad = (np.real(beta_openems) - np.real(beta_rfx)) * layout["l12_m"]
    residual_after_dispersion_deg = np.degrees(
        np.angle(np.exp(1j * (np.radians(raw_phase_diff_deg) - dispersion_predicted_diff_rad)))
    )

    cross_solver_report = {
        "l12_m": layout["l12_m"],
        "beta_rfx_real": np.real(beta_rfx).tolist(),
        "beta_openems_real": np.real(beta_openems).tolist(),
        "beta_ratio_rfx_over_openems": beta_ratio.tolist(),
        "raw_phase_diff_deg": raw_phase_diff_deg.tolist(),
        "residual_phase_diff_after_dispersion_deg": residual_after_dispersion_deg.tolist(),
        "s21_mag_rfx": np.abs(s21_rfx).tolist(),
        "s21_mag_openems": np.abs(s21).tolist(),
    }

    self_consistency_rfx_report = None
    try:
        self_consistency_rfx_report = _self_consistency_witness(
            freqs_hz, s21_rfx, beta_rfx, l12_m=layout["l12_m"],
            mag_band=B_S21_MAG_BAND, phase_tol_deg=B_PHASE_TOL_DEG,
            gd_tol_ps=B_GD_TOL_PS, label="stage_b_rfx_self_consistency",
        )
    except RuntimeError as exc:
        # rfx's own self-consistency is REPORTED alongside openEMS's (both
        # solvers' referral math is being demonstrated), but it must not
        # abort Stage B if the rfx side alone is out of band -- record the
        # failure text instead of raising, so the artifact still completes.
        self_consistency_rfx_report = {"passed": False, "error": str(exc)}

    phase21, gd21_s = np.unwrap(np.angle(s21)), None
    omega = 2.0 * np.pi * freqs_hz
    gd21_s = -np.gradient(phase21, omega)

    sanity_passed = bool(
        not truncated and passivity["passed"] and self_consistency_openems["passed"]
    )

    return {
        "freqs_hz": freqs_hz.tolist(),
        "s11": [[float(c.real), float(c.imag)] for c in s11],
        "s21": [[float(c.real), float(c.imag)] for c in s21],
        "s11_mag": np.abs(s11).tolist(), "s21_mag": np.abs(s21).tolist(),
        "s21_phase_rad_unwrapped": phase21.tolist(),
        "group_delay_ps": (gd21_s * 1e12).tolist(),
        "beta_port0": [[float(c.real), float(c.imag)] for c in beta_port0],
        "beta_port1": [[float(c.real), float(c.imag)] for c in beta_port1],
        "layout": layout,
        # NEW-1(b) fix (review 2026-08-04): the computed per-port
        # ref_plane_shift - measplane_shift (both predicted AND the REAL,
        # openEMS-measured value) so a reviewer sees the 0.000 directly
        # in the artifact rather than having to trust the docstring.
        "port_info": port_info,
        "passivity": passivity,
        "self_consistency_openems": self_consistency_openems,
        "self_consistency_rfx": self_consistency_rfx_report,
        "cross_solver_report": cross_solver_report,
        "max_uf_inc": inc_peak, "n_trace_samples": n_samples, "nrts_cap": nrts,
        "truncated_suspected": truncated, "elapsed_s": round(elapsed, 1),
        "end_criteria_not_reached": end_criteria_not_reached,
        "sanity_passed": sanity_passed,
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--output", default=".omx/msl-phase-referee/openems_msl_phase_referee.json")
    p.add_argument("--sim-root", default="/tmp/openems_msl_phase_referee")
    p.add_argument("--threads", type=int, default=16)
    p.add_argument("--nrts", type=int, default=300000, help="Stage B only")
    p.add_argument("--end-criteria", type=float, default=1e-4, help="Stage B only")
    p.add_argument("--rfx-fixture", default=RFX_FIXTURE_PATH)
    p.add_argument("--skip-stage-b", action="store_true")
    args = p.parse_args(argv)

    out_path = os.path.abspath(args.output)

    try:
        rfx_fixture = _load_rfx_fixture(args.rfx_fixture)
        _stage_b_layout(rfx_fixture)  # pure-arithmetic check FIRST, before openEMS
    except AssertionError as exc:
        print(f"CONFIG ERROR: Stage B layout assertion failed: {exc}", file=sys.stderr)
        return 3
    except FileNotFoundError as exc:
        print(f"CONFIG ERROR: {exc}", file=sys.stderr)
        return 3

    try:
        _import_openems()
    except ImportError as exc:
        print(f"SKIP: openEMS Python bindings not importable ({exc}).\n"
              "  This script is VESSL-only (source-built openEMS); see "
              "scripts/vessl_msl_phase_referee.yaml.", file=sys.stderr)
        return 2

    print("=" * 78)
    print("openEMS external referee -- rfx issue #490 lane 2 (MSL phase)")
    print("COMPARATOR LEG ONLY. Stage A = faithful MSL_NotchFilter.py port.")
    print("See module docstring for the full scope fence, delta list, convention note.")
    print("=" * 78)
    print(f"\nDeclared question:\n  {DECLARED_QUESTION}")

    t_start = time.time()
    sim_root = os.path.abspath(args.sim_root)

    try:
        print("\n--- Stage A: reproduce-gate (MSL_NotchFilter.py, faithful port) ---")
        stage_a = _run_stage_a_reproduce_gate(sim_root=sim_root, threads=args.threads)
        print(f"  f_notch: measured={stage_a['f_notch_hz']/1e9:.4f} GHz "
              f"expected={F_NOTCH_AN_HZ/1e9:.4f} GHz dev={stage_a['f_notch_dev_pct']:.2f}%")
        print(f"  Stage A passed: {stage_a['passed']}")

        stage_b = None
        if stage_a["passed"] and not args.skip_stage_b:
            print("\n--- Stage B: rfx-matched thru-line (ref_plane_shift referral) ---")
            stage_b = _run_stage_b(
                sim_root=sim_root, threads=args.threads, nrts=args.nrts,
                end_criteria=args.end_criteria, rfx_fixture=rfx_fixture,
            )
            print(f"  |S21| band: {min(stage_b['s21_mag']):.4f} - {max(stage_b['s21_mag']):.4f}")
            print(f"  openEMS self-consistency passed: {stage_b['self_consistency_openems']['passed']}")
            print(f"  rfx self-consistency (reported): "
                  f"{stage_b['self_consistency_rfx']['passed']}")
            print(f"  sanity_passed: {stage_b['sanity_passed']}")
        elif not stage_a["passed"]:
            print("\nStage A FAILED its reproduce-gate -- skipping Stage B "
                  "(external_solver_comparator.md: 'only then swap in the "
                  "target geometry').")
    except AssertionError as exc:
        print(f"\nCONFIG ERROR (internal script bug, not a physics finding): {exc}", file=sys.stderr)
        return 3
    except RuntimeError as exc:
        print(f"\nSELF-CHECK / PHYSICS-GATE FAILED: {exc}", file=sys.stderr)
        elapsed_total = time.time() - t_start
        artifact = {
            "issue": 490, "stage": "lane 2 (external openEMS referee)",
            "scope": "comparator leg only",
            "error": str(exc), "elapsed_s": round(elapsed_total, 1),
        }
        partial = getattr(exc, "partial_stage_b_data", None)
        if partial is not None:
            artifact["stage_b_partial"] = partial
        os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
        with open(out_path, "w") as f:
            json.dump(artifact, f, indent=2)
        return 1

    overall_passed = bool(
        stage_a["passed"] and (stage_b is None or stage_b["sanity_passed"])
    )

    elapsed_total = time.time() - t_start
    artifact = {
        "issue": 490, "stage": "lane 2 (external openEMS referee)",
        "scope": "comparator leg only -- brackets, does not judge rfx's own numbers",
        "declared_question": DECLARED_QUESTION,
        "must_move_when_validated": MUST_MOVE_WHEN_VALIDATED,
        "reproduce_gate_record": REPRODUCE_GATE_RECORD,
        "stage_a": stage_a, "stage_b": stage_b,
        "overall_passed": overall_passed, "elapsed_s": round(elapsed_total, 1),
    }

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(artifact, f, indent=2)
    print(f"\n=== Written to {out_path} ===")

    print("\n" + "=" * 78)
    print(f"overall_passed={overall_passed} (self-checks only -- NOT a "
          f"verdict on rfx vs openEMS phase agreement)")
    print("=" * 78)

    return 0 if overall_passed else 1


if __name__ == "__main__":
    sys.exit(main())
