"""WP 3-0 desk feasibility ladder for the gradient-vs-mesh study.

This is a CPU-only, no-simulation planning artifact. It reads rfx's own
shipped estimators (`Simulation.estimate_ad_memory`, issue #30/#39, and
`Grid.num_timesteps`) to size the reverse-mode AD memory of two canonical
geometries as the mesh is refined from dx = lambda/20 down to lambda/100
(lambda = c / freq_max in vacuum). It answers, on paper, "how far can the
GPU ladder of WP 3-1 be pushed before it runs out of VRAM?".

Geometries
----------
(a) WR-90 2-port rectangular waveguide: a = 22.86 mm, b = 10.16 mm,
    4 lambda long domain (120 mm) at a 10 GHz working frequency.
(b) Smooth dielectric-slab witness (the WP 3-1 geometry): a 60 x 12 x 12 mm
    box, CPML on the propagation axis, eps_r = 4 slab.

Method / honesty notes
----------------------
* n_steps is `Grid.num_timesteps(num_periods=20)` (num_periods held FIXED at
  20 on every rung, the settling-confound fence), then rounded UP to the
  nearest multiple of `checkpoint_segments` so the divisor constraint of
  `estimate_ad_memory(checkpoint_segments=...)` is met exactly.
* checkpoint_segments is chosen as round(sqrt(N)) -> the canonical
  O(sqrt(N)) balance; the reported `ckpt_sqrtN_gb` is the shipped
  `AD_MemoryEstimate.ad_segmented_gb` at that segment count.
* The shipped static accounting pads ALL THREE axes by 2*cpml_layers
  regardless of which faces are physically PEC. For the PEC-walled WR-90 this
  over-counts the transverse cell budget, so its numbers are CONSERVATIVE
  (biased high). `ad_segmented_gb` also counts only the per-segment carry
  snapshots, not the transient within-segment recompute tape (~segment_len
  field snapshots); both are documented limitations of the shipped estimate,
  which is labeled `evidence_class = "static_estimate"`, not a measured peak.
* VRAM verdict uses the estimator's own 85%-headroom convention against
  {24 GB RTX 4090, 48 GB A6000, 3x48 = 144 GB}.

Measured table (regenerated by running this file; freq_max = 10 GHz,
lambda = 29.98 mm, num_periods = 20; JSON beside this file is authoritative)
--------------------------------------------------------------------------
(a) WR-90 2-port (120 x 22.86 x 10.16 mm, cpml_layers = 16)
 dx       cells      n_steps  fwd GB  full-tape GB  ckpt sqrtN GB  verdict
 l/20    2.234e+05     702     0.0139     3.78          0.293      fits-4090
 l/40    5.836e+05    1406     0.0364    19.73          1.073      fits-4090
 l/60    1.169e+06    2116     0.0729    59.43          2.654      fits-4090
 l/80    2.051e+06    2809     0.1280   138.43          5.347      fits-4090
 l/100   3.199e+06    3540     0.1996   271.95          9.258      fits-4090

(b) Smooth slab witness (60 x 12 x 12 mm, cpml_layers = 8)
 dx       cells      n_steps  fwd GB  full-tape GB  ckpt sqrtN GB  verdict
 l/20    3.921e+04     702     0.0024     0.66          0.051      fits-4090
 l/40    1.133e+05    1406     0.0071     3.83          0.208      fits-4090
 l/60    2.434e+05    2116     0.0152    12.38          0.553      fits-4090
 l/80    4.450e+05    2809     0.0278    30.03          1.160      fits-4090
 l/100   7.334e+05    3540     0.0458    62.35          2.123      fits-4090

3-0 verdict (falsifier did NOT trigger)
---------------------------------------
The GPU ladder does NOT die at lambda/100 on MEMORY for either canonical
geometry once the tape is O(sqrt(N))-checkpointed: the smallest sensible
domain (smooth slab) needs 2.12 GB at lambda/100, and even the WR-90 2-port
needs only 9.26 GB -- both fit a single 24 GB RTX 4090 (and remain under
24 GB with the ~segment_len within-segment recompute term the shipped model
omits: WR-90 l/100 ~ 9.3 + 4.6 = ~14 GB). The reason the falsifier expected a
wall but none appears: both canonical geometries are electrically THIN in the
transverse plane (single-mode WR-90; a small slab box), so the cell count
grows only ~14x over the 5x dx refinement -- the fixed 2*cpml_layers padding
dominates the coarse rungs -- rather than the dx^-3 a bulk-3D domain would
show.

Where the dx^-4 cost DOES appear: the UNCHECKPOINTED full-tape column, which
climbs 3.78 -> 271.95 GB for WR-90 (l/20 -> l/100) and would OOM every listed
GPU without checkpointing. So on these geometries the binding fine-mesh
constraint is COMPUTE TIME (dt proportional to dx => n_steps, times cells),
not checkpointed memory. The practical consequence for WP 3-1: the smooth-
slab witness is comfortably single-GPU across the whole ladder, so its CPU
rungs are representative of the real memory regime rather than a toy that
would blow up on hardware.

Run
---
    python scripts/diagnostics/gradient_dx_ladder/desk_feasibility.py

Writes desk_feasibility.json beside this file.
"""

from __future__ import annotations

import json
import math
import os

from rfx.api import Simulation
from rfx.grid import Grid

C0 = 2.998e8
FREQ_MAX = 10e9
NUM_PERIODS = 20.0
RUNGS = (20, 40, 60, 80, 100)

# VRAM budgets (GB) and the estimator's 85%-headroom convention.
VRAM = {"rtx4090_24": 24.0, "a6000_48": 48.0, "a6000_3x_144": 144.0}
HEADROOM = 0.85

GEOMETRIES = {
    "wr90_2port": {
        "label": "WR-90 2-port (120 x 22.86 x 10.16 mm)",
        "domain": (0.120, 0.02286, 0.01016),
        "cpml_layers": 16,
    },
    "smooth_slab": {
        "label": "Smooth dielectric-slab witness (60 x 12 x 12 mm)",
        "domain": (0.060, 0.012, 0.012),
        "cpml_layers": 8,
    },
}


def _cells(domain, dx, cpml_layers):
    """Replicate the shipped `_ad_memory_static_accounting` cell formula."""
    def nx(extent):
        return int(math.ceil(extent / dx)) + 1 + 2 * cpml_layers
    a, b, c = (nx(domain[0]), nx(domain[1]), nx(domain[2]))
    return a, b, c, a * b * c


def _sqrtn_segments(n_steps_raw):
    """Choose checkpoint_segments ~ sqrt(N) and round n_steps up to divide."""
    segs = max(1, round(math.sqrt(n_steps_raw)))
    segment_len = math.ceil(n_steps_raw / segs)
    n_steps = segs * segment_len
    return segs, segment_len, n_steps


def _verdict(ckpt_gb):
    for key in ("rtx4090_24", "a6000_48", "a6000_3x_144"):
        if ckpt_gb <= VRAM[key] * HEADROOM:
            return {
                "rtx4090_24": "fits-4090",
                "a6000_48": "needs-A6000",
                "a6000_3x_144": "needs-3xA6000",
            }[key]
    return "infeasible (>144 GB*0.85)"


def build_rows():
    lam = C0 / FREQ_MAX
    out = {"meta": {"freq_max_hz": FREQ_MAX, "lambda_m": lam,
                    "num_periods": NUM_PERIODS, "vram_gb": VRAM,
                    "headroom": HEADROOM,
                    "evidence_class": "static_estimate"},
           "geometries": {}}
    for gkey, g in GEOMETRIES.items():
        rows = []
        for n in RUNGS:
            dx = lam / n
            grid = Grid(FREQ_MAX, g["domain"], dx=dx,
                        cpml_layers=g["cpml_layers"])
            n_raw = grid.num_timesteps(num_periods=NUM_PERIODS)
            segs, seg_len, n_steps = _sqrtn_segments(n_raw)
            nx, ny, nz, cells = _cells(g["domain"], dx, g["cpml_layers"])
            sim = Simulation(FREQ_MAX, g["domain"], boundary="cpml",
                             cpml_layers=g["cpml_layers"], dx=dx)
            est = sim.estimate_ad_memory(n_steps, checkpoint_segments=segs)
            rows.append({
                "rung": f"lambda/{n}", "lambda_over_dx": n, "dx_m": dx,
                "nx": nx, "ny": ny, "nz": nz, "cells": cells,
                "n_steps_raw": n_raw, "n_steps": n_steps,
                "checkpoint_segments": segs, "segment_len": seg_len,
                "forward_gb": est.forward_gb,
                "full_tape_gb": est.ad_full_gb,
                "ckpt_sqrtN_gb": est.ad_segmented_gb,
                "verdict": _verdict(est.ad_segmented_gb),
            })
        out["geometries"][gkey] = {"label": g["label"],
                                   "domain_m": g["domain"],
                                   "cpml_layers": g["cpml_layers"],
                                   "rows": rows}
    return out


def _print(out):
    print("=" * 78)
    print("WP 3-0 desk feasibility ladder (shipped estimators; static_estimate)")
    print(f"freq_max = {FREQ_MAX/1e9:.1f} GHz, lambda = "
          f"{out['meta']['lambda_m']*1e3:.2f} mm, num_periods = "
          f"{int(NUM_PERIODS)}")
    print("=" * 78)
    for gkey, g in out["geometries"].items():
        print(f"\n({gkey})  {g['label']}, cpml_layers = {g['cpml_layers']}")
        print(f"  {'dx':>7} {'cells':>12} {'n_steps':>8} {'fwd GB':>9} "
              f"{'full GB':>11} {'ckpt GB':>10}  verdict")
        for r in g["rows"]:
            print(f"  {r['rung']:>7} {r['cells']:12.3e} {r['n_steps']:8d} "
                  f"{r['forward_gb']:9.4f} {r['full_tape_gb']:11.2f} "
                  f"{r['ckpt_sqrtN_gb']:10.3f}  {r['verdict']}")
    # Falsifier check on the smallest sensible domain (smooth slab).
    slab_l100 = out["geometries"]["smooth_slab"]["rows"][-1]["ckpt_sqrtN_gb"]
    dies = slab_l100 > VRAM["a6000_3x_144"] * HEADROOM
    print("\n3-0 falsifier (checkpointed lambda/100, smallest domain "
          f"= smooth slab): {slab_l100:.3f} GB "
          f"-> GPU ladder {'DIES' if dies else 'SURVIVES'} on 144 GB*0.85.")


def main():
    out = build_rows()
    _print(out)
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "desk_feasibility.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nWrote {path}")


if __name__ == "__main__":
    main()
