#!/usr/bin/env python3
"""CI gate: a pull request carries code, tests and the frozen data a test reads.

The repository is public and its history keeps whatever lands. Measurement
records -- sweep and study JSON, harvested VESSL logs, the measurement of an
option that was not adopted -- go to ``bk-squared/rfx-archive`` under
``rfx/records/<YYYYMMDD>-<topic>/``, and the PR body names that path and the
archive commit (PI, 2026-09-24). Over the 14 days to 2026-09-24, ``rfx/``
changed by +39,849/-37,028 lines on main while JSON alone changed by 3.78
million, and a reviewer cannot read a diff of that shape.

Four rules over the PR's diff against its merge base, all mechanical:

1. Data files added or modified OUTSIDE ``ALLOWLIST`` may add at most
   ``LINE_BUDGET`` lines in total, and binary ones at most ``BINARY_BUDGET``
   bytes. Deletions are free: moving records out is the point.
2. No data file the PR adds or modifies may exceed ``FILE_CAP`` bytes, on the
   allowlist or off it, except a file in a frozen-data home that a reader names
   (rule 3's test), which may reach ``FROZEN_FILE_CAP``. Four fixtures tests
   read, added 2026-09-10..24, were 1.04-1.81 MB; at one cap for everything
   they would have needed the exception label, and a label needed for routine
   work stops meaning anything. ``SIZE_EXEMPT`` names the one exception.
3. A data file newly placed in a frozen-data home -- ``tests/fixtures/``,
   ``tests/data/``, ``tests/crossval/<case>/reference/`` -- must be named by a
   tracked non-data file under ``tests/`` or ``rfx/``: by its file name, by
   its name without extensions (``f"{case}.json"`` readers), or, when it sits
   in a subdirectory of its home, by that subdirectory's name (glob readers).
   The allowlist lets those homes grow past the budget; this is what keeps a
   record from being parked there.
4. A PR labelled ``data-budget-exception`` passes whatever it carries, with a
   warning annotation and the would-be failures in the step summary. The
   weekly ``scripts/ci/governance_audit.py`` lists every merged PR that
   carried the label.

What a "data file" is: ``DATA_SUFFIXES`` by the last suffix, Touchstone
``.sNp``, and the names in ``DATA_NAMES``. Git decides text or binary (numstat
``-``), not the suffix.

Inputs: ``--base``/``--head`` shas (the workflow passes the pull request's
``base.sha`` and ``head.sha``) and ``PR_LABELS_JSON``, the PR's labels as a
JSON array, which the workflow reads from the API at run time so that a label
applied after the push counts on a re-run. With no ``--base`` on a push event
there is nothing to compare and the check says so. Stdlib only.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path, PurePosixPath
from typing import Dict, FrozenSet, Iterable, List, NamedTuple, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]
_CHANGELOG_CHECK = REPO_ROOT / "scripts" / "ci" / "check_changelog_fragment.py"

LINE_BUDGET = 500
BINARY_BUDGET = 200_000  # bytes
FILE_CAP = 1_000_000  # bytes
FROZEN_FILE_CAP = 5_000_000  # bytes, a named file in a frozen-data home
EXCEPTION_LABEL = "data-budget-exception"
ARCHIVE_REPO = "bk-squared/rfx-archive"
ARCHIVE_PATH = "rfx/records/<YYYYMMDD>-<topic>/"

#: The formats the PI's rule names, plus the ones measured in the tree or in
#: the 222 PRs merged 2026-09-10..24 (``.gz`` VESSL log bundles, ``.xml``
#: pytest reports, ``.started``/``.exit`` run markers, ``.msh`` meshes), plus
#: other spellings of the same formats.
DATA_SUFFIXES = frozenset({
    ".json", ".jsonl", ".ndjson", ".csv", ".tsv", ".log", ".txt", ".out",
    ".rc", ".exit", ".started", ".dat", ".xml", ".msh",
    ".npz", ".npy", ".h5", ".hdf5", ".pkl", ".pickle", ".mat",
    ".gz", ".bz2", ".xz", ".zip", ".tar",
})
TOUCHSTONE_RE = re.compile(r"\.s\d+p\Z")
#: Data by content, with no data suffix. pytest-split's JSON file.
DATA_NAMES = frozenset({".test_durations"})

#: Data paths that change as part of ordinary code work, and the evidence:
#: PRs among the 222 merged 2026-09-10..24 that touched the path, and the
#: lines they added. Nothing else changed a data path in more than two PRs
#: except records under validation/, scripts/diagnostics/ and docs/.
ALLOWLIST: Tuple[Tuple[str, str], ...] = (
    (".test_durations", "pytest-split durations, regenerated by hand (3 PRs, 18,559 lines)"),
    ("docs/guides/api_symbol_inventory.json", "regenerated API inventory (20 PRs, 160 lines)"),
    ("docs/guides/*support_matrix*.json", "support matrices (14 PRs, 49 lines)"),
    ("validation/crossval/manifest.json", "cross-validation manifest (22 PRs, 170 lines)"),
    ("docs/design_notes/schemas/*.schema.json", "design IR schema tests/interop reads (5 PRs, 161 lines)"),
    ("docs/public/site_map.json", "public docs map scripts/check_public_docs_manifest.py reads (1 PR, 1 line)"),
    ("docs/public/gallery/assets/**", "gallery precompute outputs (1 PR, 1 line)"),
    ("scripts/ops/gpu_suite_shards.json", "rendered GPU shard list (2 PRs, 1 line)"),
    ("tests/contracts/boundary_registry.json", "registry tests/contracts reads (1 PR, 1,041 lines)"),
    ("tests/fixtures/**", "frozen reference data, rule 3 applies (34 PRs, 324,083 lines)"),
    ("tests/data/**", "frozen snapshots, rule 3 applies (34 PRs, 8,094 lines)"),
    ("tests/crossval/*/reference/**", "frozen external-solver data, rule 3 applies (5 PRs, 117,199 lines)"),
)

#: Where frozen reference data lives, and the home root of each path.
FROZEN_HOME_RE = re.compile(
    r"(?P<home>tests/fixtures/|tests/data/|tests/crossval/[^/]+/reference/)(?P<rest>.+)\Z"
)

#: Files the size cap does not apply to, with the reason.
SIZE_EXEMPT = {
    ".test_durations": "1.14 MB; pytest-split reads the whole suite's durations from one file",
}

#: Where the referencing files for rule 3 are looked for.
READER_ROOTS = ("tests", "rfx")


def _load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# Imported, not reimplemented: both gates read PR_LABELS_JSON the same way.
parse_labels = _load(_CHANGELOG_CHECK, "rfx_check_changelog_fragment").parse_labels


def _glob_regex(pattern: str) -> "re.Pattern[str]":
    """``**`` crosses directories, ``*`` does not. Anchored at both ends."""
    out: List[str] = []
    index = 0
    while index < len(pattern):
        if pattern.startswith("**", index):
            out.append(".*")
            index += 2
        elif pattern[index] == "*":
            out.append("[^/]*")
            index += 1
        else:
            out.append(re.escape(pattern[index]))
            index += 1
    return re.compile("".join(out) + r"\Z")


_ALLOW_RES = tuple(_glob_regex(pattern) for pattern, _ in ALLOWLIST)


def is_data(path: str) -> bool:
    name = PurePosixPath(path).name
    if name in DATA_NAMES:
        return True
    suffix = PurePosixPath(name).suffix.lower()
    return suffix in DATA_SUFFIXES or TOUCHSTONE_RE.search(suffix) is not None


def allowlisted(path: str) -> bool:
    return any(regex.match(path) for regex in _ALLOW_RES)


class Change(NamedTuple):
    """One data file the PR adds or modifies."""

    path: str
    status: str  # A, M, R or C (the destination of a rename or copy)
    added: Optional[int]  # None when git calls it binary
    size: int  # bytes at head


class Findings(NamedTuple):
    changes: List[Change]
    outside_lines: List[Change]  # text data outside the allowlist that adds lines
    outside_binary: List[Change]  # binary data outside the allowlist
    over_cap: List[Change]
    unreferenced: List[Change]
    new_frozen: List[Change]
    named: FrozenSet[str]  # frozen-data paths a reader names, among those asked about

    @property
    def line_total(self) -> int:
        return sum(change.added or 0 for change in self.outside_lines)

    @property
    def binary_total(self) -> int:
        return sum(change.size for change in self.outside_binary)


def _git(repo: Path, *args: str) -> bytes:
    return subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, check=True
    ).stdout


def _split_z(raw: bytes) -> List[str]:
    return raw.decode("utf-8", "surrogateescape").split("\0")


def _statuses(base: str, head: str, repo: Path) -> Dict[str, str]:
    """Post-image path -> A/M/R/C/T for everything present at head."""
    tokens = _split_z(_git(repo, "diff", "--name-status", "-z", "--find-renames",
                           f"{base}...{head}"))
    out: Dict[str, str] = {}
    index = 0
    while index < len(tokens):
        status = tokens[index]
        if not status:
            index += 1
            continue
        if status[0] in "RC":
            out[tokens[index + 2]] = status[0]
            index += 3
        else:
            if status[0] != "D":
                out[tokens[index + 1]] = status[0]
            index += 2
    return out


def _added_lines(base: str, head: str, repo: Path) -> Dict[str, Optional[int]]:
    """Post-image path -> lines added, or None for a binary file."""
    tokens = _split_z(_git(repo, "diff", "--numstat", "-z", "--find-renames",
                           f"{base}...{head}"))
    out: Dict[str, Optional[int]] = {}
    index = 0
    while index < len(tokens):
        record = tokens[index]
        if not record:
            index += 1
            continue
        added, _deleted, path = record.split("\t", 2)
        if path:
            index += 1
        else:  # a rename: "added\tdeleted\t\0old\0new\0"
            path = tokens[index + 2]
            index += 3
        out[path] = None if added == "-" else int(added)
    return out


def _sizes(head: str, repo: Path) -> Dict[str, int]:
    """Blob size in bytes of every file at head."""
    out: Dict[str, int] = {}
    for record in _split_z(_git(repo, "ls-tree", "-r", "-l", "-z", head)):
        if not record:
            continue
        meta, path = record.split("\t", 1)
        size = meta.split()[3]
        if size != "-":
            out[path] = int(size)
    return out


def reader_text(head: str, repo: Path) -> str:
    """Every tracked non-data file under ``READER_ROOTS`` at head, joined."""
    oids: List[str] = []
    for record in _split_z(_git(repo, "ls-tree", "-r", "-z", head, "--", *READER_ROOTS)):
        if not record:
            continue
        meta, path = record.split("\t", 1)
        _mode, kind, oid = meta.split()
        if kind == "blob" and not is_data(path):
            oids.append(oid)
    if not oids:
        return ""
    raw = subprocess.run(
        ["git", "cat-file", "--batch"], cwd=repo, input="\n".join(oids).encode() + b"\n",
        capture_output=True, check=True,
    ).stdout
    parts: List[str] = []
    offset = 0
    while offset < len(raw):
        header_end = raw.index(b"\n", offset)
        size = int(raw[offset:header_end].split()[2])
        start = header_end + 1
        parts.append(raw[start:start + size].decode("utf-8", "replace"))
        offset = start + size + 1
    return "\n\0\n".join(parts)


def _data_stem(name: str) -> str:
    """*name* without its trailing data suffixes: ``a.json.gz`` -> ``a``.

    Only data suffixes come off, so ``0.01_16.json`` keeps ``0.01_16`` rather
    than collapsing to ``0``, which every file in the repository names.
    """
    stem = name
    while "." in stem.lstrip(".") and is_data(stem):
        stem = stem[:stem.rindex(".")]
    return stem


def _distinctive(token: str) -> bool:
    """A shorter name can vouch for a file only if it could name one thing."""
    return len(token) >= 3 and any(char.isalpha() for char in token)


def reference_tokens(path: str) -> List[str]:
    """The names a reader may use for a frozen-data file (rule 3)."""
    match = FROZEN_HOME_RE.match(path)
    rest = PurePosixPath(match.group("rest") if match else path)
    tokens = [rest.name]
    stem = _data_stem(rest.name)
    if stem != rest.name and _distinctive(stem):
        tokens.append(stem)
    if match and len(rest.parts) > 1 and _distinctive(rest.parent.name):
        tokens.append(rest.parent.name)
    return tokens


def _name_char(char: str) -> bool:
    return char.isalnum() or char in "_-"


def is_named(token: str, text: str) -> bool:
    """*token* appears in *text* and is not part of a longer name.

    ``str.find`` rather than a regex: the reader text is about 15 MB, and a
    regex scan per token cost 0.3 s where this costs milliseconds.
    """
    start = text.find(token)
    while start != -1:
        end = start + len(token)
        before = text[start - 1] if start else ""
        after = text[end] if end < len(text) else ""
        if not (before and (_name_char(before) or before == ".")) and not (
            after and _name_char(after)
        ):
            return True
        start = text.find(token, start + 1)
    return False


def size_cap(path: str, named: FrozenSet[str]) -> int:
    """The largest a data file at *path* may be (rule 2)."""
    if FROZEN_HOME_RE.match(path) and path in named:
        return FROZEN_FILE_CAP
    return FILE_CAP


def evaluate(base: str, head: str, repo: Path) -> Findings:
    """What the PR's data changes are, sorted into the four rules' buckets."""
    statuses = _statuses(base, head, repo)
    added = _added_lines(base, head, repo)
    sizes = _sizes(head, repo)

    changes = [
        Change(path, status, added.get(path), sizes.get(path, 0))
        for path, status in sorted(statuses.items())
        if is_data(path) and path in sizes
    ]
    outside = [change for change in changes if not allowlisted(change.path)]
    outside_lines = [c for c in outside if c.added]
    outside_binary = [c for c in outside if c.added is None]
    new_frozen = [
        change for change in changes
        if change.status in ("A", "R", "C") and FROZEN_HOME_RE.match(change.path)
    ]
    # A reader is looked for on every new frozen file (rule 3) and on every
    # frozen file over FILE_CAP, new or edited (rule 2's larger cap).
    asked = new_frozen + [
        change for change in changes
        if change.size > FILE_CAP and FROZEN_HOME_RE.match(change.path)
        and change not in new_frozen
    ]
    named: FrozenSet[str] = frozenset()
    if asked:
        text = reader_text(head, repo)
        named = frozenset(
            change.path for change in asked
            if any(is_named(token, text) for token in reference_tokens(change.path))
        )
    unreferenced = [change for change in new_frozen if change.path not in named]
    over_cap = [
        change for change in changes
        if change.path not in SIZE_EXEMPT and change.size > size_cap(change.path, named)
    ]
    return Findings(changes, outside_lines, outside_binary, over_cap, unreferenced,
                    new_frozen, named)


def _listing(changes: Iterable[Change], value, unit: str, limit: int = 15) -> List[str]:
    rows = sorted(changes, key=lambda change: -value(change))
    lines = [f"      {value(change):>10,} {unit}  {change.path}" for change in rows[:limit]]
    if len(rows) > limit:
        rest = rows[limit:]
        lines.append(f"      ... and {len(rest)} more files, "
                     f"{sum(value(change) for change in rest):,} {unit}")
    return lines


def failures(findings: Findings) -> List[str]:
    """Return the failure messages; empty means the PR passes."""
    out: List[str] = []
    if findings.line_total > LINE_BUDGET:
        out.append("\n".join([
            f"data files outside the allowlist add {findings.line_total:,} lines "
            f"(budget {LINE_BUDGET}):",
            *_listing(findings.outside_lines, lambda change: change.added or 0, "lines"),
        ]))
    if findings.binary_total > BINARY_BUDGET:
        out.append("\n".join([
            f"binary data files outside the allowlist hold {findings.binary_total:,} "
            f"bytes (budget {BINARY_BUDGET:,}):",
            *_listing(findings.outside_binary, lambda change: change.size, "bytes"),
        ]))
    if findings.over_cap:
        out.append("\n".join([
            f"{len(findings.over_cap)} data file(s) over their size cap ({FILE_CAP:,} "
            f"bytes; {FROZEN_FILE_CAP:,} for a file in a frozen-data home that a "
            f"reader names):",
            *[f"      {change.size:>10,} bytes (cap "
              f"{size_cap(change.path, findings.named):,})  {change.path}"
              for change in sorted(findings.over_cap, key=lambda c: -c.size)[:15]],
            *([f"      ... and {len(findings.over_cap) - 15} more"]
              if len(findings.over_cap) > 15 else []),
        ]))
    if findings.unreferenced:
        out.append("\n".join([
            f"{len(findings.unreferenced)} new frozen-data file(s) that no tracked "
            f"file under {' or '.join(root + '/' for root in READER_ROOTS)} names "
            f"(by file name, name without extensions, or subdirectory):",
            *[f"      {change.path}" for change in findings.unreferenced[:15]],
            *([f"      ... and {len(findings.unreferenced) - 15} more"]
              if len(findings.unreferenced) > 15 else []),
        ]))
    return out


WHERE_IT_GOES = f"""\
Where the data goes:
  Measurement records -- sweep and study JSON, harvested VESSL logs, the
  measurement of an option that was not adopted -- go to
  {ARCHIVE_REPO} under {ARCHIVE_PATH}.
  Name that path and the archive commit in the PR body.
  Frozen reference data a test reads goes under tests/fixtures/,
  tests/data/ or tests/crossval/<case>/reference/, named by the test that
  reads it, and no one file over {FROZEN_FILE_CAP:,} bytes there
  ({FILE_CAP:,} anywhere else).
  If this PR has to carry the data anyway, apply the label
  '{EXCEPTION_LABEL}' and re-run the failed job (no push needed: the
  labels are read when the job runs). The weekly governance audit lists
  every merged PR that carried the label."""


def _summary(text: str) -> None:
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if path:
        with open(path, "a", encoding="utf-8") as handle:
            handle.write(text + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--base", default="", help="pull request base sha")
    parser.add_argument("--head", default="", help="pull request head sha")
    parser.add_argument("--repo", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)

    if not args.base or not args.head:
        event = os.environ.get("GITHUB_EVENT_NAME", "")
        if event and event != "pull_request":
            print(f"data budget: a {event} event has no pull request to measure; "
                  f"nothing to check.")
            return 0
        print("data budget check failed: --base and --head are both required",
              file=sys.stderr)
        return 1
    try:
        labels = parse_labels(os.environ.get("PR_LABELS_JSON", ""))
    except ValueError as exc:
        print(f"data budget check failed: {exc}", file=sys.stderr)
        return 1
    try:
        findings = evaluate(args.base, args.head, args.repo)
    except subprocess.CalledProcessError:
        print(f"data budget check failed: cannot diff {args.base}...{args.head} in "
              f"{args.repo}. Both commits must be present -- check out with "
              f"fetch-depth: 0.", file=sys.stderr)
        return 1

    found = failures(findings)
    if found and EXCEPTION_LABEL in labels:
        notice = (f"This PR carries the '{EXCEPTION_LABEL}' label, so the data "
                  f"budget was NOT enforced. Without the label it would fail:")
        print(f"::warning title=data budget not enforced::{notice} "
              f"{len(found)} rule(s); see the step summary.")
        print(notice)
        for failure in found:
            print(f"- {failure}")
        _summary("\n".join([
            "## Data budget NOT enforced: `" + EXCEPTION_LABEL + "`",
            "",
            notice,
            "",
            "```",
            *[f"- {failure}" for failure in found],
            "```",
        ]))
        return 0
    if found:
        print("data budget check failed:", file=sys.stderr)
        for failure in found:
            print(f"- {failure}", file=sys.stderr)
        print(WHERE_IT_GOES, file=sys.stderr)
        _summary("\n".join([
            "## Data budget failed", "", "```",
            *[f"- {failure}" for failure in found],
            "", WHERE_IT_GOES, "```",
        ]))
        return 1
    print(f"data budget ok: {findings.line_total:,} lines of data outside the "
          f"allowlist (budget {LINE_BUDGET}), {findings.binary_total:,} bytes "
          f"binary (budget {BINARY_BUDGET:,}), {len(findings.new_frozen)} new "
          f"frozen-data file(s), each named by a reader")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
