"""Replay of the W7 accuracy + autodiff witness on band-builder meshes
(``validation/research/multiband_nu/w7_accuracy_ad.py``), pre-declared in
``docs/design_notes/20260907_nu_band_accuracy_ad_predeclaration.md``.

Written and committed BEFORE the instrument's first measurement run; the
windows below are the note's section 3 numbers verbatim and are never
widened here. Two kinds of test live in this file:

* **JSON-free** (always run): the frozen windows are pinned against the
  instrument's constants; the transfer-matrix oracle passes its two
  self-checks (i)/(i') (closed forms to 1e-12 relative); and one fast
  LIVE autodiff test — AD1 on the A1 MB s = 2 vector with ``N_STEPS = 40``,
  finite gradient, the two largest non-tied cells within 15 % of central
  FD (about 10 s).
* **Replay** (skipped cleanly while ``results/w7_accuracy_ad.json`` is
  absent): every declared vector is regenerated by the builder on this tree
  and compared cell for cell (1e-12 m) with the JSON; every model frequency
  is recomputed from the JSON's own profiles and eps columns (1e-9
  relative); every frozen rule of note section 3 is re-evaluated from the
  JSON's measured numbers through the instrument's own judges and must
  agree with the verdict the JSON carries; the section 1a interface-
  assignment table and the ``e_samp`` first-order law on the UC production
  ladder (order 1.06 to 0.1) are pinned; the AD5 tie table must be present.

A rule that FIRED in the committed JSON turns its replay test red here by
design — the committed cavity oracles behave the same way — and the answer
to that red is a PI decision recorded in the note, never a tolerance edit
in this file. Units the instrument marked INCONCLUSIVE (extraction-limited)
are skipped, as the note prescribes, not counted either way.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pytest
import jax
import jax.numpy as jnp

from validation.research.multiband_nu import w7_accuracy_ad as w7

_REPO = pathlib.Path(__file__).resolve().parents[3]
_JSON = _REPO / "validation/research/multiband_nu/results/w7_accuracy_ad.json"

CELL_TOL = 1e-12          # m, I1/I3
MODEL_REL = 1e-9          # recomputed model frequencies vs the JSON
JUDGE_REL = 1e-9          # re-evaluated fit quantities vs the JSON's judge
E_SAMP_ORDER = 1.06       # note 1b, UC production ladder
E_SAMP_ORDER_TOL = 0.1
LIVE_AD_N_STEPS = 40
LIVE_AD_TOL = 0.15

# --- the frozen windows, verbatim from the note (section 3) ------------------
FROZEN = {
    "ORACLE_REL": 1e-12, "SELFCHECK_REL": 1e-7,
    "G1_Z_FRACTION_MIN": 0.80, "G2_GRADING_SHARE_MIN": 0.20, "G3_MODEL_RESIDUAL_HZ": 0.15e6,
    "P_UC_WINDOW": (1.8, 2.2), "P_MB_MIN": 1.8, "P_MB_ANOMALY": 2.4, "RHO_MAX": 2.0,
    "E_FLOOR_HZ": 0.3e6, "INVARIANCE_HZ": 0.1e6, "T_TOTAL": 15e-9, "T_TRUNC": 10e-9,
    "MATCH_GUARD": 0.03, "H1": 0.5e-3,
    "A2_ERR_MAX": 0.10e-2, "A2_DIFF_MAX": 0.05e-2, "A2_INV_MAX": 0.017e-2,
    "A3_ERR_MAX": 0.20e-2, "A3_DIFF_MAX": 0.10e-2, "A3_INV_MAX": 0.033e-2,
    "A2_N_STEPS": (8000, 12000), "A3_N_STEPS": (8000, 12000), "A2_CAPS": (1.3, 1.4), "A3_CAP": 1.4,
    "FD_REL_H": 1e-3, "DOMINANT_FRAC": 0.05, "AD1_TOL": 0.15, "AD2_TOL": 0.05, "AD2_H": 0.015,
    "AD3_TOL": 0.15, "AD_N_STEPS": 120, "AD4_SEED": 20260907, "AD4_N_STACKS": 20, "AD4_N_STEPS": 20,
    "F_TRUE_DECLARED": 10_561_719_600.896, "A1_SCALES": (0.5, 1.0, 2.0), "R_CAP": 1.4,
    "A1_A_X": 30e-3, "A1_B_Y": 3e-3, "DF0": 0.5e-3, "DC0": 0.7e-3, "DXY0": 0.25e-3,
}


@pytest.fixture(scope="module")
def w7_json() -> dict:
    if not _JSON.exists():
        pytest.skip(f"{_JSON.name} not present yet — the W7 arms have not been run on this tree")
    with open(_JSON) as fh:
        return json.load(fh)


def _rel_close(x, y, rel):
    return abs(x - y) <= rel * max(abs(x), abs(y), 1e-300)


def _real(units: dict) -> dict:
    return {k: r for k, r in units.items() if not r.get("smoke")}


# =============================================================================
# JSON-free
# =============================================================================

def test_frozen_windows_pinned_verbatim():
    for name, value in FROZEN.items():
        got = getattr(w7, name)
        if isinstance(value, tuple):
            assert tuple(got) == value, (name, got, value)
        else:
            assert got == value, (name, got, value)
    assert w7.A1_EDGES == [0.0, 14e-3, 16e-3, 30e-3, 44e-3]
    assert w7.A1_EPS == [4.3, 3.0, 4.3, 1.0]
    assert (w7.A1_M_X, w7.A1_P_Z) == (1, 5)
    assert (w7.Z_SRC, w7.Z_PRB) == (16e-3, 30e-3)
    assert w7.A2_X_EDGES == [0.0, 10e-3, 12e-3, 26e-3, 28e-3, 40e-3]
    assert w7.A2_Y_EDGES == [0.0, 8e-3, 10e-3, 22e-3, 24e-3, 34e-3]
    assert w7.A3_EDGES == {"x": [0.0, 19e-3, 21e-3, 40e-3], "y": [0.0, 16.5e-3, 18.5e-3, 35e-3],
                           "z": [0.0, 17e-3, 19e-3, 36e-3]}


def test_oracle_self_checks_i_and_ip():
    sc = w7.oracle_selfcheck()
    assert sc["i_pass"] and sc["i_worst_rel"] <= w7.ORACLE_REL, sc["i_worst_rel"]
    assert sc["ip_pass"] and sc["ip_worst_rel"] <= w7.ORACLE_REL, sc["ip_worst_rel"]
    # second pass: the Hy / LSM determinant reproduces the closed form too, and
    # the non-excited families are tabulated (the isolation of note 2.1 is
    # conditional on source symmetry and polarisation — reviewer finding)
    assert sc["ipp_pass"] and sc["ipp_worst_rel"] <= w7.ORACLE_REL, sc["ipp_worst_rel"]
    of = sc["other_families"]
    assert of["nearest_any_family"] is not None
    assert abs(of["nearest_any_family"]["rel_to_f_true"]) < 0.01           # an unexcited mode within 1 %
    assert of["max_source_pair_amplitude_suppressed"] <= 1e-12             # sin(m pi/3) + sin(2m pi/3) = 0
    assert sc["i_roots_by_case"]["a=60mm,m=5"] >= 1      # m = 5 is exercised, not vacuous
    assert sc["f_true_matches_declared"], sc["f_true_hz"]
    assert sc["p_matches_declared"] and sc["neighbours_match_declared"]
    assert sc["isolation_matches_declared"], sc["isolation"]


def test_declared_builder_vectors_regenerate_on_this_tree():
    for s in w7.A1_SCALES:
        mb, dec = w7.a1_mb(s), w7.a1_mb_declared(s)
        assert len(mb) == len(dec) and np.max(np.abs(mb - dec)) <= CELL_TOL, s
        for prof in (mb, w7.a1_uc(s), w7.a1_az(s)):
            nodes = np.concatenate([[0.0], np.cumsum(prof)])
            assert min(abs(nodes - w7.Z_SRC)) <= CELL_TOL and min(abs(nodes - w7.Z_PRB)) <= CELL_TOL
    for cap in w7.A2_CAPS:
        px, py, _ = w7.a2_profiles(cap)
        for p, edges, ax in ((px, w7.A2_X_EDGES, "x"), (py, w7.A2_Y_EDGES, "y")):
            rep = w7.profile_report(p, edges)
            assert rep["n"] == w7.A2_PROFILE_N[(f"{cap}", ax)]
            assert abs(rep["max_ratio"] - w7.A2_PROFILE_MAXR[(f"{cap}", ax)]) <= 1e-6
            assert rep["interface_err_m"] <= CELL_TOL and rep["max_ratio"] <= cap + 1e-9
    px, py, pz = w7.a3_profiles()
    for ax, p in (("x", px), ("y", py), ("z", pz)):
        rep = w7.profile_report(p, w7.A3_EDGES[ax])
        assert rep["n"] == w7.A3_PROFILE_N[ax]
        assert abs(rep["max_ratio"] - w7.A3_PROFILE_MAXR[ax]) <= 1e-6
        assert rep["interface_err_m"] <= CELL_TOL


def test_live_ad1_fast_profile_gradient():
    """AD1 on the s = 2 MB vector, N_STEPS = 40: finite gradient; the two
    largest non-tied cells agree with central FD to 15 % with sign."""
    dz0 = w7.a1_mb(2.0)
    eps_col = np.asarray(w7.f32_values(w7.AD1_EPS_PATTERN))
    loss = jax.jit(w7.ad1_loss_factory(eps_col, LIVE_AD_N_STEPS))
    grad = jax.jit(jax.grad(w7.ad1_loss_factory(eps_col, LIVE_AD_N_STEPS)))
    g_ad = np.asarray(grad(jnp.asarray(dz0)), np.float64)
    assert g_ad.shape == dz0.shape and np.all(np.isfinite(g_ad))
    d32 = w7.f32_values(dz0)
    tied = d32 == d32.min()
    assert tied.sum() == 2, "the two 1.0 mm cells of the thin band are the tied minimum"
    order = [k for k in np.argsort(-np.abs(g_ad)) if not tied[k]][:2]
    for k in order:
        h = w7.FD_REL_H * dz0[k]
        dp = dz0.copy()
        dp[k] += h
        dm = dz0.copy()
        dm[k] -= h
        g_fd = (float(loss(jnp.asarray(dp))) - float(loss(jnp.asarray(dm)))) / (2 * h)
        assert np.sign(g_fd) == np.sign(g_ad[k]), (k, g_ad[k], g_fd)
        rel = abs(g_ad[k] - g_fd) / abs(g_fd)
        assert rel <= LIVE_AD_TOL, (k, g_ad[k], g_fd, rel)


# =============================================================================
# Replay from the committed JSON
# =============================================================================

def test_replay_provenance_and_selfcheck(w7_json):
    sc = w7_json["selfcheck"]
    assert sc["all_pass"] and not sc["failed"]
    assert sc["rfx_file"].endswith("rfx/__init__.py")
    for run in w7_json["runs"]:
        for key in ("rfx_file", "git_sha", "git_dirty", "argv", "started_utc"):
            assert key in run


def test_replay_a1_profiles_and_columns(w7_json):
    units = _real(w7_json["a1"]["units"])
    assert units, "no A1 units in the JSON"
    for key, r in units.items():
        prof = np.asarray(r["profile_m"])
        regen = w7.a1_profile(r["arm"], r["scale"])
        assert len(regen) == len(prof) and np.max(np.abs(regen - prof)) <= CELL_TOL, key
        col = np.asarray(r["eps_column"])
        assert len(col) == len(prof) + 1, key
        if r["rule"] == "dual":
            expect = w7.f32_values(w7.dual_eps_nodes(prof))
            assert np.max(np.abs(expect - col)) == 0.0, key
        else:
            table = tuple(round(r["interface_eps"][k], 1) for k in ("14mm", "16mm", "30mm"))
            assert table == w7.A1_INTERFACE_TABLE[(r["arm"], r["scale"])], (key, table)
            assert r["interior_transversely_uniform"] is True, key


def test_replay_a1_model_frequencies_recompute(w7_json):
    units = _real(w7_json["a1"]["units"])
    f_true = w7_json["selfcheck"]["oracle"]["f_true_hz"]
    for key, r in units.items():
        m = w7.a1_model(np.asarray(r["profile_m"]), np.asarray(r["eps_column"]), r["dx"], r["dt"], f_true)
        assert _rel_close(m["f_model"], r["f_model"], MODEL_REL), (key, m["f_model"], r["f_model"])
        for term in ("e_z", "e_x", "e_t"):
            assert abs(m[term] - r[term]) <= MODEL_REL * f_true, (key, term)


def test_replay_a1_rules(w7_json):
    """G1-G3, A1-O(ii), A1-F1, A1-F2 re-evaluated through the instrument's
    judge from the JSON's measured numbers, compared with the stored verdict,
    then asserted HELD (a fired rule is a red test by design)."""
    units = _real(w7_json["a1"]["units"])
    stored = w7_json["a1"]["judge"]
    fresh = w7.judge_a1(units)
    for k in ("p_uc", "p_mb", "rho_at_h1"):
        a, b = fresh["fit"][k], stored["fit"][k]
        assert (a is None) == (b is None), k
        if a is not None:
            assert _rel_close(a, b, JUDGE_REL), (k, a, b)
    for k in ("g1_pass", "g2_pass", "g3_dual_pass"):
        assert fresh["fixture_gates"][k] == stored["fixture_gates"][k], k
    assert fresh["verdict"] == stored["verdict"]
    # the frozen rules, on whatever the ladder holds
    g = fresh["fixture_gates"]
    assert g["g1_pass"], f"G1 z-fraction {g['g1_min_z_fraction']:.3f} < 0.80: fixture invalid"
    assert g["g2_pass"], f"G2 grading share {g['g2_min_grading_share']:.3f} < 0.20: fixture invalid"
    assert g["g3_dual_pass"], (f"G3 dual residual {g['g3_max_residual_dual_hz']/1e6:.4f} MHz > 0.15 MHz: "
                               "solver != its own operators")
    if fresh["fit"]["p_uc"] is None or fresh["fit"]["p_mb"] is None:
        pytest.skip("dual ladder incomplete (fewer than 3 fit points) — nothing to replay yet")
    assert fresh["a1_o_ii"]["pass"], f"dual UC order {fresh['fit']['p_uc']:.3f} outside [1.8, 2.2]"
    assert not fresh["a1_f1"]["fired"], f"A1-F1 fired: p_mb {fresh['fit']['p_mb']:.3f} < 1.8"
    assert not fresh["a1_f2"]["fired"], f"A1-F2 fired: rho {fresh['fit']['rho_at_h1']:.3f} > 2.0"


def test_replay_a1_e_samp_first_order_law(w7_json):
    """Note 1b: on the UC ladder the production column is all-upper at every
    scale, so e_samp = f_model(production) - f_model(dual) is first order in
    the cell (fitted order 1.06)."""
    units = _real(w7_json["a1"]["units"])
    pts = []
    for s in w7.A1_SCALES:
        d = units.get(w7.a1_key("uc", s, "dual"))
        p = units.get(w7.a1_key("uc", s, "production"))
        if d and p:
            pts.append((w7.DF0 * s, abs(p["f_model"] - d["f_model"])))
    if len(pts) < 3:
        pytest.skip("UC production ladder incomplete")
    order, _ = w7.fit_line(pts)
    assert abs(order - E_SAMP_ORDER) <= E_SAMP_ORDER_TOL, order
    # every production row that extracted a mode carries its measured e_samp
    rep = w7_json["a1"]["judge"]["reported"]
    for key, val in rep["e_samp_meas_hz"].items():
        arm, s = key.split("|")
        pr = units[w7.a1_key(arm, float(s), "production")]
        du = units[w7.a1_key(arm, float(s), "dual")]
        if pr["valid"] and du["valid"]:
            assert _rel_close(val, pr["f_meas"] - du["f_meas"], 1e-12), key


def _replay_inplane(w7_json, arm, judge, err_max, diff_max, inv_max):
    units = _real(w7_json[arm]["units"])
    assert units, f"no {arm} units in the JSON"
    fresh = judge(units)
    assert fresh["verdict"] == w7_json[arm]["judge"]["verdict"]
    for key, r in units.items():
        assert r["separation_pass"] and r["anti_vacuity_pass"], key
    for key, e in fresh["arms"].items():
        if key.endswith("|invariance"):
            assert e["pass"], f"{arm} {key}: run-length scatter {e['inv']*100:.4f} % > {inv_max*100:.3f} %"
            continue
        assert e["f1_pass"], f"{arm} {key}: |err| {abs(e['err'])*100:.4f} % > {err_max*100:.2f} %"
        if e["diff_pt"] is not None:
            assert e["f2_pass"], f"{arm} {key}: graded-uniform {e['diff_pt']*100:+.4f} pt > {diff_max*100:.2f} pt"
    return units


def test_replay_a2_rules_and_model(w7_json):
    units = _replay_inplane(w7_json, "a2", w7.judge_a2, w7.A2_ERR_MAX, w7.A2_DIFF_MAX, w7.A2_INV_MAX)
    for key, r in units.items():
        px = np.asarray(r["profile_x"]["cells_m"])
        py = np.asarray(r["profile_y"]["cells_m"])
        if r["cap"] is not None:
            rx, ry, _ = w7.a2_profiles(r["cap"])
            assert np.max(np.abs(rx - px)) <= CELL_TOL and np.max(np.abs(ry - py)) <= CELL_TOL, key
        m = w7.a2_model_err(px, py, r["dt"], r["f_analytic"])
        assert abs(m - r["model_err"]) <= MODEL_REL, key


def test_replay_a3_rules_and_model(w7_json):
    units = _replay_inplane(w7_json, "a3", w7.judge_a3, w7.A3_ERR_MAX, w7.A3_DIFF_MAX, w7.A3_INV_MAX)
    for key, r in units.items():
        px, py, pz = (np.asarray(r[f"profile_{ax}"]["cells_m"]) for ax in "xyz")
        if r["graded"]:
            gx, gy, gz = w7.a3_profiles()
            for a, b in ((gx, px), (gy, py), (gz, pz)):
                assert np.max(np.abs(a - b)) <= CELL_TOL, key
        m = w7.a3_model(px, py, pz, r["dt"], r["f_analytic"])
        assert abs(m["model_err"] - r["model_err"]) <= MODEL_REL, key


def _recheck_profile_ad(row: dict, tol: float) -> None:
    g_ad, g_fd = np.asarray(row["g_ad"]), np.asarray(row["g_fd"])
    assert np.all(np.isfinite(g_ad)), "non-finite AD gradient"
    tied = np.zeros(len(g_ad), bool)
    tied[row["tied_cells"]] = True
    assert row["n_tied_min"] == int(tied.sum()) and len(row["tie_table"]) == int(tied.sum())
    free = np.isfinite(g_fd) & ~tied
    dominant = free & (np.abs(g_fd) > w7.DOMINANT_FRAC * np.abs(g_fd[free]).max())
    assert sorted(np.nonzero(dominant)[0].tolist()) == sorted(row["dominant_cells"])
    rel = np.abs(g_ad - g_fd) / np.maximum(np.abs(g_fd), 1e-300)
    worst = float(rel[dominant].max())
    assert _rel_close(worst, row["worst_dominant_rel_err"], JUDGE_REL)
    assert np.all(np.sign(g_ad[dominant]) == np.sign(g_fd[dominant])), "sign disagreement on a dominant cell"
    assert worst <= tol, f"worst dominant AD-vs-FD {worst:.3e} > {tol}"
    assert row["fired"] is False


def test_replay_ad1(w7_json):
    if "ad1" not in w7_json:
        pytest.skip("AD1 not run yet")
    row = w7_json["ad1"]
    assert row["eps_pattern_matches_declared"]
    assert "error" not in row["f32"], row["f32"].get("error")
    _recheck_profile_ad(row["f32"], w7.AD1_TOL)
    assert "x64_context" in row                      # reported, not gated


def test_replay_ad2(w7_json):
    if "ad2" not in w7_json:
        pytest.skip("AD2 not run yet")
    row = w7_json["ad2"]
    assert "error" not in row, row.get("error")
    rel = abs(row["g_ad"] - row["g_fd"]) / abs(row["g_fd"])
    assert _rel_close(rel, row["rel_err"], JUDGE_REL)
    assert row["sign_agreement"] and rel <= w7.AD2_TOL, f"AD2 rel err {rel:.3e} > {w7.AD2_TOL}"
    assert row["fired"] is False


@pytest.mark.xfail(
    strict=True,
    reason=(
        "attempt 1 FIRED on y and z and is kept on record unchanged (note "
        "second-pass finding 6): its declared central FD at h = 1e-3 put the "
        "reference at 3-17 float32 quanta on the dominant cells, so the "
        "0.5224 / 0.9924 rows measure the reference, not the gradient. The "
        "live gate is test_replay_ad3_second_attempt (reference-resolved "
        "dominant cells, jvp cross-check <= 3.1e-5), HELD on x, y, z. "
        "Decision recorded in the note's 'Replay test' section, 2026-09-11; "
        "strict so a JSON in which attempt 1 no longer fires is noticed."
    ),
)
def test_replay_ad3(w7_json):
    if "ad3" not in w7_json:
        pytest.skip("AD3 not run yet")
    row = w7_json["ad3"]
    assert "error" not in row, row.get("error")
    for ax in "xyz":
        _recheck_profile_ad(row["axes"][ax], w7.AD3_TOL)
    assert row["fired"] is False


def test_replay_ad4(w7_json):
    if "ad4" not in w7_json:
        pytest.skip("AD4 not run yet")
    row = w7_json["ad4"]
    assert row["seed"] == w7.AD4_SEED and row["n_stacks"] == w7.AD4_N_STACKS
    fam = w7.ad4_family()
    assert [s["nz"] for s in fam] == [s["nz"] for s in row["stacks"]]
    for st in row["stacks"]:
        assert st["pass"], st
        assert st["dt"] > 0 and st["trace_finite"] and st["grad_finite"]
    assert row["n_failed"] == 0 and row["fired"] is False


# =============================================================================
# Second pass (review of the first Results): run-length extension of A2 / A3
# and the AD3 second attempt. Same frozen windows; skipped while absent.
# =============================================================================

SECOND_PASS_FROZEN = {
    "A2_N_STEPS_EXT": (24000, 48000), "A3_N_STEPS_EXT": (24000, 48000),
    "AD3B_FD_REL_HS": (1e-3, 3e-3, 1e-2, 3e-2), "AD3B_FD_REL_H_GATE": 1e-2, "AD_REF_FLOOR_QUANTA": 50.0,
}


def test_second_pass_constants_pinned_verbatim():
    for name, value in SECOND_PASS_FROZEN.items():
        got = getattr(w7, name)
        assert (tuple(got) if isinstance(value, tuple) else got) == value, (name, got, value)


def _replay_extension(w7_json, arm, judge_ext, err_max, diff_max, inv_max):
    units = _real(w7_json[arm]["units"])
    ext = {k: r for k, r in units.items() if r.get("second_pass_extension")}
    if not ext:
        pytest.skip(f"{arm} run-length extension not run yet")
    fresh = judge_ext(units)
    assert fresh["verdict"] == w7_json[arm]["judge_ext"]["verdict"]
    for key, r in ext.items():
        assert r["separation_pass"] and r["anti_vacuity_pass"], key
        assert r["git_dirty"] is False, (key, r["git_modified_tracked"])       # measured from a committed tree
        assert all(p.startswith(w7.RESULTS_DIR) for p in r["git_modified_tracked"]), key
    for key, e in fresh["arms"].items():
        if key.endswith("|invariance"):
            assert e["pass"], f"{arm} {key}: run-length scatter {e['inv']*100:.4f} % > {inv_max*100:.3f} %"
            continue
        assert e["f1_pass"], f"{arm} {key}: |err| {abs(e['err'])*100:.4f} % > {err_max*100:.2f} %"
        if e["diff_pt"] is not None:
            assert e["f2_pass"], f"{arm} {key}: graded-uniform {e['diff_pt']*100:+.4f} pt > {diff_max*100:.2f} pt"
        # the reported spatial split is arithmetic on the row (reviewer finding: F2 carries the control's e_t)
        assert abs(e["spatial_err"] - (e["err"] - e["e_t"])) <= 1e-15
        if "spatial_diff_pt" in e and e["spatial_diff_pt"] is not None:
            assert abs(e["spatial_diff_pt"] - (e["spatial_err"] - e["spatial_err_uniform"])) <= 1e-15
    return ext


def test_replay_a2_extension(w7_json):
    ext = _replay_extension(w7_json, "a2", w7.judge_a2_ext, w7.A2_ERR_MAX, w7.A2_DIFF_MAX, w7.A2_INV_MAX)
    for key, r in ext.items():
        px = np.asarray(r["profile_x"]["cells_m"])
        py = np.asarray(r["profile_y"]["cells_m"])
        assert abs(w7.a2_model_err(px, py, r["dt"], r["f_analytic"]) - r["model_err"]) <= MODEL_REL, key


def test_replay_a3_extension(w7_json):
    ext = _replay_extension(w7_json, "a3", w7.judge_a3_ext, w7.A3_ERR_MAX, w7.A3_DIFF_MAX, w7.A3_INV_MAX)
    for key, r in ext.items():
        px, py, pz = (np.asarray(r[f"profile_{ax}"]["cells_m"]) for ax in "xyz")
        m = w7.a3_model(px, py, pz, r["dt"], r["f_analytic"])
        assert abs(m["model_err"] - r["model_err"]) <= MODEL_REL, key
        assert abs(w7.leapfrog_term(r) - r["e_t"]) <= 1e-12, key            # the judge's e_t is the row's e_t


def test_replay_ad3_second_attempt(w7_json):
    """Second attempt of AD3 (reference-resolution fix, note second-pass
    section): the first attempt stays under 'ad3' (its replay test stays red
    by design); here the gate is re-evaluated from the stored arrays on the
    reference-resolved dominant cells at the gated FD step."""
    if "ad3_second_attempt" not in w7_json:
        pytest.skip("AD3 second attempt not run yet")
    row = w7_json["ad3_second_attempt"]
    assert "ad3" in w7_json and w7_json["ad3"]["fired"] is True            # attempt 1 kept, unchanged
    assert "error" not in row, row.get("error")
    assert row["fd_rel_h_gate"] == w7.AD3B_FD_REL_H_GATE and row["ref_floor_quanta"] == w7.AD_REF_FLOOR_QUANTA
    assert row["tol"] == w7.AD3_TOL and row["dominant_frac"] == w7.DOMINANT_FRAC and row["n_steps"] == w7.AD_N_STEPS
    assert row["git_dirty"] is False, row["git_modified_tracked"]
    ulp = float(np.spacing(np.float32(row["loss0"])))
    assert ulp == row["loss_ulp"]
    for ax in "xyz":
        a = row["axes"][ax]
        d0 = np.asarray(row[f"d{ax}_m"])
        g_ad = np.asarray(a["g_ad"])
        assert np.all(np.isfinite(g_ad)) and a["all_finite"]
        tied = np.zeros(len(g_ad), bool)
        tied[a["tied_cells"]] = True
        gate_key = f"{w7.AD3B_FD_REL_H_GATE:g}"
        p = a["per_h"][gate_key]
        g_fd = np.asarray(p["g_fd"])
        quanta = np.abs(g_fd) * 2 * w7.AD3B_FD_REL_H_GATE * d0 / ulp
        assert np.allclose(quanta, np.asarray(p["quanta"]), rtol=1e-9, atol=0)
        free = np.isfinite(g_fd) & ~tied
        dominant = free & (np.abs(g_fd) > w7.DOMINANT_FRAC * np.abs(g_fd[free]).max())
        assert sorted(np.nonzero(dominant)[0].tolist()) == sorted(p["dominant_cells"]), ax
        resolved = dominant & (quanta >= w7.AD_REF_FLOOR_QUANTA)
        assert sorted(np.nonzero(resolved)[0].tolist()) == sorted(p["resolved_cells"]), ax
        rel = np.abs(g_ad - g_fd) / np.maximum(np.abs(g_fd), 1e-300)
        worst = float(rel[resolved].max())
        assert _rel_close(worst, a["worst_resolved_rel_err"], JUDGE_REL), ax
        assert not a["inconclusive"], f"{ax}: reference-limited (resolved {a['n_resolved']} <= unresolved {a['n_unresolved']})"
        assert np.all(np.sign(g_ad[resolved]) == np.sign(g_fd[resolved])), f"{ax}: sign disagreement"
        assert worst <= w7.AD3_TOL, f"{ax}: worst resolved AD-vs-FD {worst:.3e} > {w7.AD3_TOL}"
        assert a["fired"] is False, ax
        # the h = 1e-3 row of this attempt reproduces attempt 1 (same computation, deterministic)
        p1 = a["per_h"]["0.001"]
        assert _rel_close(p1["worst_dominant_rel_err_attempt1_rule"],
                          w7_json["ad3"]["axes"][ax]["worst_dominant_rel_err"], 1e-6), ax
        # every tied cell carries the split model alongside FD+ / FD- (AD5, knowledge output)
        assert len(p["tie_table"]) == int(tied.sum()) and all("split_model" in tt for tt in p["tie_table"])
        assert np.all(np.isfinite(np.asarray(a["g_jvp"])))                 # forward-mode reference recorded
    assert row["fired"] is False
