"""F7 replay and the narrow-band transition law on ``make_band_profile``
profiles — exact discrete chain model only, no FDTD.

Replays the W6 witness (``validation/research/multiband_nu/w6_band_builder.py``,
pre-declaration ``docs/design_notes/20260907_nu_band_profile_predeclaration.md``
section 3, F7/F8) from its committed results JSON:

* F7: the auto-z PCB profile is regenerated by ``_make_dz_profile`` on this
  tree and must equal the committed NEW profile cell for cell; the chain
  model on it (and on the committed OLD d990e18c profile, replayed from the
  JSON so the test needs no ``git show``) must return the committed totals,
  and the two frozen rules must not fire:
  F7a ``|R|^2 <= 1.5 (sum_steps |R_step|)^2`` (amplitude sum, coherent);
  F7b ``max non-thirds |R_step| <= |R_single(r = 1.4, d = max P)| (1 + 1e-9)``.
  The revert-proof numbers of the note's F2 (OLD max ratio 8.000, 25 pairs
  over 1.4) are pinned so the replay cannot pass on a regressed OLD row.
* F8 (model side): every committed row's profile is what the builder emits
  today, its chain-model ``R_model`` is reproduced, the window is the frozen
  ``0.20 R_model + 3e-5`` (amplitude), and the committed ``R_meas`` sits
  inside it — the FDTD verdict replayed without FDTD.
* Transition law, on builder profiles A(n_b) for n_b = 1..80: a single
  1.96 -> 1.4 -> 1.0 mm ramp reflects 5.7907e-3 at 10 GHz on this fixture;
  a band between two such ramps is bounded by twice that and oscillates
  with width (chain peaks 7 / 24 / 41 / 59 / 76 cells, nulls 15 / 33 / 50 /
  67, maximum 2 x 5.7907e-3 x 0.9999); the Fabry-Perot form
  ``2 R_single |sin(k_g (L + L_ramp))|`` with L_ramp = 1.87 mm and the
  discrete k_g(1.0 mm) = 0.18163 /mm reproduces the six W6 rows.

Tolerances, declared here before the first run of this file and never
widened: F8 replayed floats to 1e-9 relative (300 cells of 1-2 mm, a
well-conditioned direct solve; the re-execution on 5bf9d16b reproduced
the first attempt's rows to <= 3e-10); F7 replayed floats to 1e-6
relative — the PCB chain solve carries 8.333 um cells next to a 10 GHz
wavenumber (stiffness ratio about 1e6 between the 1/d^2 and the
(S0^2 - Sy^2) terms), and a 5e-16 relative change of one cell between
two trees moved R_total by 1.4e-8 relative in the JSON diff, so 1e-9
would lock solver noise, not physics; profile cells to 1e-12 m (I1); the
note's quoted five-figure values (5.7907e-3, 0.18163 /mm) to 1e-4
relative; the L_ramp law to 1e-2 relative on the six W6 rows (measured
0.03 % to 0.53 % on 5bf9d16b — the reviewer note's "within 0.5 %" is
0.53 % at n_b = 16; recorded in the design note, not rounded away here).

What the F7 1e-6 budget now covers, and what it no longer has to. The
first CI run of this file failed on ubuntu at sum_abs_R_step, 4.3e-6
against a JSON written on macOS: every per-step |R_step| disagreed
(median 2.9e-5, worst 3.4e-4) because a step's reflection is a 1e-7
residue that a dense float64 solve extracts by cancelling 1e10-scale
terms, so its last bits are the LAPACK build's. Those numbers come from
``chain_model.step_reflection`` now — the closed form of the same
junction, accurate to a few ulp and platform-independent (verified
against a 60-digit solve of ``scattering``'s own rows, and against
``scattering`` itself by
``test_f7_step_reflection_is_the_same_model_as_the_solve`` below). The
1e-6 budget is therefore spent only on R_total and T_total, which are
genuine multi-cell solves. Their measured macOS-vs-Linux spread is
4.5e-7 (OLD row R_total), 4.0e-8 (NEW row) and 2.8e-12 (T_total): the
OLD row uses 45 % of the budget, so a third platform could still put it
over. A stable form for those is plausible but not a drop-in:
each junction's exact reflection is the admittance mismatch this file's
step oracle is built on, so a Riccati cascade over the uniform runs is
the candidate, but a throwaway prototype of it missed both rows by about
20 %, so the node/cell bookkeeping between adjacent interfaces has to be
derived rather than guessed. That is model work, not a CI fix, and it is
deliberately NOT done here.

STEP_ORACLE_REL below is a separate, looser number: it bounds how far
the float64 dense solve of a step may sit from the exact closed form,
which is the solve's noise, not a tolerance on any replayed value.

Runtime: about 200 chain-model solves on <= 300-cell profiles (2 ms each)
plus 80 builder calls — a fast-lane test.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pytest

from rfx.auto_config import _make_dz_profile
from rfx.nonuniform import make_nonuniform_grid

from validation.research.multiband_nu import fixtures as fx
from validation.research.multiband_nu import w6_band_builder as w6
from validation.research.multiband_nu.chain_model import (
    bloch_kz, scattering, step_reflection,
)

_REPO = pathlib.Path(__file__).resolve().parents[3]
_JSON = _REPO / "validation/research/multiband_nu/results/w6_band_builder.json"

REL = 1e-9            # F8 replayed chain-model floats (well-conditioned)
F7_REL = 1e-6         # F7 replayed floats (8 um cells; see the docstring)
CELL_TOL = 1e-12      # m, I1
QUOTED_REL = 1e-4     # five-figure values quoted in the note
LAW_REL = 1e-2        # Fabry-Perot form with L_ramp on the six W6 rows
STEP_ORACLE_REL = 5e-5      # closed form vs a SHORT-runway dense step solve
STEP_ORACLE_LONG_REL = 3e-3  # ... vs the 140/150 runway, where the solve is worse

R_SINGLE_RAMP = 5.7907e-3      # note, F8 law paragraph and W6 matrix row
K_G_PER_MM = 0.18163           # discrete k_g(1.0 mm), reviewer notes
L_RAMP_M = 1.87e-3             # L_eff = L + 1.87 mm, reviewer notes
CHAIN_PEAKS = (7, 24, 41, 59, 76)
CHAIN_NULLS = (15, 33, 50, 67)
LAW_SWEEP_MAX = 80


@pytest.fixture(scope="module")
def w6_json() -> dict:
    with open(_JSON) as fh:
        return json.load(fh)


def _rel_close(x: float, y: float, rel: float = REL) -> bool:
    return abs(x - y) <= rel * max(abs(x), abs(y))


# --- F7 -----------------------------------------------------------------------

def test_f7_new_pcb_profile_regenerates_cell_for_cell(w6_json):
    new = np.asarray(_make_dz_profile(w6.PCB_FEATS, w6.PCB_DOMAIN, w6.PCB_DX), np.float64)
    committed = np.asarray(w6_json["f7"]["new"]["cells_um"], np.float64) * 1e-6
    assert len(new) == len(committed) == w6_json["f7"]["new"]["nz"]
    assert np.max(np.abs(new - committed)) <= CELL_TOL
    # F2 on the auto-z output: every pair outside a thirds split <= 1.3 + 1e-9
    ratios = np.maximum(new[1:] / new[:-1], new[:-1] / new[1:])
    thirds = w6._thirds_pairs(new, w6.PCB_EDGES)
    non_thirds = [r for k, r in enumerate(ratios) if k not in thirds]
    assert max(non_thirds) <= 1.3 + 1e-9
    # a thirds split is 1/3, 2/3, 1 of the block cell: its two pairs carry
    # ratios 1.5 and 2.0 (the OLD row's "133.3 -> 200 um, r 1.5" is one)
    assert all(min(abs(ratios[k] - 1.5), abs(ratios[k] - 2.0)) <= 1e-9 for k in thirds)
    assert len(thirds) == 20 and sum(abs(ratios[k] - 2.0) <= 1e-9 for k in thirds) == 10
    # F1/F3: every declared edge on a node, column exact
    nodes = np.concatenate([[0.0], np.cumsum(new)])
    for e in w6.PCB_EDGES:
        assert np.min(np.abs(nodes - e)) <= CELL_TOL
    assert abs(nodes[-1] - w6.PCB_DOMAIN) <= CELL_TOL


def test_f7_old_row_is_the_revert_proof(w6_json):
    old = w6_json["f7"]["old"]
    cells = np.asarray(old["cells_um"], np.float64) * 1e-6
    ratios = np.maximum(cells[1:] / cells[:-1], cells[:-1] / cells[1:])
    # note section 3, F2: "(a) 8.000 ... these two numbers are the revert-proof"
    assert abs(ratios.max() - 8.0) <= 1e-9
    assert int(np.sum(ratios > 1.4 + 1e-9)) == 25
    assert old["nz"] == 45
    assert _rel_close(old["max_ratio"], 8.0, F7_REL)
    assert old["n_ratio_over_1p4"] == 25


def test_f7_step_reflection_is_the_same_model_as_the_solve(w6_json):
    """``step_reflection`` is ``scattering`` on a step, solved on paper.

    The closed form is what the F7 per-step numbers are computed with, so
    it needs an oracle that is not itself the closed form. That oracle is
    the dense solve this file already trusts for R_total: for every
    distinct step in the committed NEW profile, the two must agree inside
    the dense solve's own accuracy on a 1e-7 residue.

    Two runways, two bounds, because the solve's accuracy depends on the
    matrix it builds. At 20/20 the dense solve is close to the closed form
    (measured worst 2.1e-6 over the 41 steps), so that leg carries the
    TIGHT bound and is the real oracle. At 140/150 -- the runway the F7
    fixture actually embeds -- the same solve is an order worse (measured
    worst 2.6e-4) because the cancellation runs over a bigger matrix, so
    that leg carries a loose bound and checks only that the gap does not
    keep growing: the closed form takes no runway at all, and a
    disagreement that scaled with it would mean a different problem rather
    than the same one solved better. Both bounds sit ~20x above the
    measured worst so a macOS solve, which sits up to 3.4e-4 from the
    linux one on these same steps, cannot flake them.

    The tight bound is measured on THIS profile's steps. The solve's
    error goes as 1/|R|, so a much gentler step at the finest cell would
    need it re-measured: swept over 200 (cell, ratio) combinations from
    8 to 200 um and 1.02 to 2.0, the 20/20 worst is 3.96e-5, and every
    case above 3e-5 is a ratio <= 1.05 step on an 8 um cell -- which this
    profile does not contain (its gentlest is 1.27). If a regenerated
    profile brings one in, re-measure rather than widen on a red.
    """
    f7 = w6_json["f7"]
    dt, dy, b = f7["dt_new_s"], f7["dy_m"], f7["b_m"]
    cells = np.asarray(f7["new"]["cells_um"], np.float64) * 1e-6
    pairs = sorted({(float(cells[k]), float(cells[k + 1]))
                    for k in range(len(cells) - 1)
                    if cells[k] != cells[k + 1]
                    and max(cells[k] / cells[k + 1],
                            cells[k + 1] / cells[k]) > 1.01})
    assert len(pairs) >= 8
    for d0, d1 in pairs:
        closed = step_reflection(d0, d1, w6.F0, dt, dy, b)
        assert closed > 0
        for n_lead, n_tail, rel in ((20, 20, STEP_ORACLE_REL),
                                    (w6.F7_LEAD, w6.F7_TAIL,
                                     STEP_ORACLE_LONG_REL)):
            prof = np.array([d0] * n_lead + [d1] * n_tail, np.float64)
            solved = abs(scattering(prof, n_lead, n_tail, w6.F0, dt, dy, b)[0])
            assert _rel_close(closed, solved, rel), (
                d0, d1, n_lead, closed, solved)


@pytest.mark.parametrize("side", ["old", "new"])
def test_f7_chain_model_replays_committed_totals_and_rules_do_not_fire(w6_json, side):
    f7 = w6_json["f7"]
    row = f7[side]
    cells = np.asarray(row["cells_um"], np.float64) * 1e-6
    dt = f7[f"dt_{side}_s"]
    # dt is the solver's own, from the embedded profile (the 8.333 um cell)
    grid = make_nonuniform_grid((w6.F7_A, fx.B_Y), w6._embed(cells), w6.PCB_DX,
                                cpml_layers=0)
    assert _rel_close(float(grid.dt), dt, 1e-12)
    rep = w6.f7_profile_report(side, cells, dt, f7["dy_m"], f7["b_m"])
    for key in ("R_total", "R_total_sq", "T_total", "sum_abs_R_step",
                "sum_R_step_sq", "max_nonthirds_step", "max_thirds_step",
                "R_single_cap_at_dmax", "f7a_window"):
        assert _rel_close(rep[key], row[key], F7_REL), (key, rep[key], row[key])
    assert rep["n_steps"] == row["n_steps"]
    # the frozen rules, recomputed from the replayed pieces
    assert rep["R_total_sq"] <= 1.5 * rep["sum_abs_R_step"] ** 2
    assert rep["max_nonthirds_step"] <= rep["R_single_cap_at_dmax"] * (1 + 1e-9)
    assert rep["f7a_fired"] is False and row["f7a_fired"] is False
    assert rep["f7b_fired"] is False and row["f7b_fired"] is False


# --- F8, model side ------------------------------------------------------------

def _f8_rows(path=_JSON):
    with open(path) as fh:
        return json.load(fh)["f8"]["rows"]


@pytest.mark.parametrize("row", _f8_rows(), ids=lambda r: f"n_b={r['n_b']}")
def test_f8_row_profile_model_window_and_verdict_replay(w6_json, row):
    f8 = w6_json["f8"]
    n_b = row["n_b"]
    prof = w6.a_profile(n_b)
    committed = np.asarray(row["profile_cells_mm"], np.float64) * 1e-3
    assert len(prof) == len(committed) == row["nz"]
    assert np.max(np.abs(prof - committed)) <= CELL_TOL
    assert np.max(np.abs(prof - w6.a_profile_expected(n_b))) <= CELL_TOL
    assert row["builder_matches_declared_vector"] is True
    dt = row["dt_s"]
    assert _rel_close(dt, f8["dt_b_s"], 1e-12)
    R, _ = scattering(prof, w6.N_LEAD_C, w6.N_TAIL_C, w6.F0, dt, fx.DXY, fx.B_Y)
    assert _rel_close(abs(R), row["R_model"]), (abs(R), row["R_model"])
    half = 0.20 * row["R_model"] + w6.FS2_FLOOR
    assert _rel_close(row["window"][0], row["R_model"] - half)
    assert _rel_close(row["window"][1], row["R_model"] + half)
    # the committed FDTD verdict, replayed against the frozen window
    assert abs(row["R_meas"] - row["R_model"]) <= half
    assert row["f8_fired"] is False
    assert row["is_gate_row"] is (n_b == 4)


def test_f8_gate_row_present_once(w6_json):
    rows = w6_json["f8"]["rows"]
    assert [r["n_b"] for r in rows if r["is_gate_row"]] == [4]
    assert {2, 4, 8, 16} <= {r["n_b"] for r in rows}


# --- transition law on builder profiles ----------------------------------------

@pytest.fixture(scope="module")
def law(w6_json):
    dt = w6_json["f8"]["dt_b_s"]
    grid = make_nonuniform_grid((fx.A_X, fx.B_Y), w6.a_profile(4), fx.DXY, cpml_layers=0)
    assert _rel_close(float(grid.dt), dt, 1e-12)
    single = np.asarray([w6.DC] * w6.N_LEAD_C + [w6.DR] + [fx.DZ_FINE] * w6.N_TAIL_C)
    r_single = abs(scattering(single, w6.N_LEAD_C, w6.N_TAIL_C, w6.F0, dt, fx.DXY, fx.B_Y)[0])
    k_g = bloch_kz(w6.F0, dt, fx.DXY, fx.B_Y, fx.DZ_FINE)
    r_band = {}
    for n_b in range(1, LAW_SWEEP_MAX + 1):
        prof = w6.a_profile(n_b)
        assert np.max(np.abs(prof - w6.a_profile_expected(n_b))) <= CELL_TOL
        r_band[n_b] = abs(scattering(prof, w6.N_LEAD_C, w6.N_TAIL_C, w6.F0, dt,
                                     fx.DXY, fx.B_Y)[0])
    return {"dt": dt, "r_single": r_single, "k_g": k_g, "r_band": r_band}


def test_law_single_ramp_and_k_g_are_the_quoted_values(law):
    assert _rel_close(law["r_single"], R_SINGLE_RAMP, QUOTED_REL), law["r_single"]
    assert _rel_close(law["k_g"] * 1e-3, K_G_PER_MM, QUOTED_REL), law["k_g"]


def test_law_narrow_band_is_bounded_by_twice_the_single_ramp(law):
    r = law["r_band"]
    bound = 2 * law["r_single"]
    assert max(r.values()) <= bound * (1 + 1e-9)
    # the chain reaches the bound: maximum 2 x R_single x 0.9999 at 76 cells
    n_max = max(r, key=r.get)
    assert n_max == CHAIN_PEAKS[-1]
    assert 0.999 <= r[n_max] / bound <= 1.0 + 1e-9


def test_law_oscillates_with_width_peaks_and_nulls(law):
    r = law["r_band"]
    peaks = [n for n in range(2, LAW_SWEEP_MAX) if r[n] > r[n - 1] and r[n] > r[n + 1]]
    nulls = [n for n in range(2, LAW_SWEEP_MAX) if r[n] < r[n - 1] and r[n] < r[n + 1]]
    assert tuple(peaks) == CHAIN_PEAKS
    assert tuple(nulls) == CHAIN_NULLS


def test_law_fabry_perot_form_with_ramp_length_reproduces_w6_rows(law, w6_json):
    rows = w6_json["f8"]["rows"]
    for row in rows:
        n_b = row["n_b"]
        L = n_b * fx.DZ_FINE
        form = 2 * law["r_single"] * abs(np.sin(law["k_g"] * (L + L_RAMP_M)))
        chain = law["r_band"][n_b]
        assert _rel_close(chain, row["R_model"])
        assert abs(form - chain) <= LAW_REL * chain, (n_b, form, chain)
