"""E1 replay — the resolution x ratio sweep of the W6 narrow-band
transition law, chain model only, no FDTD.

Replays ``validation/research/multiband_nu/results/e1_band_law_sweep.json``
(and, for the model side, the frozen predictions
``results/e1_band_law_sweep_model.json``) written by
``w6_band_builder.py --sweep`` under
``docs/design_notes/20260907_nu_exp1_band_law_sweep_predeclaration.md``:

* every (resolution, ratio) setting is regenerated by ``e1_setting`` and
  must match the JSON cell for cell (the 30 / 1.4 cell must be the lane-A
  layout: K_SRC 85, K_PRB 100, 140 / 150 / 400 cells, 1200 steps, and its
  five ``R_model`` the lane-A W6 values);
* the builder emits the declared vector for every band and single-ramp
  profile; the chain model on it returns the committed ``R_model`` /
  ``R_single_model``; the window is the frozen ``0.20 R_model + 3e-5``;
  the gate geometry is reproduced and holds;
* ``c_model`` re-fits from the committed chain sweep (n_b = 0..80) and
  sits within the declared distance of the closed form
  ``2 DR r^2 / (1 + r^2)``;
* results side: the committed ``R_meas`` sits inside the window exactly
  when the row is not ``fired``; the (i) scaling ratio, the (ii) bound and
  the (iii) ``c_meas`` fit are recomputed from the committed measurements
  and agree with the recorded flags; the cell verdicts are the declared
  conjunctions. The test replays verdicts — it does not require them to be
  "held": a cell recorded as fired must replay as fired.

Tolerances, declared before the first run of this file:
replayed chain-model floats 1e-8 relative -- RE-DECLARED 2026-09-11 from
1e-9 on a measurement, not a preference: the same dense solve of the
N60_r1.2 profile (n_b = 32, 1100 cells) returned 1.1831862931777621e-4 on
one GitHub runner (PR #963's fast-suite (4)) and 1.1831862916448015e-4 on
another (main's run 34572755776 at b7ad4e93, and this pod), 1.3e-9 apart
-- above the 1e-9 the file first declared on lane A's 3e-10 re-execution,
which was one machine reproducing itself. The declaration was falsified
by a second runner, so the bound is now set 8x above the measured
cross-runner spread (same class as the W6 F7 finding, PR #956, where the
macOS/linux spread on a stiffer profile was 4e-6); every other tolerance
below is unchanged; profile cells 1e-12 m (I1); ``c`` re-fits
to 1e-9 m (the same deterministic scan on the same data); closed-form c
within 5 % of ``c_model`` for r <= 1.4 and 12.5 % for r = 2.0 (Table L of
the note: 0.1-4.5 % and 0.7-11.9 %); gate times 1e-9 relative; the
30 / 1.4 control rows equal lane A's W6 ``R_model`` to 1e-9 and, on the
results side, lane A's ``R_meas`` to 1e-6 relative (float32 fields,
same tree family).

Results-side: ``k_src_used`` / ``k_prb_used`` equal the setting's cells and
``source_probe_in_coarse_lead`` is true on every arm (the first attempt's
defect, a2cb6cf3).

Runtime: 63 chain solves on <= 1100-cell profiles plus 9 c re-fits from
stored sweeps — a fast-lane test (about 5 s).
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pytest

from validation.research.multiband_nu import fixtures as fx
from validation.research.multiband_nu import w6_band_builder as w6
from validation.research.multiband_nu.chain_model import bloch_kz, scattering

_REPO = pathlib.Path(__file__).resolve().parents[3]
_RESULTS = _REPO / "validation/research/multiband_nu/results"
_MODEL_JSON = _RESULTS / "e1_band_law_sweep_model.json"
_SWEEP_JSON = _RESULTS / "e1_band_law_sweep.json"
_W6_JSON = _RESULTS / "w6_band_builder.json"

REL = 1e-8   # re-declared 2026-09-11 from 1e-9, see the module docstring
CELL_TOL = 1e-12
C_TOL_M = 1e-9
CLOSED_FORM_REL = {1.2: 0.05, 1.4: 0.05, 2.0: 0.125}
CONTROL_MEAS_REL = 1e-6
LANE_A_KEY = "N30_r1.4"
LANE_A_LAYOUT = {"k_src": 85, "k_prb": 100, "n_lead": 140, "n_tail": 150,
                 "n_b_coarse": 400, "n_tail_fine": 294}


def _load(path):
    if not path.exists():
        pytest.skip(f"{path.name} not present")
    with open(path) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def model_json():
    return _load(_MODEL_JSON)


@pytest.fixture(scope="module")
def sweep_json():
    return _load(_SWEEP_JSON)


@pytest.fixture(scope="module")
def w6_json():
    return _load(_W6_JSON)


def _rel_close(x, y, rel=REL):
    return abs(x - y) <= rel * max(abs(x), abs(y))


def _cells(path):
    if not path.exists():
        return []
    with open(path) as fh:
        return sorted(json.load(fh)["cells"])


def _closed_form_c(st):
    r = st["ratio"]
    return 2 * st["ramp_cell_m"] * r * r / (1 + r * r)


# --- settings ------------------------------------------------------------------

@pytest.mark.parametrize("key", _cells(_MODEL_JSON))
def test_setting_regenerates(model_json, key):
    st = model_json["cells"][key]["setting"]
    regen = w6.e1_setting(st["n_lambda"], st["ratio"])
    for k, v in st.items():
        if isinstance(v, bool) or isinstance(v, int):
            assert regen[k] == v, (key, k, regen[k], v)
        else:
            assert _rel_close(regen[k], v, 1e-12), (key, k, regen[k], v)
    assert regen["in_accuracy_class"] is (st["ratio"] <= 1.4 and st["n_lambda"] >= 30)
    assert w6.e1_cell_key(st["n_lambda"], st["ratio"]) == key


def test_lane_a_control_cell_is_the_lane_a_layout(model_json, w6_json):
    cell = model_json["cells"][LANE_A_KEY]
    st = cell["setting"]
    for k, v in LANE_A_LAYOUT.items():
        assert st[k] == v, (k, st[k], v)
    assert cell["n_steps"] == w6.N_STEPS == w6_json["f8"]["n_steps"]
    assert _rel_close(cell["model"]["dt_s"], w6_json["f8"]["dt_b_s"], 1e-12)
    lane_a = {r["n_b"]: r["R_model"] for r in w6_json["f8"]["rows"]}
    for row in cell["model"]["rows"]:
        assert _rel_close(row["R_model"], lane_a[row["n_b"]]), (row["n_b"], row["R_model"])
    assert _rel_close(cell["model"]["R_single_model"], 5.7907e-3, 1e-4)
    assert _rel_close(cell["model"]["c_model_m"], 1.87e-3, 1e-2)


# --- model side, per cell --------------------------------------------------------

def _replay_model_side(cell, key):
    st = cell["setting"]
    m = cell["model"]
    dt, dy, b = m["dt_s"], fx.DXY, fx.B_Y
    regen = w6.e1_setting(st["n_lambda"], st["ratio"])
    single = w6.e1_single_profile(regen)
    assert np.max(np.abs(single - w6.e1_single_expected(regen))) <= CELL_TOL
    assert len(single) == m["single_nz"]
    assert m["single_builder_matches_declared_vector"] is True
    r1 = abs(scattering(single, regen["n_lead"], regen["n_tail_fine"], w6.F0, dt, dy, b)[0])
    assert _rel_close(r1, m["R_single_model"]), (key, r1, m["R_single_model"])
    k_g = bloch_kz(w6.F0, dt, dy, b, regen["fine_cell_m"])
    assert _rel_close(k_g, m["k_g_fine_per_m"])
    for row in m["rows"]:
        prof = w6.e1_band_profile(regen, row["n_b"])
        assert np.max(np.abs(prof - w6.e1_band_expected(regen, row["n_b"]))) <= CELL_TOL
        assert len(prof) == row["nz"] and row["builder_matches_declared_vector"] is True
        r_model = abs(scattering(prof, regen["n_lead"], regen["n_tail"], w6.F0, dt, dy, b)[0])
        assert _rel_close(r_model, row["R_model"]), (key, row["n_b"], r_model, row["R_model"])
        half = 0.20 * row["R_model"] + w6.FS2_FLOOR
        assert _rel_close(row["window"][0], row["R_model"] - half)
        assert _rel_close(row["window"][1], row["R_model"] + half)
        assert _rel_close(row["bound_2R1"], 2 * m["R_single_model"] * (1 + w6.E1_BOUND_SLACK))
        g = w6.e1_gates(regen, prof, "band", row["n_b"], dt, cell["n_steps"])
        for k, v in row["gates_ns"].items():
            assert _rel_close(g["gates_ns"][k], v, 1e-9), (key, row["n_b"], k)
        assert g["gates_hold"] is True and row["gates_hold"] is True
        assert all(v > 0 for v in row["gate_margins_ns"].values())
    # c_model re-fit from the committed chain sweep
    sweep = m["chain_sweep_R"]
    assert len(sweep) == w6.E1_LAW_SWEEP_MAX + 1
    c = w6.e1_fit_c(list(range(len(sweep))), sweep, regen["fine_cell_m"],
                    m["R_single_model"], m["k_g_fine_per_m"],
                    w6.E1_C_FIT_MAX_DR * regen["ramp_cell_m"])
    assert abs(c - m["c_model_m"]) <= C_TOL_M, (key, c, m["c_model_m"])
    assert _rel_close(m["c_model_over_ramp_cell"], m["c_model_m"] / regen["ramp_cell_m"])
    cf = _closed_form_c(regen)
    assert abs(cf - m["c_model_m"]) <= CLOSED_FORM_REL[st["ratio"]] * m["c_model_m"], (key, cf, m["c_model_m"])
    # bound on the model's own sweep: 2 R_single is never exceeded
    assert max(sweep) <= 2 * m["R_single_model"] * (1 + 1e-9)
    assert _rel_close(m["chain_max_over_2R1"], max(sweep) / (2 * m["R_single_model"]))


@pytest.mark.parametrize("key", _cells(_MODEL_JSON))
def test_model_side_replays_frozen_predictions(model_json, key):
    _replay_model_side(model_json["cells"][key], key)


@pytest.mark.parametrize("key", _cells(_SWEEP_JSON))
def test_model_side_of_results_replays(sweep_json, model_json, key):
    cell = sweep_json["cells"][key]
    _replay_model_side(cell, key)
    # the results JSON carries the same frozen predictions as the model JSON
    frozen = model_json["cells"][key]["model"]
    assert _rel_close(cell["model"]["R_single_model"], frozen["R_single_model"])
    assert abs(cell["model"]["c_model_m"] - frozen["c_model_m"]) <= C_TOL_M
    for row, frow in zip(cell["model"]["rows"], frozen["rows"]):
        assert row["n_b"] == frow["n_b"] and _rel_close(row["R_model"], frow["R_model"])


# --- results side ------------------------------------------------------------------

@pytest.mark.parametrize("key", _cells(_SWEEP_JSON))
def test_results_rows_replay_verdicts(sweep_json, key):
    cell = sweep_json["cells"][key]
    if "arms" not in cell:
        pytest.skip(f"{key} has no measured arms")
    st = cell["setting"]
    r1 = cell["model"]["R_single_model"]
    s = cell["single"]
    half = 0.20 * s["R_model"] + w6.FS2_FLOOR
    assert _rel_close(s["R_model"], r1)
    assert s["fired"] is (abs(s["R_meas"] - s["R_model"]) > half)
    assert s["dt_matches_b"] is True and s["gates_hold"] is True
    assert (s["k_src_used"], s["k_prb_used"]) == (st["k_src"], st["k_prb"])
    assert s["source_probe_in_coarse_lead"] is True
    assert [a["n_b"] for a in cell["arms"]] == [r["n_b"] for r in cell["model"]["rows"]]
    for arm, row in zip(cell["arms"], cell["model"]["rows"]):
        assert _rel_close(arm["R_model"], row["R_model"])
        half = 0.20 * arm["R_model"] + w6.FS2_FLOOR
        assert _rel_close(arm["window"][0], arm["R_model"] - half)
        assert arm["fired"] is (abs(arm["R_meas"] - arm["R_model"]) > half)
        assert _rel_close(arm["deviation"], abs(arm["R_meas"] - arm["R_model"]), 1e-6)
        assert arm["bound_fired"] is (arm["R_meas"] > 2 * r1 * (1 + w6.E1_BOUND_SLACK))
        assert arm["dt_matches_b"] is True and arm["gates_hold"] is True
        assert arm["builder_matches_declared_vector"] is True
        # the first attempt's defect (a2cb6cf3): source/probe at the lane-A
        # cell indices instead of the setting's — pinned per arm
        assert (arm["k_src_used"], arm["k_prb_used"]) == (st["k_src"], st["k_prb"])
        assert arm["source_probe_in_coarse_lead"] is True
        assert _rel_close(arm["source_probe_planes_mm"][0], st["k_src"] * st["coarse_cell_m"] * 1e3, 1e-9)
    # (iii) c_meas re-fit from the committed measurements
    c = w6.e1_fit_c([a["n_b"] for a in cell["arms"]], [a["R_meas"] for a in cell["arms"]],
                    st["fine_cell_m"], r1, cell["model"]["k_g_fine_per_m"],
                    w6.E1_C_FIT_MAX_DR * st["ramp_cell_m"])
    assert abs(c - cell["c_meas_m"]) <= C_TOL_M, (key, c, cell["c_meas_m"])
    c_dev = abs(cell["c_meas_m"] - cell["model"]["c_model_m"])
    assert _rel_close(cell["c_window_m"], w6.E1_C_TOL_DR * st["ramp_cell_m"])
    assert cell["law_iii_fired"] is (c_dev > w6.E1_C_TOL_DR * st["ramp_cell_m"])
    # verdict conjunctions, as declared
    assert cell["any_width_fired"] is any(a["fired"] for a in cell["arms"])
    assert cell["any_bound_fired"] is any(a["bound_fired"] for a in cell["arms"])
    assert cell["in_law_domain"] is (not cell["any_width_fired"] and not cell["any_bound_fired"]
                                     and not cell["law_iii_fired"] and not s["fired"])
    assert st["in_accuracy_class"] is (st["ratio"] <= 1.4 and st["n_lambda"] >= 30)


def test_results_law_i_replays(sweep_json):
    cells = sweep_json["cells"]
    recs = w6.e1_scaling_checks(cells, sweep_json["ratios_all"], sweep_json["n_lambdas_all"])
    committed = sweep_json["law_i"]
    assert len(recs) == len(committed) == 6      # 3 ratios x {15, 60} vs 30
    for rec, com in zip(recs, committed):
        assert (rec["ratio"], rec["n_lambda"]) == (com["ratio"], com["n_lambda"])
        assert _rel_close(rec["model_ratio"], com["model_ratio"])
        if "meas_ratio" in com:
            assert _rel_close(rec["meas_ratio"], com["meas_ratio"])
            assert com["fired"] is (abs(com["meas_over_model"] - 1) > w6.E1_SCALING_TOL)


def test_results_control_cell_equals_lane_a(sweep_json, w6_json):
    cell = sweep_json["cells"].get(LANE_A_KEY)
    if cell is None or "arms" not in cell:
        pytest.skip("control cell not measured")
    lane_a = {r["n_b"]: r["R_meas"] for r in w6_json["f8"]["rows"]}
    for arm in cell["arms"]:
        assert _rel_close(arm["R_meas"], lane_a[arm["n_b"]], CONTROL_MEAS_REL), (
            arm["n_b"], arm["R_meas"], lane_a[arm["n_b"]])


def test_results_provenance(sweep_json):
    assert sweep_json["rfx_file"].endswith("rfx/__init__.py")
    assert len(sweep_json["git_sha"]) == 40
    assert sweep_json["model_only"] is False
    assert sweep_json["widths"] == [2, 4, 8, 16, 32]
    assert sweep_json["windows"]["per_arm"] == "|R_meas - R_model| <= 0.20 R_model + 3e-5"
